import type { LocalePath } from './config';

export interface BackgroundRemovalMessages {
  cleanup: string;
  cleanupHint: string;
  name: string;
  description: string;
  tagline: string;
  remove: string;
  before: string;
  after: string;
  loading: string;
  processing: string;
  result: string;
  invalid: string;
  tooLarge: string;
}

const messages: Record<LocalePath, BackgroundRemovalMessages> = {
  en: { cleanup: "Clean solid background", cleanupHint: "For a plain, single-color background. May remove matching subject colors; turn off if details disappear.", name: 'Remove Background', description: "Remove an image background automatically on your device.", tagline: "Review hair, thin lines, and openings before downloading.", remove: 'Remove background', before: 'Original', after: 'Transparent result', loading: "Preparing background removal…", processing: 'Removing the background…', result: "Transparent PNG at the original dimensions. Review the edges before use.", invalid: 'Choose a valid JPG, PNG, or WebP image.', tooLarge: 'This image is too large to process safely on this device. Choose one under 40 megapixels and 50 MB.' },
  ja: { cleanup: "単色の背景を調整", cleanupHint: "無地の単色背景向けです。同じ色の被写体も消える場合があります。細部が消えたらオフにしてください。", name: '背景を削除', description: "端末内で画像の背景を自動的に削除します。", tagline: "ダウンロード前に髪の毛、細い線、穴の部分を確認してください。", remove: '背景を削除', before: '元画像', after: '透明な結果', loading: "背景の削除を準備しています…", processing: '前景を端末内で分離しています…', result: "元の寸法の透過PNGです。使用前に輪郭を確認してください。", invalid: '有効なJPG、PNG、WebP画像を選んでください。', tooLarge: '端末メモリ保護のため、4000万画素・50MB未満の画像を選んでください。' },
  ko: { cleanup: "단색 배경 정리", cleanupHint: "단색 배경용입니다. 피사체의 같은 색도 지워질 수 있으니 세부가 사라지면 끄세요.", name: '배경 제거', description: "기기에서 이미지 배경을 자동으로 제거합니다.", tagline: "다운로드 전에 머리카락, 가는 선, 뚫린 부분을 확인하세요.", remove: '배경 제거', before: '원본', after: '투명 결과', loading: "배경 제거를 준비하는 중…", processing: '전경을 기기에서 분리하는 중…', result: "원본 크기의 투명 PNG입니다. 사용 전에 가장자리를 확인하세요.", invalid: '유효한 JPG, PNG 또는 WebP 이미지를 선택하세요.', tooLarge: '기기 메모리 보호를 위해 4천만 화소 및 50MB 미만 이미지를 선택하세요.' },
  es: { cleanup: "Limpiar fondo uniforme", cleanupHint: "Para fondos de un solo color. Puede borrar colores iguales del sujeto; desactívalo si desaparecen detalles.", name: 'Quitar fondo', description: "Elimina automáticamente el fondo de una imagen en tu dispositivo.", tagline: "Revisa el pelo, las líneas finas y los huecos antes de descargar.", remove: 'Quitar fondo', before: 'Original', after: 'Resultado transparente', loading: "Preparando la eliminación del fondo…", processing: 'Separando el primer plano localmente…', result: "PNG transparente con las dimensiones originales. Revisa los bordes antes de usarlo.", invalid: 'Elige una imagen JPG, PNG o WebP válida.', tooLarge: 'Elige una imagen de menos de 40 megapíxeles y 50 MB para proteger la memoria.' },
  fr: { cleanup: "Nettoyer le fond uni", cleanupHint: "Pour un fond d’une seule couleur. Les mêmes couleurs du sujet peuvent disparaître ; désactivez si des détails sont effacés.", name: 'Supprimer l’arrière-plan', description: "Supprimez automatiquement le fond d’une image sur votre appareil.", tagline: "Vérifiez les cheveux, les lignes fines et les ouvertures avant de télécharger.", remove: 'Supprimer l’arrière-plan', before: 'Original', after: 'Résultat transparent', loading: "Préparation de la suppression du fond…", processing: 'Séparation locale du premier plan…', result: "PNG transparent aux dimensions d’origine. Vérifiez les contours avant utilisation.", invalid: 'Choisissez une image JPG, PNG ou WebP valide.', tooLarge: 'Choisissez une image de moins de 40 mégapixels et 50 Mo.' },
  de: { cleanup: "Einfarbigen Hintergrund bereinigen", cleanupHint: "Für einfarbige Hintergründe. Kann gleiche Farben im Motiv entfernen; bei verlorenen Details ausschalten.", name: 'Hintergrund entfernen', description: "Entferne einen Bildhintergrund automatisch auf deinem Gerät.", tagline: "Prüfe Haare, dünne Linien und Öffnungen vor dem Herunterladen.", remove: 'Hintergrund entfernen', before: 'Original', after: 'Transparentes Ergebnis', loading: "Hintergrundentfernung wird vorbereitet…", processing: 'Vordergrund wird lokal getrennt…', result: "Transparentes PNG mit den ursprünglichen Abmessungen. Prüfe die Kanten vor der Verwendung.", invalid: 'Wähle ein gültiges JPG-, PNG- oder WebP-Bild.', tooLarge: 'Wähle zum Schutz des Gerätespeichers ein Bild unter 40 Megapixeln und 50 MB.' },
  pt: { cleanup: "Limpar fundo uniforme", cleanupHint: "Para fundos de uma só cor. Pode apagar cores iguais no objeto; desative se desaparecerem detalhes.", name: 'Remover fundo', description: "Remova automaticamente o fundo de uma imagem no seu dispositivo.", tagline: "Reveja o cabelo, as linhas finas e as aberturas antes de descarregar.", remove: 'Remover fundo', before: 'Original', after: 'Resultado transparente', loading: "Preparando a remoção do fundo…", processing: 'A separar o primeiro plano localmente…', result: "PNG transparente com as dimensões originais. Reveja os contornos antes de utilizar.", invalid: 'Escolha uma imagem JPG, PNG ou WebP válida.', tooLarge: 'Escolha uma imagem abaixo de 40 megapíxeis e 50 MB.' },
  'zh-cn': { cleanup: "清理纯色背景", cleanupHint: "适用于单一纯色背景。可能移除主体中的相同颜色；若细节消失，请关闭此选项。", name: '移除背景', description: "在设备上自动移除图片背景。", tagline: "下载前请检查头发、细线和镂空部分。", remove: '移除背景', before: '原图', after: '透明结果', loading: "正在准备移除背景…", processing: '正在本地分离前景…', result: "保持原始尺寸的透明PNG。使用前请检查边缘。", invalid: '请选择有效的JPG、PNG或WebP图片。', tooLarge: '为保护设备内存，请选择低于4000万像素和50MB的图片。' },
  'zh-tw': { cleanup: "清理純色背景", cleanupHint: "適用於單一純色背景。可能移除主體中的相同顏色；若細節消失，請關閉此選項。", name: '移除背景', description: "在裝置上自動移除圖片背景。", tagline: "下載前請檢查頭髮、細線與鏤空部分。", remove: '移除背景', before: '原圖', after: '透明結果', loading: "正在準備移除背景…", processing: '正在本機分離前景…', result: "保持原始尺寸的透明PNG。使用前請檢查邊緣。", invalid: '請選擇有效的JPG、PNG或WebP圖片。', tooLarge: '為保護裝置記憶體，請選擇低於4000萬畫素與50MB的圖片。' },
  hi: { cleanup: "एकरंगी बैकग्राउंड साफ करें", cleanupHint: "सादे, एक रंग के बैकग्राउंड के लिए। विषय के समान रंग भी मिट सकते हैं; विवरण गायब हों तो इसे बंद करें।", name: 'बैकग्राउंड हटाएँ', description: "अपने डिवाइस पर इमेज का बैकग्राउंड अपने आप हटाएँ।", tagline: "डाउनलोड से पहले बालों, पतली रेखाओं और खाली हिस्सों की जाँच करें।", remove: 'बैकग्राउंड हटाएँ', before: 'मूल', after: 'पारदर्शी परिणाम', loading: "बैकग्राउंड हटाने की तैयारी हो रही है…", processing: 'फोरग्राउंड लोकल अलग हो रहा है…', result: "मूल आकार का पारदर्शी PNG। उपयोग से पहले किनारों की जाँच करें।", invalid: 'सही JPG, PNG या WebP इमेज चुनें।', tooLarge: 'डिवाइस मेमोरी के लिए 40 मेगापिक्सेल और 50 MB से छोटी इमेज चुनें।' },
  ar: { cleanup: "تنظيف الخلفية الموحدة", cleanupHint: "لخلفية بلون واحد. قد تُحذف ألوان مطابقة من العنصر؛ عطّل الخيار إذا اختفت تفاصيل.", name: 'إزالة الخلفية', description: "أزل خلفية الصورة تلقائيًا على جهازك.", tagline: "راجع الشعر والخطوط الرفيعة والفتحات قبل التنزيل.", remove: 'إزالة الخلفية', before: 'الأصل', after: 'نتيجة شفافة', loading: "جارٍ التحضير لإزالة الخلفية…", processing: 'يجري فصل المقدمة محليًا…', result: "PNG شفاف بالأبعاد الأصلية. راجع الحواف قبل الاستخدام.", invalid: 'اختر صورة JPG أو PNG أو WebP صالحة.', tooLarge: 'اختر صورة أقل من 40 ميغابكسل و50 م.ب لحماية ذاكرة الجهاز.' },
  ru: { cleanup: "Очистить однотонный фон", cleanupHint: "Для фона одного цвета. Может удалить совпадающие цвета объекта; отключите, если пропадают детали.", name: 'Удалить фон', description: "Автоматически удаляйте фон изображения на своём устройстве.", tagline: "Перед скачиванием проверьте волосы, тонкие линии и отверстия.", remove: 'Удалить фон', before: 'Оригинал', after: 'Прозрачный результат', loading: "Подготовка к удалению фона…", processing: 'Локальное отделение объекта…', result: "Прозрачный PNG исходного размера. Проверьте края перед использованием.", invalid: 'Выберите корректное изображение JPG, PNG или WebP.', tooLarge: 'Выберите изображение меньше 40 мегапикселей и 50 МБ.' },
  id: { cleanup: "Bersihkan latar polos", cleanupHint: "Untuk latar satu warna. Warna objek yang sama dapat terhapus; matikan jika detail menghilang.", name: 'Hapus latar', description: "Hapus latar gambar secara otomatis di perangkat Anda.", tagline: "Periksa rambut, garis tipis, dan celah sebelum mengunduh.", remove: 'Hapus latar', before: 'Asli', after: 'Hasil transparan', loading: "Menyiapkan penghapusan latar belakang…", processing: 'Memisahkan latar depan secara lokal…', result: "PNG transparan dengan dimensi asli. Periksa tepinya sebelum digunakan.", invalid: 'Pilih gambar JPG, PNG, atau WebP yang valid.', tooLarge: 'Pilih gambar di bawah 40 megapiksel dan 50 MB.' },
  it: { cleanup: "Pulisci sfondo uniforme", cleanupHint: "Per sfondi di un solo colore. Può eliminare colori uguali del soggetto; disattiva se scompaiono dettagli.", name: 'Rimuovi sfondo', description: "Rimuovi automaticamente lo sfondo di un’immagine sul tuo dispositivo.", tagline: "Controlla capelli, linee sottili e aperture prima di scaricare.", remove: 'Rimuovi sfondo', before: 'Originale', after: 'Risultato trasparente', loading: "Preparazione della rimozione dello sfondo…", processing: 'Separazione locale del primo piano…', result: "PNG trasparente con le dimensioni originali. Controlla i bordi prima dell’uso.", invalid: 'Scegli un’immagine JPG, PNG o WebP valida.', tooLarge: 'Scegli un’immagine sotto 40 megapixel e 50 MB.' },
  nl: { cleanup: "Effen achtergrond opschonen", cleanupHint: "Voor een achtergrond met één kleur. Kan dezelfde kleuren in het onderwerp wissen; zet uit als details verdwijnen.", name: 'Achtergrond verwijderen', description: "Verwijder automatisch een afbeeldingsachtergrond op je apparaat.", tagline: "Controleer haar, dunne lijnen en openingen vóór het downloaden.", remove: 'Achtergrond verwijderen', before: 'Origineel', after: 'Transparant resultaat', loading: "Achtergrond verwijderen wordt voorbereid…", processing: 'Voorgrond wordt lokaal gescheiden…', result: "Transparante PNG met de oorspronkelijke afmetingen. Controleer de randen voor gebruik.", invalid: 'Kies een geldige JPG-, PNG- of WebP-afbeelding.', tooLarge: 'Kies een afbeelding onder 40 megapixels en 50 MB.' },
  tr: { cleanup: "Düz arka planı temizle", cleanupHint: "Tek renkli arka planlar içindir. Nesnenin aynı renklerini silebilir; ayrıntılar kaybolursa kapatın.", name: 'Arka planı kaldır', description: "Görsel arka planını cihazınızda otomatik olarak kaldırın.", tagline: "İndirmeden önce saçları, ince çizgileri ve boşlukları kontrol edin.", remove: 'Arka planı kaldır', before: 'Orijinal', after: 'Şeffaf sonuç', loading: "Arka plan kaldırma hazırlanıyor…", processing: 'Ön plan yerel olarak ayrılıyor…', result: "Özgün boyutlarda şeffaf PNG. Kullanmadan önce kenarları kontrol edin.", invalid: 'Geçerli bir JPG, PNG veya WebP görseli seçin.', tooLarge: 'Belleği korumak için 40 megapiksel ve 50 MB altı görsel seçin.' },
  vi: { cleanup: "Làm sạch nền một màu", cleanupHint: "Dành cho nền trơn một màu. Có thể xóa màu trùng trên chủ thể; tắt nếu chi tiết biến mất.", name: 'Xóa nền', description: "Tự động xóa nền ảnh trên thiết bị của bạn.", tagline: "Kiểm tra tóc, đường mảnh và khoảng trống trước khi tải xuống.", remove: 'Xóa nền', before: 'Gốc', after: 'Kết quả trong suốt', loading: "Đang chuẩn bị xóa nền…", processing: 'Đang tách tiền cảnh cục bộ…', result: "PNG trong suốt với kích thước gốc. Kiểm tra các cạnh trước khi dùng.", invalid: 'Chọn ảnh JPG, PNG hoặc WebP hợp lệ.', tooLarge: 'Chọn ảnh dưới 40 megapixel và 50 MB.' },
  th: { cleanup: "ทำความสะอาดพื้นหลังสีเดียว", cleanupHint: "สำหรับพื้นหลังเรียบสีเดียว อาจลบสีที่เหมือนกันบนวัตถุ ปิดหากรายละเอียดหายไป", name: 'ลบพื้นหลัง', description: "ลบพื้นหลังภาพโดยอัตโนมัติบนอุปกรณ์ของคุณ", tagline: "ตรวจสอบเส้นผม เส้นบาง และช่องว่างก่อนดาวน์โหลด", remove: 'ลบพื้นหลัง', before: 'ต้นฉบับ', after: 'ผลลัพธ์โปร่งใส', loading: "กำลังเตรียมลบพื้นหลัง…", processing: 'กำลังแยกฉากหน้าบนเครื่อง…', result: "PNG โปร่งใสขนาดเท่าต้นฉบับ ตรวจสอบขอบก่อนใช้งาน", invalid: 'เลือกภาพ JPG, PNG หรือ WebP ที่ถูกต้อง', tooLarge: 'เลือกภาพต่ำกว่า 40 เมกะพิกเซลและ 50 MB' },
  pl: { cleanup: "Oczyść jednolite tło", cleanupHint: "Do tła w jednym kolorze. Może usunąć takie same kolory obiektu; wyłącz, jeśli znikną szczegóły.", name: 'Usuń tło', description: "Automatycznie usuń tło obrazu na swoim urządzeniu.", tagline: "Przed pobraniem sprawdź włosy, cienkie linie i otwory.", remove: 'Usuń tło', before: 'Oryginał', after: 'Przezroczysty wynik', loading: "Przygotowywanie usuwania tła…", processing: 'Lokalne oddzielanie pierwszego planu…', result: "Przezroczysty PNG o oryginalnych wymiarach. Sprawdź krawędzie przed użyciem.", invalid: 'Wybierz prawidłowy obraz JPG, PNG lub WebP.', tooLarge: 'Wybierz obraz poniżej 40 megapikseli i 50 MB.' },
};

export function getBackgroundRemovalMessages(locale: LocalePath): BackgroundRemovalMessages {
  return messages[locale] ?? messages.en;
}
