import type { LocalePath } from './config';

export interface BackgroundRemovalMessages {
  name: string;
  description: string;
  tagline: string;
  remove: string;
  before: string;
  after: string;
  loading: string;
  processing: string;
  result: string;
  invalid: string;
  tooLarge: string;
}

const messages: Record<LocalePath, BackgroundRemovalMessages> = {
  en: { name: 'Remove Background', description: 'Remove image backgrounds locally with a high-quality AI matting engine.', tagline: 'Clean cutouts for logos, products, portraits, signatures, and stickers.', remove: 'Remove background', before: 'Original', after: 'Transparent result', loading: 'Downloading the private AI engine for first use…', processing: 'Separating the foreground locally…', result: 'Full-resolution transparent PNG. The original colors and dimensions are preserved.', invalid: 'Choose a valid JPG, PNG, or WebP image.', tooLarge: 'Choose an image under 40 megapixels and 50 MB to protect device memory.' },
  ja: { name: '背景を削除', description: '高品質AI切り抜きエンジンで画像の背景を端末内削除します。', tagline: 'ロゴ、商品、人物、署名、ステッカーをきれいに切り抜き。', remove: '背景を削除', before: '元画像', after: '透明な結果', loading: '初回用のプライベートAIエンジンをダウンロードしています…', processing: '前景を端末内で分離しています…', result: '元の色と寸法を保持したフル解像度の透過PNGです。', invalid: '有効なJPG、PNG、WebP画像を選んでください。', tooLarge: '端末メモリ保護のため、4000万画素・50MB未満の画像を選んでください。' },
  ko: { name: '배경 제거', description: '고품질 AI 매팅 엔진으로 이미지 배경을 기기에서 제거합니다.', tagline: '로고, 제품, 인물, 서명, 스티커를 깔끔하게 분리하세요.', remove: '배경 제거', before: '원본', after: '투명 결과', loading: '첫 사용용 비공개 AI 엔진을 다운로드하는 중…', processing: '전경을 기기에서 분리하는 중…', result: '원본 색상과 크기를 유지한 전체 해상도 투명 PNG입니다.', invalid: '유효한 JPG, PNG 또는 WebP 이미지를 선택하세요.', tooLarge: '기기 메모리 보호를 위해 4천만 화소 및 50MB 미만 이미지를 선택하세요.' },
  es: { name: 'Quitar fondo', description: 'Elimina fondos localmente con un motor de recorte por IA de alta calidad.', tagline: 'Recortes limpios para logotipos, productos, retratos, firmas y pegatinas.', remove: 'Quitar fondo', before: 'Original', after: 'Resultado transparente', loading: 'Descargando el motor privado de IA para el primer uso…', processing: 'Separando el primer plano localmente…', result: 'PNG transparente a resolución completa, con colores y dimensiones originales.', invalid: 'Elige una imagen JPG, PNG o WebP válida.', tooLarge: 'Elige una imagen de menos de 40 megapíxeles y 50 MB para proteger la memoria.' },
  fr: { name: 'Supprimer l’arrière-plan', description: 'Supprimez les arrière-plans localement avec un moteur de détourage IA haute qualité.', tagline: 'Détourages nets pour logos, produits, portraits, signatures et autocollants.', remove: 'Supprimer l’arrière-plan', before: 'Original', after: 'Résultat transparent', loading: 'Téléchargement du moteur IA privé pour la première utilisation…', processing: 'Séparation locale du premier plan…', result: 'PNG transparent en pleine résolution, avec couleurs et dimensions d’origine.', invalid: 'Choisissez une image JPG, PNG ou WebP valide.', tooLarge: 'Choisissez une image de moins de 40 mégapixels et 50 Mo.' },
  de: { name: 'Hintergrund entfernen', description: 'Bildhintergründe lokal mit hochwertiger KI-Freistellung entfernen.', tagline: 'Saubere Freisteller für Logos, Produkte, Porträts, Signaturen und Sticker.', remove: 'Hintergrund entfernen', before: 'Original', after: 'Transparentes Ergebnis', loading: 'Private KI-Engine wird für die erste Nutzung geladen…', processing: 'Vordergrund wird lokal getrennt…', result: 'Transparentes PNG in voller Auflösung; Farben und Abmessungen bleiben erhalten.', invalid: 'Wähle ein gültiges JPG-, PNG- oder WebP-Bild.', tooLarge: 'Wähle zum Schutz des Gerätespeichers ein Bild unter 40 Megapixeln und 50 MB.' },
  pt: { name: 'Remover fundo', description: 'Remova fundos localmente com um motor de recorte por IA de alta qualidade.', tagline: 'Recortes limpos para logótipos, produtos, retratos, assinaturas e autocolantes.', remove: 'Remover fundo', before: 'Original', after: 'Resultado transparente', loading: 'A descarregar o motor de IA privado para a primeira utilização…', processing: 'A separar o primeiro plano localmente…', result: 'PNG transparente em resolução total, com cores e dimensões originais.', invalid: 'Escolha uma imagem JPG, PNG ou WebP válida.', tooLarge: 'Escolha uma imagem abaixo de 40 megapíxeis e 50 MB.' },
  'zh-cn': { name: '移除背景', description: '使用高质量AI抠图引擎在本地移除图片背景。', tagline: '适用于徽标、商品、人像、签名和贴纸的干净抠图。', remove: '移除背景', before: '原图', after: '透明结果', loading: '正在下载首次使用的私密AI引擎…', processing: '正在本地分离前景…', result: '全分辨率透明PNG，保留原始颜色和尺寸。', invalid: '请选择有效的JPG、PNG或WebP图片。', tooLarge: '为保护设备内存，请选择低于4000万像素和50MB的图片。' },
  'zh-tw': { name: '移除背景', description: '使用高品質AI去背引擎在本機移除圖片背景。', tagline: '適用於標誌、商品、人像、簽名與貼紙的乾淨去背。', remove: '移除背景', before: '原圖', after: '透明結果', loading: '正在下載首次使用的私密AI引擎…', processing: '正在本機分離前景…', result: '全解析度透明PNG，保留原始色彩與尺寸。', invalid: '請選擇有效的JPG、PNG或WebP圖片。', tooLarge: '為保護裝置記憶體，請選擇低於4000萬畫素與50MB的圖片。' },
  hi: { name: 'बैकग्राउंड हटाएँ', description: 'उच्च-गुणवत्ता AI मैटिंग इंजन से इमेज का बैकग्राउंड लोकल हटाएँ।', tagline: 'लोगो, उत्पाद, पोर्ट्रेट, हस्ताक्षर और स्टिकर के साफ कटआउट।', remove: 'बैकग्राउंड हटाएँ', before: 'मूल', after: 'पारदर्शी परिणाम', loading: 'पहली बार के लिए निजी AI इंजन डाउनलोड हो रहा है…', processing: 'फोरग्राउंड लोकल अलग हो रहा है…', result: 'मूल रंग व आकार वाला पूर्ण-रिज़ॉल्यूशन पारदर्शी PNG।', invalid: 'सही JPG, PNG या WebP इमेज चुनें।', tooLarge: 'डिवाइस मेमोरी के लिए 40 मेगापिक्सेल और 50 MB से छोटी इमेज चुनें।' },
  ar: { name: 'إزالة الخلفية', description: 'أزل خلفية الصورة محليًا بمحرك قص ذكي عالي الجودة.', tagline: 'قص نظيف للشعارات والمنتجات والصور الشخصية والتواقيع والملصقات.', remove: 'إزالة الخلفية', before: 'الأصل', after: 'نتيجة شفافة', loading: 'يجري تنزيل محرك الذكاء الخاص للاستخدام الأول…', processing: 'يجري فصل المقدمة محليًا…', result: 'PNG شفاف بالدقة الكاملة مع الحفاظ على الألوان والأبعاد الأصلية.', invalid: 'اختر صورة JPG أو PNG أو WebP صالحة.', tooLarge: 'اختر صورة أقل من 40 ميغابكسل و50 م.ب لحماية ذاكرة الجهاز.' },
  ru: { name: 'Удалить фон', description: 'Удаляйте фон локально высококачественным ИИ-движком маттинга.', tagline: 'Чистые вырезки логотипов, товаров, портретов, подписей и стикеров.', remove: 'Удалить фон', before: 'Оригинал', after: 'Прозрачный результат', loading: 'Загрузка приватного ИИ-движка для первого запуска…', processing: 'Локальное отделение объекта…', result: 'Прозрачный PNG полного разрешения с исходными цветами и размерами.', invalid: 'Выберите корректное изображение JPG, PNG или WebP.', tooLarge: 'Выберите изображение меньше 40 мегапикселей и 50 МБ.' },
  id: { name: 'Hapus latar', description: 'Hapus latar gambar secara lokal dengan mesin matting AI berkualitas tinggi.', tagline: 'Potongan rapi untuk logo, produk, potret, tanda tangan, dan stiker.', remove: 'Hapus latar', before: 'Asli', after: 'Hasil transparan', loading: 'Mengunduh mesin AI privat untuk penggunaan pertama…', processing: 'Memisahkan latar depan secara lokal…', result: 'PNG transparan resolusi penuh dengan warna dan dimensi asli.', invalid: 'Pilih gambar JPG, PNG, atau WebP yang valid.', tooLarge: 'Pilih gambar di bawah 40 megapiksel dan 50 MB.' },
  it: { name: 'Rimuovi sfondo', description: 'Rimuovi lo sfondo localmente con un motore IA di scontorno di alta qualità.', tagline: 'Ritagli puliti per loghi, prodotti, ritratti, firme e adesivi.', remove: 'Rimuovi sfondo', before: 'Originale', after: 'Risultato trasparente', loading: 'Download del motore IA privato per il primo utilizzo…', processing: 'Separazione locale del primo piano…', result: 'PNG trasparente a piena risoluzione con colori e dimensioni originali.', invalid: 'Scegli un’immagine JPG, PNG o WebP valida.', tooLarge: 'Scegli un’immagine sotto 40 megapixel e 50 MB.' },
  nl: { name: 'Achtergrond verwijderen', description: 'Verwijder beeldachtergronden lokaal met hoogwaardige AI-matting.', tagline: 'Strakke uitsneden voor logo’s, producten, portretten, handtekeningen en stickers.', remove: 'Achtergrond verwijderen', before: 'Origineel', after: 'Transparant resultaat', loading: 'Privé-AI-engine wordt voor het eerste gebruik gedownload…', processing: 'Voorgrond wordt lokaal gescheiden…', result: 'Transparante PNG op volledige resolutie met oorspronkelijke kleuren en afmetingen.', invalid: 'Kies een geldige JPG-, PNG- of WebP-afbeelding.', tooLarge: 'Kies een afbeelding onder 40 megapixels en 50 MB.' },
  tr: { name: 'Arka planı kaldır', description: 'Yüksek kaliteli AI matlaştırma motoruyla görsel arka planını yerel olarak kaldırın.', tagline: 'Logo, ürün, portre, imza ve çıkartmalar için temiz kesimler.', remove: 'Arka planı kaldır', before: 'Orijinal', after: 'Şeffaf sonuç', loading: 'İlk kullanım için özel AI motoru indiriliyor…', processing: 'Ön plan yerel olarak ayrılıyor…', result: 'Özgün renk ve boyutları koruyan tam çözünürlüklü şeffaf PNG.', invalid: 'Geçerli bir JPG, PNG veya WebP görseli seçin.', tooLarge: 'Belleği korumak için 40 megapiksel ve 50 MB altı görsel seçin.' },
  vi: { name: 'Xóa nền', description: 'Xóa nền ảnh cục bộ bằng công cụ tách nền AI chất lượng cao.', tagline: 'Tách sạch logo, sản phẩm, chân dung, chữ ký và nhãn dán.', remove: 'Xóa nền', before: 'Gốc', after: 'Kết quả trong suốt', loading: 'Đang tải công cụ AI riêng tư cho lần dùng đầu…', processing: 'Đang tách tiền cảnh cục bộ…', result: 'PNG trong suốt độ phân giải đầy đủ, giữ màu và kích thước gốc.', invalid: 'Chọn ảnh JPG, PNG hoặc WebP hợp lệ.', tooLarge: 'Chọn ảnh dưới 40 megapixel và 50 MB.' },
  th: { name: 'ลบพื้นหลัง', description: 'ลบพื้นหลังบนเครื่องด้วยเอนจิน AI แยกภาพคุณภาพสูง', tagline: 'ไดคัทสะอาดสำหรับโลโก้ สินค้า บุคคล ลายเซ็น และสติกเกอร์', remove: 'ลบพื้นหลัง', before: 'ต้นฉบับ', after: 'ผลลัพธ์โปร่งใส', loading: 'กำลังดาวน์โหลดเอนจิน AI ส่วนตัวสำหรับครั้งแรก…', processing: 'กำลังแยกฉากหน้าบนเครื่อง…', result: 'PNG โปร่งใสความละเอียดเต็ม โดยคงสีและขนาดเดิม', invalid: 'เลือกภาพ JPG, PNG หรือ WebP ที่ถูกต้อง', tooLarge: 'เลือกภาพต่ำกว่า 40 เมกะพิกเซลและ 50 MB' },
  pl: { name: 'Usuń tło', description: 'Usuwaj tło lokalnie wysokiej jakości silnikiem mattingu AI.', tagline: 'Czyste wycięcia logo, produktów, portretów, podpisów i naklejek.', remove: 'Usuń tło', before: 'Oryginał', after: 'Przezroczysty wynik', loading: 'Pobieranie prywatnego silnika AI do pierwszego użycia…', processing: 'Lokalne oddzielanie pierwszego planu…', result: 'Przezroczysty PNG w pełnej rozdzielczości z oryginalnymi kolorami i wymiarami.', invalid: 'Wybierz prawidłowy obraz JPG, PNG lub WebP.', tooLarge: 'Wybierz obraz poniżej 40 megapikseli i 50 MB.' },
};

export function getBackgroundRemovalMessages(locale: LocalePath): BackgroundRemovalMessages {
  return messages[locale] ?? messages.en;
}
