import type { LocalePath } from './config';

export interface WatermarkPdfMessages {
  watermarkType: string;
  text: string;
  image: string;
  uploadImage: string;
  imageHelp: string;
  imageTreatment: string;
  useAsIs: string;
  useAsIsHelp: string;
  removeBackground: string;
  removeBackgroundHelp: string;
  cleanupStrength: string;
  before: string;
  after: string;
  beforeAlt: string;
  afterAlt: string;
  missingImage: string;
  tooLarge: string;
  tooManyPixels: string;
  decodeFailed: string;
}

const watermarkPdfMessages: Record<LocalePath, WatermarkPdfMessages> = {
  en: { watermarkType: 'Watermark type', text: 'Text', image: 'Image', uploadImage: 'Upload watermark image', imageHelp: 'PNG, JPG, or WebP · up to 10 MB and 20 megapixels', imageTreatment: 'Background treatment', useAsIs: 'Use image as-is', useAsIsHelp: 'Keep the uploaded image and its existing background.', removeBackground: 'Remove background', removeBackgroundHelp: 'Make the sampled edge color transparent before placing the watermark.', cleanupStrength: 'Background removal strength', before: 'Before', after: 'Watermark preview', beforeAlt: 'Uploaded watermark before background processing', afterAlt: 'Watermark image that will be placed in the PDF', missingImage: 'Upload a watermark image before processing.', tooLarge: 'Choose a watermark image smaller than 10 MB.', tooManyPixels: 'Choose a watermark image under 20 megapixels.', decodeFailed: 'This watermark image could not be decoded. Choose a valid PNG, JPG, or WebP file.' },
  ja: { watermarkType: '透かしの種類', text: 'テキスト', image: '画像', uploadImage: '透かし画像をアップロード', imageHelp: 'PNG、JPG、WebP · 10 MB・2000万画素まで', imageTreatment: '背景の処理', useAsIs: '画像をそのまま使用', useAsIsHelp: 'アップロードした画像と現在の背景を保持します。', removeBackground: '背景を削除', removeBackgroundHelp: '端の色を透明にしてから透かしを配置します。', cleanupStrength: '背景削除の強さ', before: '処理前', after: '透かしプレビュー', beforeAlt: '背景処理前のアップロード画像', afterAlt: 'PDFに配置される透かし画像', missingImage: '処理する前に透かし画像をアップロードしてください。', tooLarge: '10 MB未満の透かし画像を選択してください。', tooManyPixels: '2000万画素未満の透かし画像を選択してください。', decodeFailed: '画像を読み取れません。正しいPNG、JPG、WebPを選択してください。' },
  ko: { watermarkType: '워터마크 유형', text: '텍스트', image: '이미지', uploadImage: '워터마크 이미지 업로드', imageHelp: 'PNG, JPG 또는 WebP · 최대 10 MB 및 2천만 화소', imageTreatment: '배경 처리', useAsIs: '이미지 그대로 사용', useAsIsHelp: '업로드한 이미지와 기존 배경을 유지합니다.', removeBackground: '배경 제거', removeBackgroundHelp: '가장자리에서 추정한 색을 투명하게 만든 뒤 배치합니다.', cleanupStrength: '배경 제거 강도', before: '처리 전', after: '워터마크 미리보기', beforeAlt: '배경 처리 전 워터마크 이미지', afterAlt: 'PDF에 배치될 워터마크 이미지', missingImage: '처리하기 전에 워터마크 이미지를 업로드하세요.', tooLarge: '10 MB보다 작은 이미지를 선택하세요.', tooManyPixels: '2천만 화소 미만 이미지를 선택하세요.', decodeFailed: '이미지를 읽을 수 없습니다. 올바른 PNG, JPG 또는 WebP를 선택하세요.' },
  es: { watermarkType: 'Tipo de marca de agua', text: 'Texto', image: 'Imagen', uploadImage: 'Subir imagen de marca de agua', imageHelp: 'PNG, JPG o WebP · hasta 10 MB y 20 megapíxeles', imageTreatment: 'Tratamiento del fondo', useAsIs: 'Usar la imagen tal cual', useAsIsHelp: 'Conserva la imagen subida y su fondo actual.', removeBackground: 'Quitar el fondo', removeBackgroundHelp: 'Convierte en transparente el color detectado en los bordes.', cleanupStrength: 'Intensidad de eliminación', before: 'Antes', after: 'Vista previa', beforeAlt: 'Marca de agua antes de procesar el fondo', afterAlt: 'Marca de agua que se colocará en el PDF', missingImage: 'Sube una imagen de marca de agua antes de procesar.', tooLarge: 'Elige una imagen menor de 10 MB.', tooManyPixels: 'Elige una imagen de menos de 20 megapíxeles.', decodeFailed: 'No se pudo leer la imagen. Elige un PNG, JPG o WebP válido.' },
  fr: { watermarkType: 'Type de filigrane', text: 'Texte', image: 'Image', uploadImage: 'Importer une image de filigrane', imageHelp: 'PNG, JPG ou WebP · 10 Mo et 20 mégapixels maximum', imageTreatment: 'Traitement de l’arrière-plan', useAsIs: 'Utiliser l’image telle quelle', useAsIsHelp: 'Conserve l’image importée et son arrière-plan actuel.', removeBackground: 'Supprimer l’arrière-plan', removeBackgroundHelp: 'Rend transparente la couleur détectée sur les bords.', cleanupStrength: 'Intensité de suppression', before: 'Avant', after: 'Aperçu du filigrane', beforeAlt: 'Filigrane avant le traitement de l’arrière-plan', afterAlt: 'Filigrane qui sera placé dans le PDF', missingImage: 'Importez une image de filigrane avant de traiter le PDF.', tooLarge: 'Choisissez une image de moins de 10 Mo.', tooManyPixels: 'Choisissez une image de moins de 20 mégapixels.', decodeFailed: 'Impossible de lire cette image. Choisissez un PNG, JPG ou WebP valide.' },
  de: { watermarkType: 'Wasserzeichentyp', text: 'Text', image: 'Bild', uploadImage: 'Wasserzeichenbild hochladen', imageHelp: 'PNG, JPG oder WebP · bis 10 MB und 20 Megapixel', imageTreatment: 'Hintergrundbehandlung', useAsIs: 'Bild unverändert verwenden', useAsIsHelp: 'Behält das hochgeladene Bild und seinen vorhandenen Hintergrund.', removeBackground: 'Hintergrund entfernen', removeBackgroundHelp: 'Macht die an den Rändern erkannte Farbe transparent.', cleanupStrength: 'Stärke der Hintergrundentfernung', before: 'Vorher', after: 'Wasserzeichenvorschau', beforeAlt: 'Wasserzeichen vor der Hintergrundbearbeitung', afterAlt: 'Wasserzeichen, das im PDF platziert wird', missingImage: 'Lade vor der Verarbeitung ein Wasserzeichenbild hoch.', tooLarge: 'Wähle ein Bild unter 10 MB.', tooManyPixels: 'Wähle ein Bild unter 20 Megapixel.', decodeFailed: 'Das Bild konnte nicht gelesen werden. Wähle eine gültige PNG-, JPG- oder WebP-Datei.' },
  pt: { watermarkType: 'Tipo de marca de água', text: 'Texto', image: 'Imagem', uploadImage: 'Carregar imagem de marca de água', imageHelp: 'PNG, JPG ou WebP · até 10 MB e 20 megapíxeis', imageTreatment: 'Tratamento do fundo', useAsIs: 'Usar imagem como está', useAsIsHelp: 'Mantém a imagem carregada e o fundo existente.', removeBackground: 'Remover fundo', removeBackgroundHelp: 'Torna transparente a cor detetada nas margens.', cleanupStrength: 'Intensidade da remoção', before: 'Antes', after: 'Pré-visualização', beforeAlt: 'Marca de água antes do tratamento do fundo', afterAlt: 'Marca de água que será colocada no PDF', missingImage: 'Carregue uma imagem de marca de água antes de processar.', tooLarge: 'Escolha uma imagem inferior a 10 MB.', tooManyPixels: 'Escolha uma imagem com menos de 20 megapíxeis.', decodeFailed: 'Não foi possível ler a imagem. Escolha um PNG, JPG ou WebP válido.' },
  'zh-cn': { watermarkType: '水印类型', text: '文字', image: '图片', uploadImage: '上传水印图片', imageHelp: 'PNG、JPG 或 WebP · 不超过 10 MB 和 2000 万像素', imageTreatment: '背景处理', useAsIs: '原样使用图片', useAsIsHelp: '保留上传图片及其现有背景。', removeBackground: '移除背景', removeBackgroundHelp: '放置水印前，将边缘检测到的颜色变为透明。', cleanupStrength: '背景移除强度', before: '处理前', after: '水印预览', beforeAlt: '背景处理前的水印图片', afterAlt: '将放入 PDF 的水印图片', missingImage: '请先上传水印图片。', tooLarge: '请选择小于 10 MB 的图片。', tooManyPixels: '请选择低于 2000 万像素的图片。', decodeFailed: '无法读取图片。请选择有效的 PNG、JPG 或 WebP 文件。' },
  'zh-tw': { watermarkType: '浮水印類型', text: '文字', image: '圖片', uploadImage: '上傳浮水印圖片', imageHelp: 'PNG、JPG 或 WebP · 不超過 10 MB 與 2000 萬像素', imageTreatment: '背景處理', useAsIs: '原樣使用圖片', useAsIsHelp: '保留上傳圖片與目前背景。', removeBackground: '移除背景', removeBackgroundHelp: '放置浮水印前，將邊緣偵測到的顏色變透明。', cleanupStrength: '背景移除強度', before: '處理前', after: '浮水印預覽', beforeAlt: '背景處理前的浮水印圖片', afterAlt: '將放入 PDF 的浮水印圖片', missingImage: '請先上傳浮水印圖片。', tooLarge: '請選擇小於 10 MB 的圖片。', tooManyPixels: '請選擇低於 2000 萬像素的圖片。', decodeFailed: '無法讀取圖片。請選擇有效的 PNG、JPG 或 WebP 檔案。' },
  hi: { watermarkType: 'वॉटरमार्क प्रकार', text: 'टेक्स्ट', image: 'इमेज', uploadImage: 'वॉटरमार्क इमेज अपलोड करें', imageHelp: 'PNG, JPG या WebP · अधिकतम 10 MB और 20 मेगापिक्सेल', imageTreatment: 'बैकग्राउंड विकल्प', useAsIs: 'इमेज जैसी है वैसी रखें', useAsIsHelp: 'अपलोड की गई इमेज और उसका मौजूदा बैकग्राउंड रखें।', removeBackground: 'बैकग्राउंड हटाएँ', removeBackgroundHelp: 'किनारों से पहचाने रंग को पारदर्शी बनाकर वॉटरमार्क लगाएँ।', cleanupStrength: 'बैकग्राउंड हटाने की तीव्रता', before: 'पहले', after: 'वॉटरमार्क पूर्वावलोकन', beforeAlt: 'बैकग्राउंड प्रक्रिया से पहले वॉटरमार्क', afterAlt: 'PDF में लगाया जाने वाला वॉटरमार्क', missingImage: 'प्रोसेस करने से पहले वॉटरमार्क इमेज अपलोड करें।', tooLarge: '10 MB से छोटी इमेज चुनें।', tooManyPixels: '20 मेगापिक्सेल से छोटी इमेज चुनें।', decodeFailed: 'इमेज पढ़ी नहीं जा सकी। सही PNG, JPG या WebP चुनें।' },
  ar: { watermarkType: 'نوع العلامة المائية', text: 'نص', image: 'صورة', uploadImage: 'رفع صورة العلامة المائية', imageHelp: 'PNG أو JPG أو WebP · حتى 10 م.ب و20 ميغابكسل', imageTreatment: 'معالجة الخلفية', useAsIs: 'استخدام الصورة كما هي', useAsIsHelp: 'يحافظ على الصورة المرفوعة وخلفيتها الحالية.', removeBackground: 'إزالة الخلفية', removeBackgroundHelp: 'يجعل اللون المكتشف عند الحواف شفافًا قبل وضع العلامة.', cleanupStrength: 'قوة إزالة الخلفية', before: 'قبل', after: 'معاينة العلامة', beforeAlt: 'العلامة المائية قبل معالجة الخلفية', afterAlt: 'العلامة المائية التي ستوضع في PDF', missingImage: 'ارفع صورة علامة مائية قبل المعالجة.', tooLarge: 'اختر صورة أصغر من 10 م.ب.', tooManyPixels: 'اختر صورة أقل من 20 ميغابكسل.', decodeFailed: 'تعذر قراءة الصورة. اختر ملف PNG أو JPG أو WebP صالحًا.' },
  ru: { watermarkType: 'Тип водяного знака', text: 'Текст', image: 'Изображение', uploadImage: 'Загрузить изображение водяного знака', imageHelp: 'PNG, JPG или WebP · до 10 МБ и 20 мегапикселей', imageTreatment: 'Обработка фона', useAsIs: 'Использовать как есть', useAsIsHelp: 'Сохраняет загруженное изображение и его текущий фон.', removeBackground: 'Удалить фон', removeBackgroundHelp: 'Делает цвет, найденный по краям, прозрачным.', cleanupStrength: 'Сила удаления фона', before: 'До', after: 'Предпросмотр', beforeAlt: 'Водяной знак до обработки фона', afterAlt: 'Водяной знак, который будет помещён в PDF', missingImage: 'Загрузите изображение водяного знака перед обработкой.', tooLarge: 'Выберите изображение меньше 10 МБ.', tooManyPixels: 'Выберите изображение меньше 20 мегапикселей.', decodeFailed: 'Не удалось прочитать изображение. Выберите корректный PNG, JPG или WebP.' },
  id: { watermarkType: 'Jenis watermark', text: 'Teks', image: 'Gambar', uploadImage: 'Unggah gambar watermark', imageHelp: 'PNG, JPG, atau WebP · hingga 10 MB dan 20 megapiksel', imageTreatment: 'Perlakuan latar', useAsIs: 'Gunakan gambar apa adanya', useAsIsHelp: 'Mempertahankan gambar unggahan dan latarnya.', removeBackground: 'Hapus latar', removeBackgroundHelp: 'Membuat warna yang terdeteksi di tepi menjadi transparan.', cleanupStrength: 'Kekuatan penghapusan latar', before: 'Sebelum', after: 'Pratinjau watermark', beforeAlt: 'Watermark sebelum pemrosesan latar', afterAlt: 'Watermark yang akan ditempatkan di PDF', missingImage: 'Unggah gambar watermark sebelum memproses.', tooLarge: 'Pilih gambar di bawah 10 MB.', tooManyPixels: 'Pilih gambar di bawah 20 megapiksel.', decodeFailed: 'Gambar tidak dapat dibaca. Pilih PNG, JPG, atau WebP yang valid.' },
  it: { watermarkType: 'Tipo di filigrana', text: 'Testo', image: 'Immagine', uploadImage: 'Carica immagine filigrana', imageHelp: 'PNG, JPG o WebP · fino a 10 MB e 20 megapixel', imageTreatment: 'Trattamento dello sfondo', useAsIs: 'Usa l’immagine così com’è', useAsIsHelp: 'Mantiene l’immagine caricata e lo sfondo esistente.', removeBackground: 'Rimuovi lo sfondo', removeBackgroundHelp: 'Rende trasparente il colore rilevato sui bordi.', cleanupStrength: 'Intensità della rimozione', before: 'Prima', after: 'Anteprima filigrana', beforeAlt: 'Filigrana prima del trattamento dello sfondo', afterAlt: 'Filigrana che verrà inserita nel PDF', missingImage: 'Carica un’immagine filigrana prima di elaborare.', tooLarge: 'Scegli un’immagine sotto 10 MB.', tooManyPixels: 'Scegli un’immagine sotto 20 megapixel.', decodeFailed: 'Impossibile leggere l’immagine. Scegli un PNG, JPG o WebP valido.' },
  nl: { watermarkType: 'Type watermerk', text: 'Tekst', image: 'Afbeelding', uploadImage: 'Watermerkafbeelding uploaden', imageHelp: 'PNG, JPG of WebP · maximaal 10 MB en 20 megapixels', imageTreatment: 'Achtergrondverwerking', useAsIs: 'Afbeelding ongewijzigd gebruiken', useAsIsHelp: 'Behoudt de geüploade afbeelding en bestaande achtergrond.', removeBackground: 'Achtergrond verwijderen', removeBackgroundHelp: 'Maakt de aan de randen gevonden kleur transparant.', cleanupStrength: 'Sterkte achtergrondverwijdering', before: 'Voor', after: 'Watermerkvoorbeeld', beforeAlt: 'Watermerk vóór achtergrondverwerking', afterAlt: 'Watermerk dat in de PDF wordt geplaatst', missingImage: 'Upload eerst een watermerkafbeelding.', tooLarge: 'Kies een afbeelding kleiner dan 10 MB.', tooManyPixels: 'Kies een afbeelding onder 20 megapixels.', decodeFailed: 'De afbeelding kon niet worden gelezen. Kies een geldige PNG, JPG of WebP.' },
  tr: { watermarkType: 'Filigran türü', text: 'Metin', image: 'Görsel', uploadImage: 'Filigran görseli yükle', imageHelp: 'PNG, JPG veya WebP · en fazla 10 MB ve 20 megapiksel', imageTreatment: 'Arka plan işlemi', useAsIs: 'Görseli olduğu gibi kullan', useAsIsHelp: 'Yüklenen görseli ve mevcut arka planını korur.', removeBackground: 'Arka planı kaldır', removeBackgroundHelp: 'Kenarlarda algılanan rengi şeffaf yapar.', cleanupStrength: 'Arka plan kaldırma gücü', before: 'Önce', after: 'Filigran önizlemesi', beforeAlt: 'Arka plan işleminden önce filigran', afterAlt: 'PDF’ye yerleştirilecek filigran', missingImage: 'İşlemeden önce filigran görseli yükleyin.', tooLarge: '10 MB’tan küçük bir görsel seçin.', tooManyPixels: '20 megapikselden küçük bir görsel seçin.', decodeFailed: 'Görsel okunamadı. Geçerli bir PNG, JPG veya WebP seçin.' },
  vi: { watermarkType: 'Loại hình mờ', text: 'Văn bản', image: 'Hình ảnh', uploadImage: 'Tải ảnh hình mờ lên', imageHelp: 'PNG, JPG hoặc WebP · tối đa 10 MB và 20 megapixel', imageTreatment: 'Xử lý nền', useAsIs: 'Dùng nguyên ảnh', useAsIsHelp: 'Giữ nguyên ảnh tải lên và nền hiện có.', removeBackground: 'Xóa nền', removeBackgroundHelp: 'Làm trong suốt màu được phát hiện ở các cạnh.', cleanupStrength: 'Mức xóa nền', before: 'Trước', after: 'Xem trước hình mờ', beforeAlt: 'Hình mờ trước khi xử lý nền', afterAlt: 'Hình mờ sẽ được đặt vào PDF', missingImage: 'Hãy tải ảnh hình mờ lên trước khi xử lý.', tooLarge: 'Chọn ảnh nhỏ hơn 10 MB.', tooManyPixels: 'Chọn ảnh dưới 20 megapixel.', decodeFailed: 'Không thể đọc ảnh. Hãy chọn PNG, JPG hoặc WebP hợp lệ.' },
  th: { watermarkType: 'ประเภทลายน้ำ', text: 'ข้อความ', image: 'รูปภาพ', uploadImage: 'อัปโหลดรูปลายน้ำ', imageHelp: 'PNG, JPG หรือ WebP · สูงสุด 10 MB และ 20 เมกะพิกเซล', imageTreatment: 'การจัดการพื้นหลัง', useAsIs: 'ใช้รูปตามที่อัปโหลด', useAsIsHelp: 'คงรูปที่อัปโหลดและพื้นหลังเดิมไว้', removeBackground: 'ลบพื้นหลัง', removeBackgroundHelp: 'ทำให้สีที่ตรวจพบจากขอบโปร่งใสก่อนวางลายน้ำ', cleanupStrength: 'ระดับการลบพื้นหลัง', before: 'ก่อน', after: 'ตัวอย่างลายน้ำ', beforeAlt: 'ลายน้ำก่อนประมวลผลพื้นหลัง', afterAlt: 'ลายน้ำที่จะวางใน PDF', missingImage: 'อัปโหลดรูปลายน้ำก่อนประมวลผล', tooLarge: 'เลือกรูปที่เล็กกว่า 10 MB', tooManyPixels: 'เลือกรูปที่ต่ำกว่า 20 เมกะพิกเซล', decodeFailed: 'อ่านรูปไม่ได้ โปรดเลือก PNG, JPG หรือ WebP ที่ถูกต้อง' },
  pl: { watermarkType: 'Typ znaku wodnego', text: 'Tekst', image: 'Obraz', uploadImage: 'Prześlij obraz znaku wodnego', imageHelp: 'PNG, JPG lub WebP · do 10 MB i 20 megapikseli', imageTreatment: 'Obsługa tła', useAsIs: 'Użyj obrazu bez zmian', useAsIsHelp: 'Zachowuje przesłany obraz i jego obecne tło.', removeBackground: 'Usuń tło', removeBackgroundHelp: 'Ustawia wykryty na krawędziach kolor jako przezroczysty.', cleanupStrength: 'Siła usuwania tła', before: 'Przed', after: 'Podgląd znaku', beforeAlt: 'Znak wodny przed obróbką tła', afterAlt: 'Znak wodny, który zostanie umieszczony w PDF', missingImage: 'Prześlij obraz znaku wodnego przed przetwarzaniem.', tooLarge: 'Wybierz obraz mniejszy niż 10 MB.', tooManyPixels: 'Wybierz obraz poniżej 20 megapikseli.', decodeFailed: 'Nie udało się odczytać obrazu. Wybierz prawidłowy PNG, JPG lub WebP.' },
};

export function getWatermarkPdfMessages(locale: LocalePath): WatermarkPdfMessages {
  return watermarkPdfMessages[locale] ?? watermarkPdfMessages.en;
}
