import type { LocalePath } from './config';

export interface WatermarkPdfMessages {
  watermarkType: string;
  text: string;
  image: string;
  uploadImage: string;
  imageHelp: string;
  imageTreatment: string;
  useAsIs: string;
  useAsIsHelp: string;
  removeBackground: string;
  removeBackgroundHelp: string;
  cleanupStrength: string;
  before: string;
  after: string;
  beforeAlt: string;
  afterAlt: string;
  missingImage: string;
  tooLarge: string;
  tooManyPixels: string;
  decodeFailed: string;
}

export interface ConversionFidelityMessages {
  exactAppearance: string;
  pdfToWordNote: string;
  wordToPdfNote: string;
  renderingDocument: string;
  renderingPage: string;
  assembling: string;
  pdfToWordResult: string;
  wordToPdfResult: string;
  officeIsolation: string;
  officeFailed: string;
}

const conversionFidelityMessages: Record<LocalePath, Omit<ConversionFidelityMessages, 'officeIsolation' | 'officeFailed'>> = {
  en: { exactAppearance: 'Exact appearance', pdfToWordNote: 'Every PDF page is preserved as a full-page visual in Word, including text, spacing, logos, and images. The appearance stays intact; page content is not editable.', wordToPdfNote: 'The DOCX is rendered page by page with its fonts, spacing, images, tables, headers, and footers, then preserved visually in PDF. The result is flattened and its text is not selectable.', renderingDocument: 'Rendering the document locally…', renderingPage: 'Rendering page {current} of {total}…', assembling: 'Assembling the high-fidelity file…', pdfToWordResult: 'Exact appearance preserved. Pages are full-page visuals, so Word text is not editable.', wordToPdfResult: 'Exact appearance preserved as page visuals. Text in the PDF is not selectable.' },
  ja: { exactAppearance: '見た目を正確に保持', pdfToWordNote: '文字、間隔、ロゴ、画像を含む各PDFページを、Word内の全面画像として保持します。見た目は保たれますが、ページ内容は編集できません。', wordToPdfNote: 'DOCXをフォント、間隔、画像、表、ヘッダー、フッター付きでページごとに描画し、PDFに視覚的に保持します。結果は画像化され、文字を選択できません。', renderingDocument: '文書を端末内で描画しています…', renderingPage: '{total}ページ中{current}ページを描画しています…', assembling: '高再現ファイルを作成しています…', pdfToWordResult: '見た目を保持しました。ページは全面画像のため、Word内の文字は編集できません。', wordToPdfResult: 'ページの見た目を保持しました。PDF内の文字は選択できません。' },
  ko: { exactAppearance: '모양 그대로 보존', pdfToWordNote: '텍스트, 간격, 로고, 이미지를 포함한 각 PDF 페이지를 Word의 전체 페이지 이미지로 보존합니다. 모양은 유지되지만 페이지 내용은 편집할 수 없습니다.', wordToPdfNote: 'DOCX를 글꼴, 간격, 이미지, 표, 머리글, 바닥글과 함께 페이지별로 렌더링해 PDF에 시각적으로 보존합니다. 결과는 평면화되어 텍스트를 선택할 수 없습니다.', renderingDocument: '문서를 기기에서 렌더링하는 중…', renderingPage: '{total}페이지 중 {current}페이지 렌더링 중…', assembling: '고품질 파일을 만드는 중…', pdfToWordResult: '모양을 그대로 보존했습니다. 페이지가 전체 이미지이므로 Word 텍스트는 편집할 수 없습니다.', wordToPdfResult: '페이지 모양을 그대로 보존했습니다. PDF 텍스트는 선택할 수 없습니다.' },
  es: { exactAppearance: 'Apariencia exacta', pdfToWordNote: 'Cada página PDF se conserva como una imagen de página completa en Word, incluidos texto, espacios, logotipos e imágenes. La apariencia se mantiene; el contenido no es editable.', wordToPdfNote: 'El DOCX se representa página por página con fuentes, espacios, imágenes, tablas, encabezados y pies, y se conserva visualmente en PDF. El resultado queda aplanado y el texto no se puede seleccionar.', renderingDocument: 'Representando el documento localmente…', renderingPage: 'Representando página {current} de {total}…', assembling: 'Creando el archivo de alta fidelidad…', pdfToWordResult: 'Apariencia exacta conservada. Las páginas son imágenes completas y el texto no es editable en Word.', wordToPdfResult: 'Apariencia exacta conservada como páginas visuales. El texto del PDF no se puede seleccionar.' },
  fr: { exactAppearance: 'Apparence exacte', pdfToWordNote: 'Chaque page PDF est conservée comme visuel pleine page dans Word, avec texte, espacements, logos et images. L’apparence reste intacte, mais le contenu n’est pas modifiable.', wordToPdfNote: 'Le DOCX est rendu page par page avec ses polices, espacements, images, tableaux, en-têtes et pieds de page, puis conservé visuellement dans le PDF. Le résultat est aplati et le texte non sélectionnable.', renderingDocument: 'Rendu local du document…', renderingPage: 'Rendu de la page {current} sur {total}…', assembling: 'Création du fichier haute fidélité…', pdfToWordResult: 'Apparence exacte conservée. Les pages sont des visuels pleine page et le texte Word n’est pas modifiable.', wordToPdfResult: 'Apparence exacte conservée visuellement. Le texte du PDF n’est pas sélectionnable.' },
  de: { exactAppearance: 'Exaktes Erscheinungsbild', pdfToWordNote: 'Jede PDF-Seite wird in Word als ganzseitige Darstellung mit Text, Abständen, Logos und Bildern erhalten. Das Aussehen bleibt erhalten; der Seiteninhalt ist nicht bearbeitbar.', wordToPdfNote: 'Die DOCX-Datei wird mit Schriften, Abständen, Bildern, Tabellen, Kopf- und Fußzeilen seitenweise gerendert und visuell im PDF erhalten. Das Ergebnis ist reduziert; Text ist nicht auswählbar.', renderingDocument: 'Dokument wird lokal gerendert…', renderingPage: 'Seite {current} von {total} wird gerendert…', assembling: 'Datei mit hoher Wiedergabetreue wird erstellt…', pdfToWordResult: 'Exaktes Aussehen erhalten. Seiten sind ganzseitige Darstellungen; Word-Text ist nicht bearbeitbar.', wordToPdfResult: 'Exaktes Aussehen als Seitendarstellung erhalten. PDF-Text ist nicht auswählbar.' },
  pt: { exactAppearance: 'Aparência exata', pdfToWordNote: 'Cada página PDF é preservada no Word como visual de página inteira, incluindo texto, espaçamento, logótipos e imagens. A aparência mantém-se; o conteúdo não é editável.', wordToPdfNote: 'O DOCX é apresentado página a página com tipos de letra, espaçamento, imagens, tabelas, cabeçalhos e rodapés, sendo preservado visualmente no PDF. O resultado é achatado e o texto não pode ser selecionado.', renderingDocument: 'A processar o documento localmente…', renderingPage: 'A processar a página {current} de {total}…', assembling: 'A criar o ficheiro de alta fidelidade…', pdfToWordResult: 'Aparência exata preservada. As páginas são visuais completos e o texto não é editável no Word.', wordToPdfResult: 'Aparência exata preservada visualmente. O texto do PDF não pode ser selecionado.' },
  'zh-cn': { exactAppearance: '精确保留外观', pdfToWordNote: '每个 PDF 页面都会作为整页图像保存在 Word 中，包括文字、间距、徽标和图片。外观保持不变，但页面内容不可编辑。', wordToPdfNote: 'DOCX 会按页呈现字体、间距、图片、表格、页眉和页脚，然后以视觉形式保存在 PDF 中。结果会被扁平化，文字不可选择。', renderingDocument: '正在本地呈现文档…', renderingPage: '正在呈现第 {current}/{total} 页…', assembling: '正在生成高保真文件…', pdfToWordResult: '已精确保留外观。页面为整页图像，因此无法在 Word 中编辑文字。', wordToPdfResult: '已按页面视觉效果精确保留外观。PDF 中的文字不可选择。' },
  'zh-tw': { exactAppearance: '精確保留外觀', pdfToWordNote: '每個 PDF 頁面都會作為整頁影像保存在 Word 中，包括文字、間距、標誌和圖片。外觀維持不變，但頁面內容不可編輯。', wordToPdfNote: 'DOCX 會逐頁呈現字型、間距、圖片、表格、頁首與頁尾，再以視覺形式保存在 PDF 中。結果會被扁平化，文字不可選取。', renderingDocument: '正在本機呈現文件…', renderingPage: '正在呈現第 {current}/{total} 頁…', assembling: '正在建立高擬真檔案…', pdfToWordResult: '已精確保留外觀。頁面為整頁影像，因此無法在 Word 中編輯文字。', wordToPdfResult: '已按頁面視覺效果精確保留外觀。PDF 中的文字不可選取。' },
  hi: { exactAppearance: 'सटीक रूप', pdfToWordNote: 'हर PDF पेज को टेक्स्ट, स्पेसिंग, लोगो और चित्रों सहित Word में पूरे पेज के दृश्य के रूप में रखा जाता है। रूप सुरक्षित रहता है, लेकिन पेज की सामग्री संपादित नहीं की जा सकती।', wordToPdfNote: 'DOCX को फ़ॉन्ट, स्पेसिंग, चित्र, तालिका, हेडर और फ़ुटर सहित पेज-दर-पेज रेंडर कर PDF में दृश्य रूप में रखा जाता है। परिणाम फ़्लैट होता है और टेक्स्ट चुना नहीं जा सकता।', renderingDocument: 'दस्तावेज़ को डिवाइस पर रेंडर किया जा रहा है…', renderingPage: '{total} में से पेज {current} रेंडर हो रहा है…', assembling: 'उच्च गुणवत्ता वाली फ़ाइल बनाई जा रही है…', pdfToWordResult: 'सटीक रूप सुरक्षित है। पेज पूरे-पेज के दृश्य हैं, इसलिए Word टेक्स्ट संपादन योग्य नहीं है।', wordToPdfResult: 'पेज के दृश्य के रूप में सटीक रूप सुरक्षित है। PDF टेक्स्ट चुना नहीं जा सकता।' },
  ar: { exactAppearance: 'مظهر مطابق', pdfToWordNote: 'تُحفظ كل صفحة PDF كصورة صفحة كاملة في Word، بما في ذلك النص والمسافات والشعارات والصور. يبقى المظهر كما هو، لكن محتوى الصفحة غير قابل للتحرير.', wordToPdfNote: 'يُعرض ملف DOCX صفحة بصفحة مع الخطوط والمسافات والصور والجداول والرؤوس والتذييلات، ثم يُحفظ بصريًا في PDF. تكون النتيجة مسطحة والنص غير قابل للتحديد.', renderingDocument: 'جارٍ عرض المستند محليًا…', renderingPage: 'جارٍ عرض الصفحة {current} من {total}…', assembling: 'جارٍ إنشاء ملف عالي الدقة…', pdfToWordResult: 'تم الحفاظ على المظهر المطابق. الصفحات صور كاملة، لذلك لا يمكن تحرير النص في Word.', wordToPdfResult: 'تم الحفاظ على المظهر بصريًا. لا يمكن تحديد النص في PDF.' },
  ru: { exactAppearance: 'Точное отображение', pdfToWordNote: 'Каждая страница PDF сохраняется в Word как полноразмерное изображение со всем текстом, интервалами, логотипами и картинками. Вид сохраняется, но содержимое страницы нельзя редактировать.', wordToPdfNote: 'DOCX постранично отображается со шрифтами, интервалами, изображениями, таблицами, колонтитулами и визуально сохраняется в PDF. Результат сводится в изображение, текст нельзя выделить.', renderingDocument: 'Документ обрабатывается локально…', renderingPage: 'Обработка страницы {current} из {total}…', assembling: 'Создание файла высокой точности…', pdfToWordResult: 'Точный вид сохранён. Страницы являются полноразмерными изображениями, поэтому текст Word нельзя редактировать.', wordToPdfResult: 'Точный вид страниц сохранён. Текст в PDF нельзя выделить.' },
  id: { exactAppearance: 'Tampilan akurat', pdfToWordNote: 'Setiap halaman PDF dipertahankan sebagai visual satu halaman penuh di Word, termasuk teks, spasi, logo, dan gambar. Tampilan tetap utuh; isi halaman tidak dapat diedit.', wordToPdfNote: 'DOCX dirender per halaman dengan font, spasi, gambar, tabel, header, dan footer, lalu dipertahankan secara visual dalam PDF. Hasil diratakan dan teksnya tidak dapat dipilih.', renderingDocument: 'Merender dokumen secara lokal…', renderingPage: 'Merender halaman {current} dari {total}…', assembling: 'Menyusun file fidelitas tinggi…', pdfToWordResult: 'Tampilan akurat dipertahankan. Halaman berupa visual penuh sehingga teks Word tidak dapat diedit.', wordToPdfResult: 'Tampilan akurat dipertahankan sebagai visual halaman. Teks PDF tidak dapat dipilih.' },
  it: { exactAppearance: 'Aspetto esatto', pdfToWordNote: 'Ogni pagina PDF viene conservata in Word come visuale a pagina intera, inclusi testo, spaziatura, loghi e immagini. L’aspetto resta intatto, ma il contenuto non è modificabile.', wordToPdfNote: 'Il DOCX viene reso pagina per pagina con font, spaziatura, immagini, tabelle, intestazioni e piè di pagina, poi conservato visivamente nel PDF. Il risultato è appiattito e il testo non è selezionabile.', renderingDocument: 'Rendering locale del documento…', renderingPage: 'Rendering pagina {current} di {total}…', assembling: 'Creazione del file ad alta fedeltà…', pdfToWordResult: 'Aspetto esatto conservato. Le pagine sono visuali intere e il testo Word non è modificabile.', wordToPdfResult: 'Aspetto esatto conservato come visuale di pagina. Il testo PDF non è selezionabile.' },
  nl: { exactAppearance: 'Exacte weergave', pdfToWordNote: 'Elke PDF-pagina wordt in Word bewaard als paginavullende weergave, inclusief tekst, afstand, logo’s en afbeeldingen. Het uiterlijk blijft intact; de pagina-inhoud is niet bewerkbaar.', wordToPdfNote: 'De DOCX wordt pagina voor pagina weergegeven met lettertypen, afstand, afbeeldingen, tabellen, kop- en voetteksten en visueel in PDF bewaard. Het resultaat is afgevlakt en tekst is niet selecteerbaar.', renderingDocument: 'Document wordt lokaal weergegeven…', renderingPage: 'Pagina {current} van {total} wordt weergegeven…', assembling: 'Bestand met hoge getrouwheid wordt samengesteld…', pdfToWordResult: 'Exacte weergave behouden. Pagina’s zijn paginavullende beelden; Word-tekst is niet bewerkbaar.', wordToPdfResult: 'Exacte weergave als paginabeeld behouden. PDF-tekst is niet selecteerbaar.' },
  tr: { exactAppearance: 'Birebir görünüm', pdfToWordNote: 'Her PDF sayfası metin, boşluk, logo ve görseller dâhil olmak üzere Word’de tam sayfa görsel olarak korunur. Görünüm bozulmaz; sayfa içeriği düzenlenemez.', wordToPdfNote: 'DOCX; yazı tipleri, boşluklar, görseller, tablolar, üstbilgi ve altbilgilerle sayfa sayfa işlenir ve PDF’de görsel olarak korunur. Sonuç düzleştirilir ve metin seçilemez.', renderingDocument: 'Belge yerel olarak işleniyor…', renderingPage: '{total} sayfadan {current}. sayfa işleniyor…', assembling: 'Yüksek kaliteli dosya hazırlanıyor…', pdfToWordResult: 'Birebir görünüm korundu. Sayfalar tam sayfa görsellerdir; Word metni düzenlenemez.', wordToPdfResult: 'Birebir görünüm sayfa görselleri olarak korundu. PDF metni seçilemez.' },
  vi: { exactAppearance: 'Giữ nguyên hình thức', pdfToWordNote: 'Mỗi trang PDF được giữ dưới dạng hình ảnh toàn trang trong Word, gồm văn bản, khoảng cách, logo và hình ảnh. Hình thức được giữ nguyên nhưng nội dung trang không thể chỉnh sửa.', wordToPdfNote: 'DOCX được kết xuất từng trang với phông chữ, khoảng cách, hình ảnh, bảng, đầu trang và chân trang, rồi giữ nguyên về mặt hình ảnh trong PDF. Kết quả được làm phẳng và không thể chọn văn bản.', renderingDocument: 'Đang kết xuất tài liệu trên thiết bị…', renderingPage: 'Đang kết xuất trang {current}/{total}…', assembling: 'Đang tạo tệp có độ trung thực cao…', pdfToWordResult: 'Đã giữ nguyên hình thức. Trang là hình ảnh toàn trang nên không thể chỉnh sửa văn bản trong Word.', wordToPdfResult: 'Đã giữ nguyên hình thức theo từng trang. Không thể chọn văn bản trong PDF.' },
  th: { exactAppearance: 'คงหน้าตาเดิม', pdfToWordNote: 'แต่ละหน้า PDF จะถูกเก็บเป็นภาพเต็มหน้าใน Word รวมทั้งข้อความ ระยะห่าง โลโก้ และรูปภาพ หน้าตายังคงเดิม แต่แก้ไขเนื้อหาในหน้าไม่ได้', wordToPdfNote: 'DOCX จะถูกเรนเดอร์ทีละหน้าพร้อมแบบอักษร ระยะห่าง รูปภาพ ตาราง หัวกระดาษ และท้ายกระดาษ แล้วเก็บเป็นภาพใน PDF ผลลัพธ์จะแบนและเลือกข้อความไม่ได้', renderingDocument: 'กำลังเรนเดอร์เอกสารบนอุปกรณ์…', renderingPage: 'กำลังเรนเดอร์หน้า {current} จาก {total}…', assembling: 'กำลังสร้างไฟล์ความเที่ยงตรงสูง…', pdfToWordResult: 'คงหน้าตาเดิมแล้ว หน้าเป็นภาพเต็มหน้าจึงแก้ไขข้อความใน Word ไม่ได้', wordToPdfResult: 'คงหน้าตาเดิมเป็นภาพของแต่ละหน้าแล้ว ไม่สามารถเลือกข้อความใน PDF ได้' },
  pl: { exactAppearance: 'Dokładny wygląd', pdfToWordNote: 'Każda strona PDF jest zachowywana w Wordzie jako pełnostronicowy obraz, razem z tekstem, odstępami, logo i grafikami. Wygląd pozostaje bez zmian, ale treści strony nie można edytować.', wordToPdfNote: 'DOCX jest renderowany strona po stronie z czcionkami, odstępami, obrazami, tabelami, nagłówkami i stopkami, a następnie wizualnie zachowywany w PDF. Wynik jest spłaszczony i tekstu nie można zaznaczać.', renderingDocument: 'Lokalne renderowanie dokumentu…', renderingPage: 'Renderowanie strony {current} z {total}…', assembling: 'Tworzenie pliku o wysokiej zgodności…', pdfToWordResult: 'Dokładny wygląd zachowany. Strony są pełnostronicowymi obrazami, więc tekstu w Wordzie nie można edytować.', wordToPdfResult: 'Dokładny wygląd zachowany jako obrazy stron. Tekstu w PDF nie można zaznaczać.' },
};

const watermarkPdfMessages: Record<LocalePath, WatermarkPdfMessages> = {
  en: { watermarkType: 'Watermark type', text: 'Text', image: 'Image', uploadImage: 'Upload watermark image', imageHelp: 'PNG, JPG, or WebP · up to 10 MB and 20 megapixels', imageTreatment: 'Background treatment', useAsIs: 'Use image as-is', useAsIsHelp: 'Keep the uploaded image and its existing background.', removeBackground: 'Remove background', removeBackgroundHelp: 'Make the sampled edge color transparent before placing the watermark.', cleanupStrength: 'Background removal strength', before: 'Before', after: 'Watermark preview', beforeAlt: 'Uploaded watermark before background processing', afterAlt: 'Watermark image that will be placed in the PDF', missingImage: 'Upload a watermark image before processing.', tooLarge: 'Choose a watermark image smaller than 10 MB.', tooManyPixels: 'Choose a watermark image under 20 megapixels.', decodeFailed: 'This watermark image could not be decoded. Choose a valid PNG, JPG, or WebP file.' },
  ja: { watermarkType: '透かしの種類', text: 'テキスト', image: '画像', uploadImage: '透かし画像をアップロード', imageHelp: 'PNG、JPG、WebP · 10 MB・2000万画素まで', imageTreatment: '背景の処理', useAsIs: '画像をそのまま使用', useAsIsHelp: 'アップロードした画像と現在の背景を保持します。', removeBackground: '背景を削除', removeBackgroundHelp: '端の色を透明にしてから透かしを配置します。', cleanupStrength: '背景削除の強さ', before: '処理前', after: '透かしプレビュー', beforeAlt: '背景処理前のアップロード画像', afterAlt: 'PDFに配置される透かし画像', missingImage: '処理する前に透かし画像をアップロードしてください。', tooLarge: '10 MB未満の透かし画像を選択してください。', tooManyPixels: '2000万画素未満の透かし画像を選択してください。', decodeFailed: '画像を読み取れません。正しいPNG、JPG、WebPを選択してください。' },
  ko: { watermarkType: '워터마크 유형', text: '텍스트', image: '이미지', uploadImage: '워터마크 이미지 업로드', imageHelp: 'PNG, JPG 또는 WebP · 최대 10 MB 및 2천만 화소', imageTreatment: '배경 처리', useAsIs: '이미지 그대로 사용', useAsIsHelp: '업로드한 이미지와 기존 배경을 유지합니다.', removeBackground: '배경 제거', removeBackgroundHelp: '가장자리에서 추정한 색을 투명하게 만든 뒤 배치합니다.', cleanupStrength: '배경 제거 강도', before: '처리 전', after: '워터마크 미리보기', beforeAlt: '배경 처리 전 워터마크 이미지', afterAlt: 'PDF에 배치될 워터마크 이미지', missingImage: '처리하기 전에 워터마크 이미지를 업로드하세요.', tooLarge: '10 MB보다 작은 이미지를 선택하세요.', tooManyPixels: '2천만 화소 미만 이미지를 선택하세요.', decodeFailed: '이미지를 읽을 수 없습니다. 올바른 PNG, JPG 또는 WebP를 선택하세요.' },
  es: { watermarkType: 'Tipo de marca de agua', text: 'Texto', image: 'Imagen', uploadImage: 'Subir imagen de marca de agua', imageHelp: 'PNG, JPG o WebP · hasta 10 MB y 20 megapíxeles', imageTreatment: 'Tratamiento del fondo', useAsIs: 'Usar la imagen tal cual', useAsIsHelp: 'Conserva la imagen subida y su fondo actual.', removeBackground: 'Quitar el fondo', removeBackgroundHelp: 'Convierte en transparente el color detectado en los bordes.', cleanupStrength: 'Intensidad de eliminación', before: 'Antes', after: 'Vista previa', beforeAlt: 'Marca de agua antes de procesar el fondo', afterAlt: 'Marca de agua que se colocará en el PDF', missingImage: 'Sube una imagen de marca de agua antes de procesar.', tooLarge: 'Elige una imagen menor de 10 MB.', tooManyPixels: 'Elige una imagen de menos de 20 megapíxeles.', decodeFailed: 'No se pudo leer la imagen. Elige un PNG, JPG o WebP válido.' },
  fr: { watermarkType: 'Type de filigrane', text: 'Texte', image: 'Image', uploadImage: 'Importer une image de filigrane', imageHelp: 'PNG, JPG ou WebP · 10 Mo et 20 mégapixels maximum', imageTreatment: 'Traitement de l’arrière-plan', useAsIs: 'Utiliser l’image telle quelle', useAsIsHelp: 'Conserve l’image importée et son arrière-plan actuel.', removeBackground: 'Supprimer l’arrière-plan', removeBackgroundHelp: 'Rend transparente la couleur détectée sur les bords.', cleanupStrength: 'Intensité de suppression', before: 'Avant', after: 'Aperçu du filigrane', beforeAlt: 'Filigrane avant le traitement de l’arrière-plan', afterAlt: 'Filigrane qui sera placé dans le PDF', missingImage: 'Importez une image de filigrane avant de traiter le PDF.', tooLarge: 'Choisissez une image de moins de 10 Mo.', tooManyPixels: 'Choisissez une image de moins de 20 mégapixels.', decodeFailed: 'Impossible de lire cette image. Choisissez un PNG, JPG ou WebP valide.' },
  de: { watermarkType: 'Wasserzeichentyp', text: 'Text', image: 'Bild', uploadImage: 'Wasserzeichenbild hochladen', imageHelp: 'PNG, JPG oder WebP · bis 10 MB und 20 Megapixel', imageTreatment: 'Hintergrundbehandlung', useAsIs: 'Bild unverändert verwenden', useAsIsHelp: 'Behält das hochgeladene Bild und seinen vorhandenen Hintergrund.', removeBackground: 'Hintergrund entfernen', removeBackgroundHelp: 'Macht die an den Rändern erkannte Farbe transparent.', cleanupStrength: 'Stärke der Hintergrundentfernung', before: 'Vorher', after: 'Wasserzeichenvorschau', beforeAlt: 'Wasserzeichen vor der Hintergrundbearbeitung', afterAlt: 'Wasserzeichen, das im PDF platziert wird', missingImage: 'Lade vor der Verarbeitung ein Wasserzeichenbild hoch.', tooLarge: 'Wähle ein Bild unter 10 MB.', tooManyPixels: 'Wähle ein Bild unter 20 Megapixel.', decodeFailed: 'Das Bild konnte nicht gelesen werden. Wähle eine gültige PNG-, JPG- oder WebP-Datei.' },
  pt: { watermarkType: 'Tipo de marca de água', text: 'Texto', image: 'Imagem', uploadImage: 'Carregar imagem de marca de água', imageHelp: 'PNG, JPG ou WebP · até 10 MB e 20 megapíxeis', imageTreatment: 'Tratamento do fundo', useAsIs: 'Usar imagem como está', useAsIsHelp: 'Mantém a imagem carregada e o fundo existente.', removeBackground: 'Remover fundo', removeBackgroundHelp: 'Torna transparente a cor detetada nas margens.', cleanupStrength: 'Intensidade da remoção', before: 'Antes', after: 'Pré-visualização', beforeAlt: 'Marca de água antes do tratamento do fundo', afterAlt: 'Marca de água que será colocada no PDF', missingImage: 'Carregue uma imagem de marca de água antes de processar.', tooLarge: 'Escolha uma imagem inferior a 10 MB.', tooManyPixels: 'Escolha uma imagem com menos de 20 megapíxeis.', decodeFailed: 'Não foi possível ler a imagem. Escolha um PNG, JPG ou WebP válido.' },
  'zh-cn': { watermarkType: '水印类型', text: '文字', image: '图片', uploadImage: '上传水印图片', imageHelp: 'PNG、JPG 或 WebP · 不超过 10 MB 和 2000 万像素', imageTreatment: '背景处理', useAsIs: '原样使用图片', useAsIsHelp: '保留上传图片及其现有背景。', removeBackground: '移除背景', removeBackgroundHelp: '放置水印前，将边缘检测到的颜色变为透明。', cleanupStrength: '背景移除强度', before: '处理前', after: '水印预览', beforeAlt: '背景处理前的水印图片', afterAlt: '将放入 PDF 的水印图片', missingImage: '请先上传水印图片。', tooLarge: '请选择小于 10 MB 的图片。', tooManyPixels: '请选择低于 2000 万像素的图片。', decodeFailed: '无法读取图片。请选择有效的 PNG、JPG 或 WebP 文件。' },
  'zh-tw': { watermarkType: '浮水印類型', text: '文字', image: '圖片', uploadImage: '上傳浮水印圖片', imageHelp: 'PNG、JPG 或 WebP · 不超過 10 MB 與 2000 萬像素', imageTreatment: '背景處理', useAsIs: '原樣使用圖片', useAsIsHelp: '保留上傳圖片與目前背景。', removeBackground: '移除背景', removeBackgroundHelp: '放置浮水印前，將邊緣偵測到的顏色變透明。', cleanupStrength: '背景移除強度', before: '處理前', after: '浮水印預覽', beforeAlt: '背景處理前的浮水印圖片', afterAlt: '將放入 PDF 的浮水印圖片', missingImage: '請先上傳浮水印圖片。', tooLarge: '請選擇小於 10 MB 的圖片。', tooManyPixels: '請選擇低於 2000 萬像素的圖片。', decodeFailed: '無法讀取圖片。請選擇有效的 PNG、JPG 或 WebP 檔案。' },
  hi: { watermarkType: 'वॉटरमार्क प्रकार', text: 'टेक्स्ट', image: 'इमेज', uploadImage: 'वॉटरमार्क इमेज अपलोड करें', imageHelp: 'PNG, JPG या WebP · अधिकतम 10 MB और 20 मेगापिक्सेल', imageTreatment: 'बैकग्राउंड विकल्प', useAsIs: 'इमेज जैसी है वैसी रखें', useAsIsHelp: 'अपलोड की गई इमेज और उसका मौजूदा बैकग्राउंड रखें।', removeBackground: 'बैकग्राउंड हटाएँ', removeBackgroundHelp: 'किनारों से पहचाने रंग को पारदर्शी बनाकर वॉटरमार्क लगाएँ।', cleanupStrength: 'बैकग्राउंड हटाने की तीव्रता', before: 'पहले', after: 'वॉटरमार्क पूर्वावलोकन', beforeAlt: 'बैकग्राउंड प्रक्रिया से पहले वॉटरमार्क', afterAlt: 'PDF में लगाया जाने वाला वॉटरमार्क', missingImage: 'प्रोसेस करने से पहले वॉटरमार्क इमेज अपलोड करें।', tooLarge: '10 MB से छोटी इमेज चुनें।', tooManyPixels: '20 मेगापिक्सेल से छोटी इमेज चुनें।', decodeFailed: 'इमेज पढ़ी नहीं जा सकी। सही PNG, JPG या WebP चुनें।' },
  ar: { watermarkType: 'نوع العلامة المائية', text: 'نص', image: 'صورة', uploadImage: 'رفع صورة العلامة المائية', imageHelp: 'PNG أو JPG أو WebP · حتى 10 م.ب و20 ميغابكسل', imageTreatment: 'معالجة الخلفية', useAsIs: 'استخدام الصورة كما هي', useAsIsHelp: 'يحافظ على الصورة المرفوعة وخلفيتها الحالية.', removeBackground: 'إزالة الخلفية', removeBackgroundHelp: 'يجعل اللون المكتشف عند الحواف شفافًا قبل وضع العلامة.', cleanupStrength: 'قوة إزالة الخلفية', before: 'قبل', after: 'معاينة العلامة', beforeAlt: 'العلامة المائية قبل معالجة الخلفية', afterAlt: 'العلامة المائية التي ستوضع في PDF', missingImage: 'ارفع صورة علامة مائية قبل المعالجة.', tooLarge: 'اختر صورة أصغر من 10 م.ب.', tooManyPixels: 'اختر صورة أقل من 20 ميغابكسل.', decodeFailed: 'تعذر قراءة الصورة. اختر ملف PNG أو JPG أو WebP صالحًا.' },
  ru: { watermarkType: 'Тип водяного знака', text: 'Текст', image: 'Изображение', uploadImage: 'Загрузить изображение водяного знака', imageHelp: 'PNG, JPG или WebP · до 10 МБ и 20 мегапикселей', imageTreatment: 'Обработка фона', useAsIs: 'Использовать как есть', useAsIsHelp: 'Сохраняет загруженное изображение и его текущий фон.', removeBackground: 'Удалить фон', removeBackgroundHelp: 'Делает цвет, найденный по краям, прозрачным.', cleanupStrength: 'Сила удаления фона', before: 'До', after: 'Предпросмотр', beforeAlt: 'Водяной знак до обработки фона', afterAlt: 'Водяной знак, который будет помещён в PDF', missingImage: 'Загрузите изображение водяного знака перед обработкой.', tooLarge: 'Выберите изображение меньше 10 МБ.', tooManyPixels: 'Выберите изображение меньше 20 мегапикселей.', decodeFailed: 'Не удалось прочитать изображение. Выберите корректный PNG, JPG или WebP.' },
  id: { watermarkType: 'Jenis watermark', text: 'Teks', image: 'Gambar', uploadImage: 'Unggah gambar watermark', imageHelp: 'PNG, JPG, atau WebP · hingga 10 MB dan 20 megapiksel', imageTreatment: 'Perlakuan latar', useAsIs: 'Gunakan gambar apa adanya', useAsIsHelp: 'Mempertahankan gambar unggahan dan latarnya.', removeBackground: 'Hapus latar', removeBackgroundHelp: 'Membuat warna yang terdeteksi di tepi menjadi transparan.', cleanupStrength: 'Kekuatan penghapusan latar', before: 'Sebelum', after: 'Pratinjau watermark', beforeAlt: 'Watermark sebelum pemrosesan latar', afterAlt: 'Watermark yang akan ditempatkan di PDF', missingImage: 'Unggah gambar watermark sebelum memproses.', tooLarge: 'Pilih gambar di bawah 10 MB.', tooManyPixels: 'Pilih gambar di bawah 20 megapiksel.', decodeFailed: 'Gambar tidak dapat dibaca. Pilih PNG, JPG, atau WebP yang valid.' },
  it: { watermarkType: 'Tipo di filigrana', text: 'Testo', image: 'Immagine', uploadImage: 'Carica immagine filigrana', imageHelp: 'PNG, JPG o WebP · fino a 10 MB e 20 megapixel', imageTreatment: 'Trattamento dello sfondo', useAsIs: 'Usa l’immagine così com’è', useAsIsHelp: 'Mantiene l’immagine caricata e lo sfondo esistente.', removeBackground: 'Rimuovi lo sfondo', removeBackgroundHelp: 'Rende trasparente il colore rilevato sui bordi.', cleanupStrength: 'Intensità della rimozione', before: 'Prima', after: 'Anteprima filigrana', beforeAlt: 'Filigrana prima del trattamento dello sfondo', afterAlt: 'Filigrana che verrà inserita nel PDF', missingImage: 'Carica un’immagine filigrana prima di elaborare.', tooLarge: 'Scegli un’immagine sotto 10 MB.', tooManyPixels: 'Scegli un’immagine sotto 20 megapixel.', decodeFailed: 'Impossibile leggere l’immagine. Scegli un PNG, JPG o WebP valido.' },
  nl: { watermarkType: 'Type watermerk', text: 'Tekst', image: 'Afbeelding', uploadImage: 'Watermerkafbeelding uploaden', imageHelp: 'PNG, JPG of WebP · maximaal 10 MB en 20 megapixels', imageTreatment: 'Achtergrondverwerking', useAsIs: 'Afbeelding ongewijzigd gebruiken', useAsIsHelp: 'Behoudt de geüploade afbeelding en bestaande achtergrond.', removeBackground: 'Achtergrond verwijderen', removeBackgroundHelp: 'Maakt de aan de randen gevonden kleur transparant.', cleanupStrength: 'Sterkte achtergrondverwijdering', before: 'Voor', after: 'Watermerkvoorbeeld', beforeAlt: 'Watermerk vóór achtergrondverwerking', afterAlt: 'Watermerk dat in de PDF wordt geplaatst', missingImage: 'Upload eerst een watermerkafbeelding.', tooLarge: 'Kies een afbeelding kleiner dan 10 MB.', tooManyPixels: 'Kies een afbeelding onder 20 megapixels.', decodeFailed: 'De afbeelding kon niet worden gelezen. Kies een geldige PNG, JPG of WebP.' },
  tr: { watermarkType: 'Filigran türü', text: 'Metin', image: 'Görsel', uploadImage: 'Filigran görseli yükle', imageHelp: 'PNG, JPG veya WebP · en fazla 10 MB ve 20 megapiksel', imageTreatment: 'Arka plan işlemi', useAsIs: 'Görseli olduğu gibi kullan', useAsIsHelp: 'Yüklenen görseli ve mevcut arka planını korur.', removeBackground: 'Arka planı kaldır', removeBackgroundHelp: 'Kenarlarda algılanan rengi şeffaf yapar.', cleanupStrength: 'Arka plan kaldırma gücü', before: 'Önce', after: 'Filigran önizlemesi', beforeAlt: 'Arka plan işleminden önce filigran', afterAlt: 'PDF’ye yerleştirilecek filigran', missingImage: 'İşlemeden önce filigran görseli yükleyin.', tooLarge: '10 MB’tan küçük bir görsel seçin.', tooManyPixels: '20 megapikselden küçük bir görsel seçin.', decodeFailed: 'Görsel okunamadı. Geçerli bir PNG, JPG veya WebP seçin.' },
  vi: { watermarkType: 'Loại hình mờ', text: 'Văn bản', image: 'Hình ảnh', uploadImage: 'Tải ảnh hình mờ lên', imageHelp: 'PNG, JPG hoặc WebP · tối đa 10 MB và 20 megapixel', imageTreatment: 'Xử lý nền', useAsIs: 'Dùng nguyên ảnh', useAsIsHelp: 'Giữ nguyên ảnh tải lên và nền hiện có.', removeBackground: 'Xóa nền', removeBackgroundHelp: 'Làm trong suốt màu được phát hiện ở các cạnh.', cleanupStrength: 'Mức xóa nền', before: 'Trước', after: 'Xem trước hình mờ', beforeAlt: 'Hình mờ trước khi xử lý nền', afterAlt: 'Hình mờ sẽ được đặt vào PDF', missingImage: 'Hãy tải ảnh hình mờ lên trước khi xử lý.', tooLarge: 'Chọn ảnh nhỏ hơn 10 MB.', tooManyPixels: 'Chọn ảnh dưới 20 megapixel.', decodeFailed: 'Không thể đọc ảnh. Hãy chọn PNG, JPG hoặc WebP hợp lệ.' },
  th: { watermarkType: 'ประเภทลายน้ำ', text: 'ข้อความ', image: 'รูปภาพ', uploadImage: 'อัปโหลดรูปลายน้ำ', imageHelp: 'PNG, JPG หรือ WebP · สูงสุด 10 MB และ 20 เมกะพิกเซล', imageTreatment: 'การจัดการพื้นหลัง', useAsIs: 'ใช้รูปตามที่อัปโหลด', useAsIsHelp: 'คงรูปที่อัปโหลดและพื้นหลังเดิมไว้', removeBackground: 'ลบพื้นหลัง', removeBackgroundHelp: 'ทำให้สีที่ตรวจพบจากขอบโปร่งใสก่อนวางลายน้ำ', cleanupStrength: 'ระดับการลบพื้นหลัง', before: 'ก่อน', after: 'ตัวอย่างลายน้ำ', beforeAlt: 'ลายน้ำก่อนประมวลผลพื้นหลัง', afterAlt: 'ลายน้ำที่จะวางใน PDF', missingImage: 'อัปโหลดรูปลายน้ำก่อนประมวลผล', tooLarge: 'เลือกรูปที่เล็กกว่า 10 MB', tooManyPixels: 'เลือกรูปที่ต่ำกว่า 20 เมกะพิกเซล', decodeFailed: 'อ่านรูปไม่ได้ โปรดเลือก PNG, JPG หรือ WebP ที่ถูกต้อง' },
  pl: { watermarkType: 'Typ znaku wodnego', text: 'Tekst', image: 'Obraz', uploadImage: 'Prześlij obraz znaku wodnego', imageHelp: 'PNG, JPG lub WebP · do 10 MB i 20 megapikseli', imageTreatment: 'Obsługa tła', useAsIs: 'Użyj obrazu bez zmian', useAsIsHelp: 'Zachowuje przesłany obraz i jego obecne tło.', removeBackground: 'Usuń tło', removeBackgroundHelp: 'Ustawia wykryty na krawędziach kolor jako przezroczysty.', cleanupStrength: 'Siła usuwania tła', before: 'Przed', after: 'Podgląd znaku', beforeAlt: 'Znak wodny przed obróbką tła', afterAlt: 'Znak wodny, który zostanie umieszczony w PDF', missingImage: 'Prześlij obraz znaku wodnego przed przetwarzaniem.', tooLarge: 'Wybierz obraz mniejszy niż 10 MB.', tooManyPixels: 'Wybierz obraz poniżej 20 megapikseli.', decodeFailed: 'Nie udało się odczytać obrazu. Wybierz prawidłowy PNG, JPG lub WebP.' },
};

export function getWatermarkPdfMessages(locale: LocalePath): WatermarkPdfMessages {
  return watermarkPdfMessages[locale] ?? watermarkPdfMessages.en;
}

const officeFidelityMessages: Record<LocalePath, Pick<ConversionFidelityMessages, 'wordToPdfNote' | 'wordToPdfResult' | 'officeIsolation' | 'officeFailed'>> = {
  en: { wordToPdfNote: 'LibreOffice runs locally in your browser to preserve paragraphs, spacing, tables, pictures, charts, headers, footers, and selectable text. Unavailable or non-embedded fonts may be substituted.', wordToPdfResult: 'Exported locally with LibreOffice. Layout and editable text are retained where the source file and available fonts permit.', officeIsolation: 'This high-fidelity converter needs a secure browser session with cross-origin isolation. Reload the page; if it still fails, update your browser or disable an extension that rewrites page headers.', officeFailed: 'LibreOffice could not export this file locally. Check that it is a valid, unprotected Office document and try again.' },
  ja: { wordToPdfNote: 'LibreOffice をブラウザー内で実行し、段落、間隔、表、画像、グラフ、ヘッダー、フッター、選択可能な文字を保持します。利用できない、または埋め込まれていないフォントは置き換えられる場合があります。', wordToPdfResult: 'LibreOffice で端末内変換しました。元ファイルと利用可能なフォントが許す範囲でレイアウトと選択可能な文字を保持します。', officeIsolation: '高再現変換にはクロスオリジン分離された安全なブラウザー環境が必要です。再読み込みし、解決しない場合はブラウザーを更新するかヘッダーを書き換える拡張機能を無効にしてください。', officeFailed: 'LibreOffice でこのファイルを端末内変換できませんでした。有効で保護されていない Office 文書か確認してください。' },
  ko: { wordToPdfNote: '브라우저에서 LibreOffice를 로컬로 실행해 문단, 간격, 표, 그림, 차트, 머리글, 바닥글과 선택 가능한 텍스트를 유지합니다. 사용할 수 없거나 포함되지 않은 글꼴은 대체될 수 있습니다.', wordToPdfResult: 'LibreOffice로 기기에서 내보냈습니다. 원본 파일과 사용 가능한 글꼴이 허용하는 범위에서 레이아웃과 선택 가능한 텍스트를 유지합니다.', officeIsolation: '고품질 변환에는 교차 출처 격리가 적용된 안전한 브라우저 세션이 필요합니다. 페이지를 새로고침하고, 계속되면 브라우저를 업데이트하거나 헤더를 변경하는 확장 프로그램을 끄세요.', officeFailed: 'LibreOffice가 이 파일을 로컬로 내보내지 못했습니다. 유효하고 보호되지 않은 Office 문서인지 확인하세요.' },
  es: { wordToPdfNote: 'LibreOffice se ejecuta localmente en el navegador para conservar párrafos, espaciado, tablas, imágenes, gráficos, encabezados, pies y texto seleccionable. Las fuentes no disponibles o no incrustadas pueden sustituirse.', wordToPdfResult: 'Exportado localmente con LibreOffice. Se conservan el diseño y el texto seleccionable cuando el archivo y las fuentes disponibles lo permiten.', officeIsolation: 'Este conversor de alta fidelidad necesita una sesión segura con aislamiento entre orígenes. Recarga la página; si continúa, actualiza el navegador o desactiva extensiones que modifiquen encabezados.', officeFailed: 'LibreOffice no pudo exportar este archivo localmente. Comprueba que sea un documento de Office válido y sin protección.' },
  fr: { wordToPdfNote: 'LibreOffice s’exécute localement dans le navigateur pour conserver paragraphes, espacements, tableaux, images, graphiques, en-têtes, pieds de page et texte sélectionnable. Les polices absentes ou non incorporées peuvent être remplacées.', wordToPdfResult: 'Exporté localement avec LibreOffice. La mise en page et le texte sélectionnable sont conservés selon le fichier source et les polices disponibles.', officeIsolation: 'Ce convertisseur haute fidélité exige une session sécurisée avec isolation inter-origines. Rechargez la page ; si le problème persiste, mettez le navigateur à jour ou désactivez les extensions qui modifient les en-têtes.', officeFailed: 'LibreOffice n’a pas pu exporter ce fichier localement. Vérifiez qu’il s’agit d’un document Office valide et non protégé.' },
  de: { wordToPdfNote: 'LibreOffice läuft lokal im Browser und erhält Absätze, Abstände, Tabellen, Bilder, Diagramme, Kopf-/Fußzeilen und auswählbaren Text. Nicht verfügbare oder nicht eingebettete Schriften können ersetzt werden.', wordToPdfResult: 'Lokal mit LibreOffice exportiert. Layout und auswählbarer Text bleiben erhalten, soweit Quelldatei und verfügbare Schriften es zulassen.', officeIsolation: 'Dieser hochwertige Konverter benötigt eine sichere, ursprungsisolierte Browsersitzung. Seite neu laden; falls nötig Browser aktualisieren oder Erweiterungen deaktivieren, die Header verändern.', officeFailed: 'LibreOffice konnte diese Datei lokal nicht exportieren. Prüfe, ob sie ein gültiges, ungeschütztes Office-Dokument ist.' },
  pt: { wordToPdfNote: 'O LibreOffice corre localmente no navegador para preservar parágrafos, espaçamento, tabelas, imagens, gráficos, cabeçalhos, rodapés e texto selecionável. Tipos de letra indisponíveis ou não incorporados podem ser substituídos.', wordToPdfResult: 'Exportado localmente com o LibreOffice. O esquema e o texto selecionável são mantidos quando o ficheiro e os tipos de letra disponíveis permitem.', officeIsolation: 'Este conversor de alta fidelidade precisa de uma sessão segura com isolamento entre origens. Recarregue a página; se persistir, atualize o navegador ou desative extensões que alterem cabeçalhos.', officeFailed: 'O LibreOffice não conseguiu exportar este ficheiro localmente. Confirme que é um documento Office válido e sem proteção.' },
  'zh-cn': { wordToPdfNote: 'LibreOffice 在浏览器本地运行，尽量保留段落、间距、表格、图片、图表、页眉页脚及可选文字。不可用或未嵌入的字体可能被替换。', wordToPdfResult: '已由 LibreOffice 在本地导出。在源文件与可用字体允许的范围内保留版式和可选文字。', officeIsolation: '高保真转换需要启用跨源隔离的安全浏览器会话。请刷新页面；若仍失败，请更新浏览器或停用会改写页面标头的扩展。', officeFailed: 'LibreOffice 无法在本地导出此文件。请确认它是有效且未受保护的 Office 文档。' },
  'zh-tw': { wordToPdfNote: 'LibreOffice 在瀏覽器本機執行，盡量保留段落、間距、表格、圖片、圖表、頁首頁尾與可選取文字。無法使用或未嵌入的字型可能被替換。', wordToPdfResult: '已由 LibreOffice 在本機匯出。在來源檔案與可用字型允許的範圍內保留版面和可選取文字。', officeIsolation: '高保真轉換需要啟用跨來源隔離的安全瀏覽器工作階段。請重新載入；若仍失敗，請更新瀏覽器或停用會改寫頁面標頭的擴充功能。', officeFailed: 'LibreOffice 無法在本機匯出此檔案。請確認它是有效且未受保護的 Office 文件。' },
  hi: { wordToPdfNote: 'LibreOffice ब्राउज़र में लोकल चलता है और पैराग्राफ, स्पेसिंग, टेबल, चित्र, चार्ट, हेडर-फुटर तथा चुने जा सकने वाले टेक्स्ट को बनाए रखता है। अनुपलब्ध या एम्बेड न किए गए फ़ॉन्ट बदले जा सकते हैं।', wordToPdfResult: 'LibreOffice से लोकल एक्सपोर्ट हुआ। स्रोत फ़ाइल और उपलब्ध फ़ॉन्ट जहाँ अनुमति देते हैं वहाँ लेआउट व चयन योग्य टेक्स्ट सुरक्षित रहता है।', officeIsolation: 'इस उच्च-गुणवत्ता कन्वर्टर को cross-origin isolation वाला सुरक्षित ब्राउज़र सत्र चाहिए। पेज रीलोड करें; समस्या रहे तो ब्राउज़र अपडेट करें या हेडर बदलने वाला एक्सटेंशन बंद करें।', officeFailed: 'LibreOffice इस फ़ाइल को लोकल एक्सपोर्ट नहीं कर सका। जाँचें कि यह सही और असुरक्षित Office दस्तावेज़ है।' },
  ar: { wordToPdfNote: 'يعمل LibreOffice محليًا في المتصفح للحفاظ على الفقرات والتباعد والجداول والصور والمخططات والرؤوس والتذييلات والنص القابل للتحديد. قد تُستبدل الخطوط غير المتاحة أو غير المضمّنة.', wordToPdfResult: 'تم التصدير محليًا بواسطة LibreOffice مع الحفاظ على التخطيط والنص القابل للتحديد بقدر ما يسمح الملف والخطوط المتاحة.', officeIsolation: 'يتطلب هذا المحول عالي الدقة جلسة متصفح آمنة ومعزولة بين المصادر. أعد تحميل الصفحة، وإن استمرت المشكلة فحدّث المتصفح أو عطّل إضافة تغيّر ترويسات الصفحة.', officeFailed: 'تعذر على LibreOffice تصدير هذا الملف محليًا. تحقق من أنه مستند Office صالح وغير محمي.' },
  ru: { wordToPdfNote: 'LibreOffice работает локально в браузере и сохраняет абзацы, интервалы, таблицы, изображения, диаграммы, колонтитулы и выделяемый текст. Недоступные или невстроенные шрифты могут быть заменены.', wordToPdfResult: 'Локально экспортировано LibreOffice. Макет и выделяемый текст сохраняются настолько, насколько позволяют исходный файл и доступные шрифты.', officeIsolation: 'Для точного конвертера нужна безопасная сессия браузера с изоляцией источников. Перезагрузите страницу; если не поможет, обновите браузер или отключите расширение, меняющее заголовки.', officeFailed: 'LibreOffice не смог локально экспортировать файл. Убедитесь, что это корректный незащищённый документ Office.' },
  id: { wordToPdfNote: 'LibreOffice berjalan lokal di browser untuk mempertahankan paragraf, spasi, tabel, gambar, bagan, header, footer, dan teks yang dapat dipilih. Font yang tidak tersedia atau tidak tertanam dapat diganti.', wordToPdfResult: 'Diekspor secara lokal dengan LibreOffice. Tata letak dan teks yang dapat dipilih dipertahankan bila file sumber dan font tersedia mendukungnya.', officeIsolation: 'Konverter fidelitas tinggi ini memerlukan sesi browser aman dengan isolasi lintas origin. Muat ulang halaman; bila masih gagal, perbarui browser atau nonaktifkan ekstensi yang mengubah header.', officeFailed: 'LibreOffice tidak dapat mengekspor file ini secara lokal. Pastikan ini dokumen Office valid dan tidak dilindungi.' },
  it: { wordToPdfNote: 'LibreOffice viene eseguito localmente nel browser per conservare paragrafi, spaziatura, tabelle, immagini, grafici, intestazioni, piè di pagina e testo selezionabile. I font non disponibili o non incorporati possono essere sostituiti.', wordToPdfResult: 'Esportato localmente con LibreOffice. Layout e testo selezionabile sono mantenuti quando file sorgente e font disponibili lo consentono.', officeIsolation: 'Il convertitore ad alta fedeltà richiede una sessione sicura con isolamento cross-origin. Ricarica la pagina; se persiste, aggiorna il browser o disattiva estensioni che modificano le intestazioni.', officeFailed: 'LibreOffice non ha potuto esportare il file localmente. Verifica che sia un documento Office valido e non protetto.' },
  nl: { wordToPdfNote: 'LibreOffice draait lokaal in de browser en behoudt alinea’s, afstanden, tabellen, afbeeldingen, grafieken, kop-/voetteksten en selecteerbare tekst. Ontbrekende of niet-ingesloten lettertypen kunnen worden vervangen.', wordToPdfResult: 'Lokaal geëxporteerd met LibreOffice. Opmaak en selecteerbare tekst blijven behouden voor zover bronbestand en beschikbare lettertypen dat toelaten.', officeIsolation: 'Deze hoogwaardige converter vereist een veilige browsersessie met cross-origin-isolatie. Herlaad de pagina; werk anders de browser bij of schakel extensies uit die headers wijzigen.', officeFailed: 'LibreOffice kon dit bestand niet lokaal exporteren. Controleer of het een geldig, onbeveiligd Office-document is.' },
  tr: { wordToPdfNote: 'LibreOffice tarayıcıda yerel çalışarak paragrafları, boşlukları, tabloları, görselleri, grafikleri, üst-alt bilgileri ve seçilebilir metni korur. Kullanılamayan veya gömülmemiş yazı tipleri değiştirilebilir.', wordToPdfResult: 'LibreOffice ile yerel olarak dışa aktarıldı. Kaynak dosya ve mevcut yazı tipleri izin verdiği ölçüde düzen ve seçilebilir metin korunur.', officeIsolation: 'Bu yüksek doğruluklu dönüştürücü, kaynaklar arası yalıtımlı güvenli bir tarayıcı oturumu gerektirir. Sayfayı yenileyin; sürerse tarayıcıyı güncelleyin veya başlıkları değiştiren uzantıyı kapatın.', officeFailed: 'LibreOffice bu dosyayı yerel olarak dışa aktaramadı. Geçerli ve korumasız bir Office belgesi olduğunu doğrulayın.' },
  vi: { wordToPdfNote: 'LibreOffice chạy cục bộ trong trình duyệt để giữ đoạn văn, khoảng cách, bảng, ảnh, biểu đồ, đầu/chân trang và văn bản có thể chọn. Phông chữ không có sẵn hoặc không nhúng có thể bị thay thế.', wordToPdfResult: 'Đã xuất cục bộ bằng LibreOffice. Bố cục và văn bản có thể chọn được giữ khi tệp nguồn và phông chữ hiện có cho phép.', officeIsolation: 'Bộ chuyển đổi độ trung thực cao cần phiên trình duyệt an toàn có cô lập nguồn chéo. Hãy tải lại; nếu vẫn lỗi, cập nhật trình duyệt hoặc tắt tiện ích sửa tiêu đề trang.', officeFailed: 'LibreOffice không thể xuất tệp này cục bộ. Hãy kiểm tra đây là tài liệu Office hợp lệ và không được bảo vệ.' },
  th: { wordToPdfNote: 'LibreOffice ทำงานในเบราว์เซอร์บนเครื่องเพื่อรักษาย่อหน้า ระยะห่าง ตาราง รูปภาพ แผนภูมิ หัว/ท้ายกระดาษ และข้อความที่เลือกได้ ฟอนต์ที่ไม่มีหรือไม่ได้ฝังอาจถูกแทนที่', wordToPdfResult: 'ส่งออกบนเครื่องด้วย LibreOffice โดยรักษาเลย์เอาต์และข้อความที่เลือกได้เท่าที่ไฟล์ต้นฉบับและฟอนต์ที่มีรองรับ', officeIsolation: 'ตัวแปลงความเที่ยงตรงสูงต้องใช้เซสชันเบราว์เซอร์ที่ปลอดภัยและแยกต้นทาง โปรดโหลดใหม่ หากยังไม่สำเร็จให้อัปเดตเบราว์เซอร์หรือปิดส่วนขยายที่แก้ไขส่วนหัว', officeFailed: 'LibreOffice ส่งออกไฟล์นี้บนเครื่องไม่ได้ ตรวจสอบว่าเป็นเอกสาร Office ที่ถูกต้องและไม่ได้ป้องกัน' },
  pl: { wordToPdfNote: 'LibreOffice działa lokalnie w przeglądarce i zachowuje akapity, odstępy, tabele, obrazy, wykresy, nagłówki, stopki oraz zaznaczalny tekst. Niedostępne lub nieosadzone czcionki mogą zostać zastąpione.', wordToPdfResult: 'Wyeksportowano lokalnie przez LibreOffice. Układ i zaznaczalny tekst są zachowane w zakresie dostępnym dla pliku źródłowego i czcionek.', officeIsolation: 'Konwerter wysokiej jakości wymaga bezpiecznej sesji z izolacją między źródłami. Odśwież stronę; jeśli problem trwa, zaktualizuj przeglądarkę lub wyłącz rozszerzenie zmieniające nagłówki.', officeFailed: 'LibreOffice nie mógł lokalnie wyeksportować pliku. Sprawdź, czy to prawidłowy, niechroniony dokument Office.' },
};

export function getConversionFidelityMessages(locale: LocalePath): ConversionFidelityMessages {
  return { ...(conversionFidelityMessages[locale] ?? conversionFidelityMessages.en), ...(officeFidelityMessages[locale] ?? officeFidelityMessages.en) };
}
