import type { LocalePath } from './config';

// Star-rating copy. Placeholders: {tool}, {average}, {count}, {n}.
export interface RatingCopy {
  siteTitle: string; siteQuestion: string; toolTitle: string; toolAction: string;
  none: string; one: string; many: string; thanks: string; yours: string; error: string;
  star: string; stars: string; legendSite: string; legendTool: string; keyboard: string;
}

const copy: Record<LocalePath, RatingCopy> = {
  en: { siteTitle: 'Rate SoraFiles', siteQuestion: 'How’s your experience?', toolTitle: 'Enjoying {tool}?', toolAction: 'Rate this tool', none: 'No ratings yet', one: '{average} out of 5 · {count} rating', many: '{average} out of 5 · {count} ratings', thanks: 'Thanks for rating!', yours: 'Your rating: {n} of 5. Choose another star to change it.', error: 'Your rating couldn’t be saved. Please try again.', star: '{n} star', stars: '{n} stars', legendSite: 'Your rating for SoraFiles', legendTool: 'Your rating for {tool}', keyboard: 'Use the arrow keys to choose, then press Enter.' },
  ja: { siteTitle: 'SoraFilesを評価', siteQuestion: '使い心地はいかがですか？', toolTitle: '{tool}はお役に立ちましたか？', toolAction: 'このツールを評価', none: 'まだ評価はありません', one: '5点中{average} · {count}件の評価', many: '5点中{average} · {count}件の評価', thanks: '評価ありがとうございます！', yours: 'あなたの評価：5点中{n}。別の星を選ぶと変更できます。', error: '評価を保存できませんでした。もう一度お試しください。', star: '星{n}つ', stars: '星{n}つ', legendSite: 'SoraFilesへの評価', legendTool: '{tool}への評価', keyboard: '矢印キーで選んで、Enterキーを押してください。' },
  ko: { siteTitle: 'SoraFiles 평가하기', siteQuestion: '사용해 보니 어떠셨나요?', toolTitle: '{tool}이(가) 마음에 드셨나요?', toolAction: '이 도구 평가하기', none: '아직 평가가 없습니다', one: '5점 중 {average}점 · 평가 {count}개', many: '5점 중 {average}점 · 평가 {count}개', thanks: '평가해 주셔서 감사합니다!', yours: '내 평가: 5점 중 {n}점. 다른 별을 선택해 변경할 수 있습니다.', error: '평가를 저장하지 못했습니다. 다시 시도해 주세요.', star: '별 {n}개', stars: '별 {n}개', legendSite: 'SoraFiles에 대한 내 평가', legendTool: '{tool}에 대한 내 평가', keyboard: '화살표 키로 선택한 다음 Enter 키를 누르세요.' },
  es: { siteTitle: 'Valora SoraFiles', siteQuestion: '¿Qué tal tu experiencia?', toolTitle: '¿Te gusta {tool}?', toolAction: 'Valora esta herramienta', none: 'Aún no hay valoraciones', one: '{average} de 5 · {count} valoración', many: '{average} de 5 · {count} valoraciones', thanks: '¡Gracias por tu valoración!', yours: 'Tu valoración: {n} de 5. Elige otra estrella para cambiarla.', error: 'No se pudo guardar tu valoración. Inténtalo de nuevo.', star: '{n} estrella', stars: '{n} estrellas', legendSite: 'Tu valoración de SoraFiles', legendTool: 'Tu valoración de {tool}', keyboard: 'Usa las flechas para elegir y pulsa Intro.' },
  fr: { siteTitle: 'Notez SoraFiles', siteQuestion: 'Que pensez-vous de SoraFiles ?', toolTitle: '{tool} vous plaît ?', toolAction: 'Notez cet outil', none: 'Pas encore de note', one: '{average} sur 5 · {count} note', many: '{average} sur 5 · {count} notes', thanks: 'Merci pour votre note !', yours: 'Votre note : {n} sur 5. Choisissez une autre étoile pour la modifier.', error: 'Votre note n’a pas pu être enregistrée. Réessayez.', star: '{n} étoile', stars: '{n} étoiles', legendSite: 'Votre note pour SoraFiles', legendTool: 'Votre note pour {tool}', keyboard: 'Utilisez les flèches pour choisir, puis appuyez sur Entrée.' },
  de: { siteTitle: 'SoraFiles bewerten', siteQuestion: 'Wie gefällt dir SoraFiles?', toolTitle: 'Gefällt dir {tool}?', toolAction: 'Dieses Tool bewerten', none: 'Noch keine Bewertungen', one: '{average} von 5 · {count} Bewertung', many: '{average} von 5 · {count} Bewertungen', thanks: 'Danke für deine Bewertung!', yours: 'Deine Bewertung: {n} von 5. Wähle einen anderen Stern, um sie zu ändern.', error: 'Deine Bewertung konnte nicht gespeichert werden. Bitte versuche es erneut.', star: '{n} Stern', stars: '{n} Sterne', legendSite: 'Deine Bewertung für SoraFiles', legendTool: 'Deine Bewertung für {tool}', keyboard: 'Wähle mit den Pfeiltasten und drücke dann die Eingabetaste.' },
  pt: { siteTitle: 'Avalie o SoraFiles', siteQuestion: 'Como está a ser a sua experiência?', toolTitle: 'Está a gostar de {tool}?', toolAction: 'Avalie esta ferramenta', none: 'Ainda sem avaliações', one: '{average} de 5 · {count} avaliação', many: '{average} de 5 · {count} avaliações', thanks: 'Obrigado pela sua avaliação!', yours: 'A sua avaliação: {n} de 5. Escolha outra estrela para a alterar.', error: 'Não foi possível guardar a sua avaliação. Tente novamente.', star: '{n} estrela', stars: '{n} estrelas', legendSite: 'A sua avaliação do SoraFiles', legendTool: 'A sua avaliação de {tool}', keyboard: 'Use as setas para escolher e prima Enter.' },
  'zh-cn': { siteTitle: '为 SoraFiles 评分', siteQuestion: '您的使用体验如何？', toolTitle: '喜欢{tool}吗？', toolAction: '为此工具评分', none: '暂无评分', one: '{average} / 5 · {count} 个评分', many: '{average} / 5 · {count} 个评分', thanks: '感谢您的评分！', yours: '您的评分：{n} / 5。选择其他星级即可更改。', error: '无法保存您的评分，请重试。', star: '{n} 星', stars: '{n} 星', legendSite: '您对 SoraFiles 的评分', legendTool: '您对{tool}的评分', keyboard: '使用方向键选择，然后按 Enter 键。' },
  'zh-tw': { siteTitle: '為 SoraFiles 評分', siteQuestion: '您的使用體驗如何？', toolTitle: '喜歡{tool}嗎？', toolAction: '為此工具評分', none: '尚無評分', one: '{average} / 5 · {count} 則評分', many: '{average} / 5 · {count} 則評分', thanks: '感謝您的評分！', yours: '您的評分：{n} / 5。選擇其他星等即可變更。', error: '無法儲存您的評分，請再試一次。', star: '{n} 星', stars: '{n} 星', legendSite: '您對 SoraFiles 的評分', legendTool: '您對{tool}的評分', keyboard: '使用方向鍵選擇，然後按 Enter 鍵。' },
  hi: { siteTitle: 'SoraFiles को रेट करें', siteQuestion: 'आपका अनुभव कैसा रहा?', toolTitle: 'क्या {tool} पसंद आया?', toolAction: 'इस टूल को रेट करें', none: 'अभी कोई रेटिंग नहीं', one: '5 में से {average} · {count} रेटिंग', many: '5 में से {average} · {count} रेटिंग', thanks: 'रेटिंग के लिए धन्यवाद!', yours: 'आपकी रेटिंग: 5 में से {n}। बदलने के लिए दूसरा स्टार चुनें।', error: 'आपकी रेटिंग सहेजी नहीं जा सकी। कृपया फिर से कोशिश करें।', star: '{n} स्टार', stars: '{n} स्टार', legendSite: 'SoraFiles के लिए आपकी रेटिंग', legendTool: '{tool} के लिए आपकी रेटिंग', keyboard: 'चुनने के लिए तीर कुंजियों का उपयोग करें, फिर Enter दबाएँ।' },
  ar: { siteTitle: 'قيّم SoraFiles', siteQuestion: 'كيف كانت تجربتك؟', toolTitle: 'هل أعجبتك أداة {tool}؟', toolAction: 'قيّم هذه الأداة', none: 'لا توجد تقييمات بعد', one: '{average} من 5 · تقييم واحد', many: '{average} من 5 · {count} تقييمات', thanks: 'شكرًا على تقييمك!', yours: 'تقييمك: {n} من 5. اختر نجمة أخرى لتغييره.', error: 'تعذّر حفظ تقييمك. حاول مرة أخرى.', star: 'نجمة واحدة', stars: '{n} نجوم', legendSite: 'تقييمك لـ SoraFiles', legendTool: 'تقييمك لأداة {tool}', keyboard: 'استخدم مفاتيح الأسهم للاختيار ثم اضغط Enter.' },
  ru: { siteTitle: 'Оцените SoraFiles', siteQuestion: 'Как вам SoraFiles?', toolTitle: 'Понравился инструмент «{tool}»?', toolAction: 'Оцените этот инструмент', none: 'Пока нет оценок', one: '{average} из 5 · оценок: {count}', many: '{average} из 5 · оценок: {count}', thanks: 'Спасибо за оценку!', yours: 'Ваша оценка: {n} из 5. Выберите другую звезду, чтобы изменить её.', error: 'Не удалось сохранить оценку. Попробуйте ещё раз.', star: 'Звёзд: {n}', stars: 'Звёзд: {n}', legendSite: 'Ваша оценка SoraFiles', legendTool: 'Ваша оценка: {tool}', keyboard: 'Выберите клавишами со стрелками и нажмите Enter.' },
  id: { siteTitle: 'Beri nilai SoraFiles', siteQuestion: 'Bagaimana pengalaman Anda?', toolTitle: 'Suka dengan {tool}?', toolAction: 'Beri nilai alat ini', none: 'Belum ada penilaian', one: '{average} dari 5 · {count} penilaian', many: '{average} dari 5 · {count} penilaian', thanks: 'Terima kasih atas penilaian Anda!', yours: 'Nilai Anda: {n} dari 5. Pilih bintang lain untuk mengubahnya.', error: 'Penilaian Anda tidak dapat disimpan. Coba lagi.', star: '{n} bintang', stars: '{n} bintang', legendSite: 'Nilai Anda untuk SoraFiles', legendTool: 'Nilai Anda untuk {tool}', keyboard: 'Gunakan tombol panah untuk memilih, lalu tekan Enter.' },
  it: { siteTitle: 'Valuta SoraFiles', siteQuestion: 'Com’è la tua esperienza?', toolTitle: 'Ti piace {tool}?', toolAction: 'Valuta questo strumento', none: 'Ancora nessuna valutazione', one: '{average} su 5 · {count} valutazione', many: '{average} su 5 · {count} valutazioni', thanks: 'Grazie per la valutazione!', yours: 'La tua valutazione: {n} su 5. Scegli un’altra stella per cambiarla.', error: 'Impossibile salvare la valutazione. Riprova.', star: '{n} stella', stars: '{n} stelle', legendSite: 'La tua valutazione di SoraFiles', legendTool: 'La tua valutazione di {tool}', keyboard: 'Usa i tasti freccia per scegliere, poi premi Invio.' },
  nl: { siteTitle: 'Beoordeel SoraFiles', siteQuestion: 'Hoe bevalt SoraFiles?', toolTitle: 'Bevalt {tool}?', toolAction: 'Beoordeel deze tool', none: 'Nog geen beoordelingen', one: '{average} van 5 · {count} beoordeling', many: '{average} van 5 · {count} beoordelingen', thanks: 'Bedankt voor je beoordeling!', yours: 'Jouw beoordeling: {n} van 5. Kies een andere ster om die te wijzigen.', error: 'Je beoordeling kon niet worden opgeslagen. Probeer het opnieuw.', star: '{n} ster', stars: '{n} sterren', legendSite: 'Jouw beoordeling van SoraFiles', legendTool: 'Jouw beoordeling van {tool}', keyboard: 'Kies met de pijltjestoetsen en druk op Enter.' },
  tr: { siteTitle: 'SoraFiles’ı puanlayın', siteQuestion: 'Deneyiminiz nasıl?', toolTitle: '{tool} işinize yaradı mı?', toolAction: 'Bu aracı puanlayın', none: 'Henüz puan yok', one: '5 üzerinden {average} · {count} puan', many: '5 üzerinden {average} · {count} puan', thanks: 'Puanınız için teşekkürler!', yours: 'Puanınız: 5 üzerinden {n}. Değiştirmek için başka bir yıldız seçin.', error: 'Puanınız kaydedilemedi. Lütfen tekrar deneyin.', star: '{n} yıldız', stars: '{n} yıldız', legendSite: 'SoraFiles için puanınız', legendTool: '{tool} için puanınız', keyboard: 'Seçmek için ok tuşlarını kullanın, ardından Enter’a basın.' },
  vi: { siteTitle: 'Đánh giá SoraFiles', siteQuestion: 'Trải nghiệm của bạn thế nào?', toolTitle: 'Bạn thấy {tool} thế nào?', toolAction: 'Đánh giá công cụ này', none: 'Chưa có đánh giá', one: '{average}/5 · {count} lượt đánh giá', many: '{average}/5 · {count} lượt đánh giá', thanks: 'Cảm ơn bạn đã đánh giá!', yours: 'Đánh giá của bạn: {n}/5. Chọn sao khác để thay đổi.', error: 'Không thể lưu đánh giá của bạn. Vui lòng thử lại.', star: '{n} sao', stars: '{n} sao', legendSite: 'Đánh giá của bạn cho SoraFiles', legendTool: 'Đánh giá của bạn cho {tool}', keyboard: 'Dùng các phím mũi tên để chọn, sau đó nhấn Enter.' },
  th: { siteTitle: 'ให้คะแนน SoraFiles', siteQuestion: 'ประสบการณ์ของคุณเป็นอย่างไร', toolTitle: 'ชอบ {tool} ไหม', toolAction: 'ให้คะแนนเครื่องมือนี้', none: 'ยังไม่มีคะแนน', one: '{average} จาก 5 · {count} คะแนน', many: '{average} จาก 5 · {count} คะแนน', thanks: 'ขอบคุณที่ให้คะแนน', yours: 'คะแนนของคุณ: {n} จาก 5 เลือกดาวอื่นเพื่อเปลี่ยน', error: 'บันทึกคะแนนไม่สำเร็จ โปรดลองอีกครั้ง', star: '{n} ดาว', stars: '{n} ดาว', legendSite: 'คะแนนของคุณสำหรับ SoraFiles', legendTool: 'คะแนนของคุณสำหรับ {tool}', keyboard: 'ใช้ปุ่มลูกศรเพื่อเลือก แล้วกด Enter' },
  pl: { siteTitle: 'Oceń SoraFiles', siteQuestion: 'Jak Ci się podoba SoraFiles?', toolTitle: 'Podoba Ci się {tool}?', toolAction: 'Oceń to narzędzie', none: 'Brak ocen', one: '{average} na 5 · {count} ocena', many: '{average} na 5 · ocen: {count}', thanks: 'Dziękujemy za ocenę!', yours: 'Twoja ocena: {n} na 5. Wybierz inną gwiazdkę, aby ją zmienić.', error: 'Nie udało się zapisać oceny. Spróbuj ponownie.', star: '{n} gwiazdka', stars: 'Gwiazdki: {n}', legendSite: 'Twoja ocena SoraFiles', legendTool: 'Twoja ocena: {tool}', keyboard: 'Wybierz strzałkami, a potem naciśnij Enter.' },
};

export const ratingCopy = (locale: LocalePath): RatingCopy => copy[locale] ?? copy.en;
