import type { LocalePath } from './config';

export interface SpreadsheetToolMessages {
  resultMode: string;
  exactAppearance: string;
  exactHelp: string;
  editableCells: string;
  editableHelp: string;
  exactResult: string;
  editableResult: string;
  excelResult: string;
}

const messages: Record<LocalePath, SpreadsheetToolMessages> = {
  en: { resultMode: 'Workbook result', exactAppearance: 'Exact appearance', exactHelp: 'Preserve each complete PDF page on its own worksheet. Pictures, charts, tables, fonts, and every language stay visually intact; the page is not editable cells.', editableCells: 'Editable text & tables', editableHelp: 'Place selectable PDF text into cells. Useful for simple tables, but PDF has no original formulas, chart data, merged cells, or spreadsheet structure to recover.', exactResult: 'Every PDF page is preserved losslessly on its own worksheet. The page visuals are exact; their contents are not editable cells.', editableResult: 'Selectable PDF text was placed into editable cells. Complex tables, formulas, charts, and exact spacing may require cleanup.', excelResult: 'Exported locally by LibreOffice. Formatting, charts, pictures, tables, formulas, and print layout are retained where the source file and available fonts permit.' },
  ja: { resultMode: 'ブックの結果', exactAppearance: '見た目を正確に保持', exactHelp: '各PDFページ全体を個別のシートに保持します。画像、グラフ、表、フォント、全言語の見た目は保たれますが、セルとしては編集できません。', editableCells: '編集可能な文字と表', editableHelp: '選択可能なPDF文字をセルに配置します。単純な表向けです。PDFには元の数式、グラフデータ、結合セル、表計算構造がないため復元できません。', exactResult: '各PDFページを個別シートに劣化なく保持しました。見た目は正確ですが、内容は編集可能なセルではありません。', editableResult: '選択可能なPDF文字を編集可能なセルに配置しました。複雑な表、数式、グラフ、正確な間隔は調整が必要です。', excelResult: 'LibreOfficeで端末内変換しました。元ファイルと利用可能なフォントが許す範囲で書式、グラフ、画像、表、数式、印刷設定を保持します。' },
  ko: { resultMode: '통합 문서 결과', exactAppearance: '모양 그대로 보존', exactHelp: '각 PDF 페이지 전체를 별도 시트에 보존합니다. 그림, 차트, 표, 글꼴, 모든 언어의 모양은 유지되지만 셀로 편집할 수 없습니다.', editableCells: '편집 가능한 텍스트와 표', editableHelp: '선택 가능한 PDF 텍스트를 셀에 넣습니다. 단순 표에 적합하지만 PDF에는 원래 수식, 차트 데이터, 병합 셀, 스프레드시트 구조가 없어 복원할 수 없습니다.', exactResult: '각 PDF 페이지를 별도 시트에 손실 없이 보존했습니다. 모양은 정확하지만 내용은 편집 가능한 셀이 아닙니다.', editableResult: '선택 가능한 PDF 텍스트를 편집 가능한 셀에 넣었습니다. 복잡한 표, 수식, 차트와 정확한 간격은 정리가 필요할 수 있습니다.', excelResult: 'LibreOffice로 기기에서 내보냈습니다. 원본과 사용 가능한 글꼴이 허용하는 범위에서 서식, 차트, 그림, 표, 수식과 인쇄 레이아웃을 유지합니다.' },
  es: { resultMode: 'Resultado del libro', exactAppearance: 'Apariencia exacta', exactHelp: 'Conserva cada página PDF completa en su propia hoja. Imágenes, gráficos, tablas, fuentes e idiomas permanecen visualmente intactos; la página no son celdas editables.', editableCells: 'Texto y tablas editables', editableHelp: 'Coloca el texto seleccionable del PDF en celdas. Sirve para tablas simples; un PDF no contiene las fórmulas, datos de gráficos, celdas combinadas ni estructura original.', exactResult: 'Cada página PDF se conserva sin pérdida en su propia hoja. La imagen es exacta; el contenido no son celdas editables.', editableResult: 'El texto seleccionable se colocó en celdas editables. Tablas complejas, fórmulas, gráficos y espaciado pueden requerir ajustes.', excelResult: 'Exportado localmente con LibreOffice. Conserva formato, gráficos, imágenes, tablas, fórmulas y diseño de impresión cuando el archivo y las fuentes lo permiten.' },
  fr: { resultMode: 'Résultat du classeur', exactAppearance: 'Apparence exacte', exactHelp: 'Conserve chaque page PDF complète sur une feuille distincte. Images, graphiques, tableaux, polices et langues restent visuellement intacts ; la page n’est pas composée de cellules modifiables.', editableCells: 'Texte et tableaux modifiables', editableHelp: 'Place le texte sélectionnable du PDF dans des cellules. Adapté aux tableaux simples ; un PDF ne contient pas les formules, données de graphiques, cellules fusionnées ni structure d’origine.', exactResult: 'Chaque page PDF est conservée sans perte sur sa propre feuille. Le visuel est exact ; le contenu n’est pas constitué de cellules modifiables.', editableResult: 'Le texte sélectionnable a été placé dans des cellules. Les tableaux complexes, formules, graphiques et espacements peuvent demander des corrections.', excelResult: 'Exporté localement avec LibreOffice. Mise en forme, graphiques, images, tableaux, formules et impression sont conservés selon le fichier et les polices disponibles.' },
  de: { resultMode: 'Arbeitsmappenergebnis', exactAppearance: 'Exaktes Erscheinungsbild', exactHelp: 'Erhält jede vollständige PDF-Seite auf einem eigenen Blatt. Bilder, Diagramme, Tabellen, Schriften und Sprachen bleiben optisch intakt; die Seite besteht nicht aus bearbeitbaren Zellen.', editableCells: 'Bearbeitbarer Text und Tabellen', editableHelp: 'Setzt auswählbaren PDF-Text in Zellen. Für einfache Tabellen; PDFs enthalten keine ursprünglichen Formeln, Diagrammdaten, verbundenen Zellen oder Tabellenstruktur.', exactResult: 'Jede PDF-Seite wurde verlustfrei auf einem eigenen Blatt erhalten. Die Optik ist exakt; der Inhalt sind keine bearbeitbaren Zellen.', editableResult: 'Auswählbarer PDF-Text wurde in bearbeitbare Zellen gesetzt. Komplexe Tabellen, Formeln, Diagramme und Abstände können Nacharbeit brauchen.', excelResult: 'Lokal mit LibreOffice exportiert. Formatierung, Diagramme, Bilder, Tabellen, Formeln und Drucklayout bleiben erhalten, soweit Datei und Schriften es zulassen.' },
  pt: { resultMode: 'Resultado do livro', exactAppearance: 'Aparência exata', exactHelp: 'Preserva cada página PDF completa numa folha própria. Imagens, gráficos, tabelas, tipos de letra e idiomas ficam visualmente intactos; a página não é composta por células editáveis.', editableCells: 'Texto e tabelas editáveis', editableHelp: 'Coloca o texto selecionável do PDF em células. Útil para tabelas simples; o PDF não contém fórmulas, dados de gráficos, células unidas nem estrutura original.', exactResult: 'Cada página PDF foi preservada sem perdas numa folha própria. O visual é exato; o conteúdo não são células editáveis.', editableResult: 'O texto selecionável foi colocado em células editáveis. Tabelas complexas, fórmulas, gráficos e espaçamento podem precisar de ajustes.', excelResult: 'Exportado localmente com o LibreOffice. Formatação, gráficos, imagens, tabelas, fórmulas e impressão são mantidos quando o ficheiro e os tipos de letra permitem.' },
  'zh-cn': { resultMode: '工作簿结果', exactAppearance: '精确保留外观', exactHelp: '将每个完整PDF页面保存在独立工作表中。图片、图表、表格、字体和所有语言的外观保持不变，但页面内容不是可编辑单元格。', editableCells: '可编辑文字和表格', editableHelp: '把可选择的PDF文字放入单元格，适合简单表格。PDF不含原始公式、图表数据、合并单元格或电子表格结构，无法还原。', exactResult: '每个PDF页面均无损保存在独立工作表中。外观准确，但内容不是可编辑单元格。', editableResult: '已将可选择的PDF文字放入可编辑单元格。复杂表格、公式、图表和精确间距可能需要整理。', excelResult: '已由LibreOffice在本地导出。在源文件与可用字体允许的范围内保留格式、图表、图片、表格、公式和打印版式。' },
  'zh-tw': { resultMode: '活頁簿結果', exactAppearance: '精確保留外觀', exactHelp: '將每個完整PDF頁面保存在獨立工作表中。圖片、圖表、表格、字型與所有語言的外觀保持不變，但頁面內容不是可編輯儲存格。', editableCells: '可編輯文字與表格', editableHelp: '把可選取的PDF文字放入儲存格，適合簡單表格。PDF不含原始公式、圖表資料、合併儲存格或試算表結構，無法還原。', exactResult: '每個PDF頁面均無損保存在獨立工作表中。外觀準確，但內容不是可編輯儲存格。', editableResult: '已將可選取的PDF文字放入可編輯儲存格。複雜表格、公式、圖表與精確間距可能需要整理。', excelResult: '已由LibreOffice在本機匯出。在來源檔案與可用字型允許的範圍內保留格式、圖表、圖片、表格、公式與列印版面。' },
  hi: { resultMode: 'वर्कबुक परिणाम', exactAppearance: 'बिल्कुल वही रूप', exactHelp: 'हर पूरे PDF पेज को अलग शीट पर सुरक्षित रखता है। चित्र, चार्ट, टेबल, फ़ॉन्ट और सभी भाषाएँ वैसी दिखती हैं; पेज एडिट होने वाले सेल नहीं है।', editableCells: 'एडिट करने योग्य टेक्स्ट व टेबल', editableHelp: 'चुने जा सकने वाले PDF टेक्स्ट को सेल में रखता है। सरल टेबल के लिए उपयोगी; PDF में मूल फ़ॉर्मूला, चार्ट डेटा, मर्ज सेल या स्प्रेडशीट संरचना नहीं होती।', exactResult: 'हर PDF पेज को अलग शीट पर बिना नुकसान सुरक्षित किया। रूप सटीक है; सामग्री एडिट होने वाले सेल नहीं है।', editableResult: 'PDF टेक्स्ट को एडिट होने वाले सेल में रखा। जटिल टेबल, फ़ॉर्मूला, चार्ट और स्पेसिंग में सफाई लग सकती है।', excelResult: 'LibreOffice से लोकल एक्सपोर्ट हुआ। स्रोत और उपलब्ध फ़ॉन्ट जहाँ अनुमति दें वहाँ फ़ॉर्मेटिंग, चार्ट, चित्र, टेबल, फ़ॉर्मूला और प्रिंट लेआउट सुरक्षित हैं।' },
  ar: { resultMode: 'نتيجة المصنف', exactAppearance: 'مظهر مطابق', exactHelp: 'يحفظ كل صفحة PDF كاملة في ورقة مستقلة. تبقى الصور والمخططات والجداول والخطوط وكل اللغات مطابقة بصريًا، لكن الصفحة ليست خلايا قابلة للتحرير.', editableCells: 'نص وجداول قابلة للتحرير', editableHelp: 'يضع نص PDF القابل للتحديد في خلايا. مناسب للجداول البسيطة؛ لا يحتوي PDF على الصيغ أو بيانات المخططات أو الخلايا المدمجة أو البنية الأصلية.', exactResult: 'حُفظت كل صفحة PDF بلا فقد في ورقة مستقلة. المظهر مطابق، لكن المحتوى ليس خلايا قابلة للتحرير.', editableResult: 'وُضع النص القابل للتحديد في خلايا قابلة للتحرير. قد تحتاج الجداول المعقدة والصيغ والمخططات والتباعد إلى ضبط.', excelResult: 'تم التصدير محليًا بواسطة LibreOffice مع الحفاظ على التنسيق والمخططات والصور والجداول والصيغ وتخطيط الطباعة بقدر ما يسمح الملف والخطوط.' },
  ru: { resultMode: 'Результат книги', exactAppearance: 'Точный внешний вид', exactHelp: 'Сохраняет каждую страницу PDF целиком на отдельном листе. Изображения, диаграммы, таблицы, шрифты и языки выглядят точно, но страница не является редактируемыми ячейками.', editableCells: 'Редактируемый текст и таблицы', editableHelp: 'Помещает выделяемый текст PDF в ячейки. Подходит для простых таблиц; PDF не содержит исходных формул, данных диаграмм, объединённых ячеек и структуры книги.', exactResult: 'Каждая страница PDF без потерь сохранена на отдельном листе. Вид точный, но содержимое не является редактируемыми ячейками.', editableResult: 'Выделяемый текст помещён в редактируемые ячейки. Сложные таблицы, формулы, диаграммы и интервалы могут потребовать правки.', excelResult: 'Локально экспортировано LibreOffice. Форматирование, диаграммы, изображения, таблицы, формулы и печать сохраняются, насколько позволяют файл и шрифты.' },
  id: { resultMode: 'Hasil buku kerja', exactAppearance: 'Tampilan persis', exactHelp: 'Mempertahankan setiap halaman PDF lengkap di lembar tersendiri. Gambar, bagan, tabel, font, dan semua bahasa tetap utuh secara visual; halaman bukan sel yang dapat diedit.', editableCells: 'Teks & tabel yang dapat diedit', editableHelp: 'Menempatkan teks PDF yang dapat dipilih ke sel. Cocok untuk tabel sederhana; PDF tidak memiliki rumus, data bagan, sel gabungan, atau struktur spreadsheet asli.', exactResult: 'Setiap halaman PDF dipertahankan tanpa kehilangan di lembar tersendiri. Visualnya persis; isinya bukan sel yang dapat diedit.', editableResult: 'Teks PDF yang dapat dipilih ditempatkan dalam sel. Tabel kompleks, rumus, bagan, dan spasi mungkin perlu dirapikan.', excelResult: 'Diekspor lokal dengan LibreOffice. Format, bagan, gambar, tabel, rumus, dan tata letak cetak dipertahankan bila file dan font mendukung.' },
  it: { resultMode: 'Risultato cartella', exactAppearance: 'Aspetto esatto', exactHelp: 'Conserva ogni pagina PDF completa in un foglio distinto. Immagini, grafici, tabelle, font e lingue restano visivamente intatti; la pagina non è composta da celle modificabili.', editableCells: 'Testo e tabelle modificabili', editableHelp: 'Inserisce il testo selezionabile del PDF nelle celle. Utile per tabelle semplici; il PDF non contiene formule, dati dei grafici, celle unite o struttura originale.', exactResult: 'Ogni pagina PDF è conservata senza perdita nel proprio foglio. L’aspetto è esatto; il contenuto non è costituito da celle modificabili.', editableResult: 'Il testo selezionabile è stato inserito in celle modificabili. Tabelle complesse, formule, grafici e spaziatura possono richiedere correzioni.', excelResult: 'Esportato localmente con LibreOffice. Formattazione, grafici, immagini, tabelle, formule e stampa sono mantenuti quando file e font lo consentono.' },
  nl: { resultMode: 'Werkmapresultaat', exactAppearance: 'Exact uiterlijk', exactHelp: 'Behoudt elke volledige PDF-pagina op een eigen werkblad. Afbeeldingen, grafieken, tabellen, lettertypen en talen blijven visueel intact; de pagina bestaat niet uit bewerkbare cellen.', editableCells: 'Bewerkbare tekst en tabellen', editableHelp: 'Plaatst selecteerbare PDF-tekst in cellen. Handig voor eenvoudige tabellen; een PDF bevat geen oorspronkelijke formules, grafiekdata, samengevoegde cellen of werkmapstructuur.', exactResult: 'Elke PDF-pagina is verliesvrij op een eigen werkblad bewaard. Het uiterlijk is exact; de inhoud zijn geen bewerkbare cellen.', editableResult: 'Selecteerbare PDF-tekst is in bewerkbare cellen geplaatst. Complexe tabellen, formules, grafieken en afstanden kunnen nabewerking vragen.', excelResult: 'Lokaal geëxporteerd met LibreOffice. Opmaak, grafieken, afbeeldingen, tabellen, formules en afdruklayout blijven behouden als bestand en lettertypen dit toelaten.' },
  tr: { resultMode: 'Çalışma kitabı sonucu', exactAppearance: 'Tam görünüm', exactHelp: 'Her PDF sayfasını ayrı çalışma sayfasında eksiksiz korur. Görseller, grafikler, tablolar, yazı tipleri ve tüm diller görsel olarak aynı kalır; sayfa düzenlenebilir hücreler değildir.', editableCells: 'Düzenlenebilir metin ve tablolar', editableHelp: 'Seçilebilir PDF metnini hücrelere yerleştirir. Basit tablolar için; PDF özgün formülleri, grafik verisini, birleşik hücreleri veya çalışma kitabı yapısını içermez.', exactResult: 'Her PDF sayfası ayrı çalışma sayfasında kayıpsız korundu. Görünüm tamdır; içerik düzenlenebilir hücreler değildir.', editableResult: 'Seçilebilir PDF metni düzenlenebilir hücrelere yerleştirildi. Karmaşık tablolar, formüller, grafikler ve aralıklar temizlik gerektirebilir.', excelResult: 'LibreOffice ile yerel olarak dışa aktarıldı. Kaynak ve mevcut yazı tipleri izin verdiği ölçüde biçim, grafik, görsel, tablo, formül ve yazdırma düzeni korunur.' },
  vi: { resultMode: 'Kết quả sổ làm việc', exactAppearance: 'Hình thức chính xác', exactHelp: 'Giữ toàn bộ mỗi trang PDF trên một trang tính riêng. Ảnh, biểu đồ, bảng, phông chữ và mọi ngôn ngữ giữ nguyên hình thức; trang không phải các ô có thể sửa.', editableCells: 'Văn bản & bảng có thể sửa', editableHelp: 'Đặt văn bản PDF có thể chọn vào ô. Hữu ích cho bảng đơn giản; PDF không chứa công thức, dữ liệu biểu đồ, ô gộp hay cấu trúc bảng tính gốc.', exactResult: 'Mỗi trang PDF được giữ nguyên không mất dữ liệu trên trang tính riêng. Hình thức chính xác; nội dung không phải ô có thể sửa.', editableResult: 'Văn bản PDF có thể chọn đã được đặt vào ô. Bảng phức tạp, công thức, biểu đồ và khoảng cách có thể cần chỉnh.', excelResult: 'Đã xuất cục bộ bằng LibreOffice. Định dạng, biểu đồ, ảnh, bảng, công thức và bố cục in được giữ khi tệp và phông chữ cho phép.' },
  th: { resultMode: 'ผลลัพธ์สมุดงาน', exactAppearance: 'รูปลักษณ์ตรงต้นฉบับ', exactHelp: 'เก็บแต่ละหน้า PDF ทั้งหน้าไว้ในแผ่นงานแยก รูป แผนภูมิ ตาราง ฟอนต์ และทุกภาษายังคงเหมือนเดิม แต่หน้าไม่ใช่เซลล์ที่แก้ไขได้', editableCells: 'ข้อความและตารางที่แก้ไขได้', editableHelp: 'วางข้อความ PDF ที่เลือกได้ลงในเซลล์ เหมาะกับตารางง่าย ๆ เพราะ PDF ไม่มีสูตร ข้อมูลแผนภูมิ เซลล์รวม หรือโครงสร้างสเปรดชีตเดิม', exactResult: 'เก็บแต่ละหน้า PDF แบบไม่สูญเสียไว้ในแผ่นงานแยก รูปลักษณ์ตรงต้นฉบับ แต่เนื้อหาไม่ใช่เซลล์ที่แก้ไขได้', editableResult: 'วางข้อความ PDF ที่เลือกได้ลงในเซลล์แล้ว ตารางซับซ้อน สูตร แผนภูมิ และระยะห่างอาจต้องปรับ', excelResult: 'ส่งออกบนเครื่องด้วย LibreOffice โดยรักษารูปแบบ แผนภูมิ รูป ตาราง สูตร และเค้าโครงการพิมพ์เท่าที่ไฟล์และฟอนต์รองรับ' },
  pl: { resultMode: 'Wynik skoroszytu', exactAppearance: 'Dokładny wygląd', exactHelp: 'Zachowuje każdą pełną stronę PDF na osobnym arkuszu. Obrazy, wykresy, tabele, czcionki i języki pozostają wizualnie nienaruszone; strona nie jest edytowalnymi komórkami.', editableCells: 'Edytowalny tekst i tabele', editableHelp: 'Umieszcza zaznaczalny tekst PDF w komórkach. Dobre dla prostych tabel; PDF nie zawiera pierwotnych formuł, danych wykresów, scalonych komórek ani struktury arkusza.', exactResult: 'Każda strona PDF została bezstratnie zachowana na osobnym arkuszu. Wygląd jest dokładny; zawartość nie jest edytowalnymi komórkami.', editableResult: 'Zaznaczalny tekst PDF umieszczono w komórkach. Złożone tabele, formuły, wykresy i odstępy mogą wymagać poprawek.', excelResult: 'Wyeksportowano lokalnie przez LibreOffice. Formatowanie, wykresy, obrazy, tabele, formuły i druk są zachowane w zakresie obsługiwanym przez plik i czcionki.' },
};

export function getSpreadsheetToolMessages(locale: LocalePath): SpreadsheetToolMessages {
  return messages[locale] ?? messages.en;
}
