import type { LocalePath } from './config';

export interface WorkbenchMessages {
  localFileTool: string; localImageTool: string; localPdfTool: string; noUpload: string; processedHere: string;
  chooseFile: string; chooseFiles: string; chooseImage: string; choosePdf: string; dragDrop: string; remove: string; removeAll: string;
  selectedFile: string; selectedFiles: string; compressionGoal: string; auto: string; targetSize: string; reduceBy: string;
  keepUnder: string; approximateReduction: string; outputFormat: string; whatChanges: string; process: string; ready: string;
  download: string; original: string; newFile: string; convertTo: string; imageQuality: string; whatPreserved: string;
  compressionLevel: string; balanced: string; smallerFile: string; betterQuality: string; confirmLimitation: string;
  rotation: string; pageSize: string; processing: string; finished: string; failed: string; invalidFile: string; tooLarge: string;
  noText: string; password: string; review: string;
}

export const workbenchMessages: Record<LocalePath, WorkbenchMessages> = {
  en: { localFileTool: 'Local file tool', localImageTool: 'Local image tool', localPdfTool: 'Local PDF tool', noUpload: 'No server upload', processedHere: 'Processed on your device', chooseFile: 'Choose file', chooseFiles: 'Choose files', chooseImage: 'Choose image', choosePdf: 'Choose PDF', dragDrop: 'or drag and drop here', remove: 'Remove', removeAll: 'Remove all', selectedFile: 'Selected file', selectedFiles: 'Selected files', compressionGoal: 'Compression goal', auto: 'Auto', targetSize: 'Target size', reduceBy: 'Reduce by', keepUnder: 'Keep it under', approximateReduction: 'Exact reduction limit', outputFormat: 'Output format', whatChanges: 'What changes?', process: 'Process locally', ready: 'Ready to download', download: 'Download result', original: 'Original', newFile: 'New file', convertTo: 'Convert to', imageQuality: 'Image quality', whatPreserved: 'What is preserved?', compressionLevel: 'Compression level', balanced: 'Balanced', smallerFile: 'Smaller file', betterQuality: 'Better quality', confirmLimitation: 'I understand the stated formatting limitation.', rotation: 'Rotation', pageSize: 'PDF page size', processing: 'Processing locally…', finished: 'Finished. Your file never left this device.', failed: 'Local processing failed. Try another compatible file or setting.', invalidFile: 'This file is not a supported or valid format.', tooLarge: 'This file exceeds the local processing safety limit.', noText: 'No readable text was found. Scanned PDFs require OCR.', password: 'Password-protected PDFs are not supported.', review: 'Open and review the result before replacing the original.' },
  ja: { localFileTool: 'ローカルファイルツール', localImageTool: 'ローカル画像ツール', localPdfTool: 'ローカルPDFツール', noUpload: 'サーバー送信なし', processedHere: 'この端末で処理', chooseFile: 'ファイルを選択', chooseFiles: 'ファイルを選択', chooseImage: '画像を選択', choosePdf: 'PDFを選択', dragDrop: 'またはここにドラッグ＆ドロップ', remove: '削除', removeAll: 'すべて削除', selectedFile: '選択したファイル', selectedFiles: '選択したファイル', compressionGoal: '圧縮目標', auto: '自動', targetSize: '目標サイズ', reduceBy: '削減率', keepUnder: '上限サイズ', approximateReduction: '厳密な削減上限', outputFormat: '出力形式', whatChanges: '何が変わりますか？', process: '端末内で処理', ready: 'ダウンロードできます', download: '結果をダウンロード', original: '元のファイル', newFile: '新しいファイル', convertTo: '変換先', imageQuality: '画像品質', whatPreserved: '保持される内容', compressionLevel: '圧縮レベル', balanced: 'バランス', smallerFile: '小さいファイル', betterQuality: '高画質', confirmLimitation: '記載された書式上の制限を理解しました。', rotation: '回転', pageSize: 'PDFページサイズ', processing: '端末内で処理中…', finished: '完了しました。ファイルはこの端末から送信されていません。', failed: 'ローカル処理に失敗しました。対応ファイルまたは設定を変更してください。', invalidFile: '対応していないか、正しくないファイル形式です。', tooLarge: 'ローカル処理の安全上限を超えています。', noText: '読み取り可能な文字がありません。スキャンPDFにはOCRが必要です。', password: 'パスワード保護PDFには対応していません。', review: '元のファイルを置き換える前に結果を開いて確認してください。' },
  ko: { localFileTool: '로컬 파일 도구', localImageTool: '로컬 이미지 도구', localPdfTool: '로컬 PDF 도구', noUpload: '서버 업로드 없음', processedHere: '이 기기에서 처리', chooseFile: '파일 선택', chooseFiles: '파일 선택', chooseImage: '이미지 선택', choosePdf: 'PDF 선택', dragDrop: '또는 여기에 끌어다 놓기', remove: '삭제', removeAll: '모두 삭제', selectedFile: '선택한 파일', selectedFiles: '선택한 파일', compressionGoal: '압축 목표', auto: '자동', targetSize: '목표 크기', reduceBy: '줄일 비율', keepUnder: '최대 크기', approximateReduction: '정확한 축소 한도', outputFormat: '출력 형식', whatChanges: '무엇이 바뀌나요?', process: '기기에서 처리', ready: '다운로드 준비 완료', download: '결과 다운로드', original: '원본', newFile: '새 파일', convertTo: '변환 형식', imageQuality: '이미지 품질', whatPreserved: '유지되는 항목', compressionLevel: '압축 수준', balanced: '균형', smallerFile: '더 작은 파일', betterQuality: '더 높은 품질', confirmLimitation: '안내된 서식 제한을 이해했습니다.', rotation: '회전', pageSize: 'PDF 페이지 크기', processing: '기기에서 처리 중…', finished: '완료되었습니다. 파일은 이 기기를 떠나지 않았습니다.', failed: '로컬 처리에 실패했습니다. 호환 파일이나 설정을 다시 선택하세요.', invalidFile: '지원되지 않거나 올바르지 않은 파일 형식입니다.', tooLarge: '로컬 처리 안전 한도를 초과했습니다.', noText: '읽을 수 있는 텍스트가 없습니다. 스캔 PDF에는 OCR이 필요합니다.', password: '암호로 보호된 PDF는 지원되지 않습니다.', review: '원본을 교체하기 전에 결과를 열어 확인하세요.' },
  es: { localFileTool: 'Herramienta local', localImageTool: 'Herramienta de imagen local', localPdfTool: 'Herramienta PDF local', noUpload: 'Sin subida al servidor', processedHere: 'Procesado en tu dispositivo', chooseFile: 'Elegir archivo', chooseFiles: 'Elegir archivos', chooseImage: 'Elegir imagen', choosePdf: 'Elegir PDF', dragDrop: 'o arrastra y suelta aquí', remove: 'Quitar', removeAll: 'Quitar todo', selectedFile: 'Archivo seleccionado', selectedFiles: 'Archivos seleccionados', compressionGoal: 'Objetivo de compresión', auto: 'Automático', targetSize: 'Tamaño objetivo', reduceBy: 'Reducir en', keepUnder: 'Mantener por debajo de', approximateReduction: 'Límite exacto de reducción', outputFormat: 'Formato de salida', whatChanges: '¿Qué cambia?', process: 'Procesar localmente', ready: 'Listo para descargar', download: 'Descargar resultado', original: 'Original', newFile: 'Archivo nuevo', convertTo: 'Convertir a', imageQuality: 'Calidad de imagen', whatPreserved: '¿Qué se conserva?', compressionLevel: 'Nivel de compresión', balanced: 'Equilibrado', smallerFile: 'Archivo más pequeño', betterQuality: 'Mejor calidad', confirmLimitation: 'Entiendo la limitación de formato indicada.', rotation: 'Rotación', pageSize: 'Tamaño de página PDF', processing: 'Procesando localmente…', finished: 'Listo. El archivo nunca salió de tu dispositivo.', failed: 'Falló el procesamiento local. Prueba otro archivo compatible o ajuste.', invalidFile: 'El formato no es válido o no es compatible.', tooLarge: 'El archivo supera el límite seguro de procesamiento local.', noText: 'No se encontró texto legible. Los PDF escaneados necesitan OCR.', password: 'Los PDF protegidos con contraseña no son compatibles.', review: 'Abre y revisa el resultado antes de sustituir el original.' },
  fr: { localFileTool: 'Outil de fichier local', localImageTool: 'Outil d’image local', localPdfTool: 'Outil PDF local', noUpload: 'Aucun envoi au serveur', processedHere: 'Traité sur votre appareil', chooseFile: 'Choisir un fichier', chooseFiles: 'Choisir des fichiers', chooseImage: 'Choisir une image', choosePdf: 'Choisir un PDF', dragDrop: 'ou glissez-déposez ici', remove: 'Retirer', removeAll: 'Tout retirer', selectedFile: 'Fichier sélectionné', selectedFiles: 'Fichiers sélectionnés', compressionGoal: 'Objectif de compression', auto: 'Automatique', targetSize: 'Taille cible', reduceBy: 'Réduire de', keepUnder: 'Rester sous', approximateReduction: 'Limite exacte de réduction', outputFormat: 'Format de sortie', whatChanges: 'Qu’est-ce qui change ?', process: 'Traiter localement', ready: 'Prêt à télécharger', download: 'Télécharger le résultat', original: 'Original', newFile: 'Nouveau fichier', convertTo: 'Convertir en', imageQuality: 'Qualité de l’image', whatPreserved: 'Qu’est-ce qui est conservé ?', compressionLevel: 'Niveau de compression', balanced: 'Équilibré', smallerFile: 'Fichier plus petit', betterQuality: 'Meilleure qualité', confirmLimitation: 'Je comprends la limite de mise en forme indiquée.', rotation: 'Rotation', pageSize: 'Taille de page PDF', processing: 'Traitement local en cours…', finished: 'Terminé. Le fichier n’a jamais quitté votre appareil.', failed: 'Le traitement local a échoué. Essayez un autre fichier compatible ou réglage.', invalidFile: 'Ce format de fichier est invalide ou non pris en charge.', tooLarge: 'Ce fichier dépasse la limite de sécurité du traitement local.', noText: 'Aucun texte lisible trouvé. Un PDF numérisé nécessite de l’OCR.', password: 'Les PDF protégés par mot de passe ne sont pas pris en charge.', review: 'Ouvrez et vérifiez le résultat avant de remplacer l’original.' },
  de: { localFileTool: 'Lokales Dateitool', localImageTool: 'Lokales Bildtool', localPdfTool: 'Lokales PDF-Tool', noUpload: 'Kein Server-Upload', processedHere: 'Auf deinem Gerät verarbeitet', chooseFile: 'Datei auswählen', chooseFiles: 'Dateien auswählen', chooseImage: 'Bild auswählen', choosePdf: 'PDF auswählen', dragDrop: 'oder hierher ziehen', remove: 'Entfernen', removeAll: 'Alle entfernen', selectedFile: 'Ausgewählte Datei', selectedFiles: 'Ausgewählte Dateien', compressionGoal: 'Kompressionsziel', auto: 'Automatisch', targetSize: 'Zielgröße', reduceBy: 'Reduzieren um', keepUnder: 'Unter dieser Größe', approximateReduction: 'Exaktes Reduktionslimit', outputFormat: 'Ausgabeformat', whatChanges: 'Was ändert sich?', process: 'Lokal verarbeiten', ready: 'Bereit zum Herunterladen', download: 'Ergebnis herunterladen', original: 'Original', newFile: 'Neue Datei', convertTo: 'Konvertieren in', imageQuality: 'Bildqualität', whatPreserved: 'Was bleibt erhalten?', compressionLevel: 'Kompressionsstufe', balanced: 'Ausgewogen', smallerFile: 'Kleinere Datei', betterQuality: 'Bessere Qualität', confirmLimitation: 'Ich verstehe die angegebene Formatierungsgrenze.', rotation: 'Drehung', pageSize: 'PDF-Seitengröße', processing: 'Wird lokal verarbeitet…', finished: 'Fertig. Die Datei hat dein Gerät nie verlassen.', failed: 'Lokale Verarbeitung fehlgeschlagen. Probiere eine andere kompatible Datei oder Einstellung.', invalidFile: 'Dieses Dateiformat ist ungültig oder wird nicht unterstützt.', tooLarge: 'Die Datei überschreitet das sichere Limit für lokale Verarbeitung.', noText: 'Kein lesbarer Text gefunden. Gescannte PDFs benötigen OCR.', password: 'Passwortgeschützte PDFs werden nicht unterstützt.', review: 'Öffne und prüfe das Ergebnis, bevor du das Original ersetzt.' },
  pt: { localFileTool: 'Ferramenta local', localImageTool: 'Ferramenta de imagem local', localPdfTool: 'Ferramenta PDF local', noUpload: 'Sem envio ao servidor', processedHere: 'Processado no seu dispositivo', chooseFile: 'Escolher ficheiro', chooseFiles: 'Escolher ficheiros', chooseImage: 'Escolher imagem', choosePdf: 'Escolher PDF', dragDrop: 'ou arraste e largue aqui', remove: 'Remover', removeAll: 'Remover tudo', selectedFile: 'Ficheiro selecionado', selectedFiles: 'Ficheiros selecionados', compressionGoal: 'Objetivo de compressão', auto: 'Automático', targetSize: 'Tamanho alvo', reduceBy: 'Reduzir em', keepUnder: 'Manter abaixo de', approximateReduction: 'Limite exato de redução', outputFormat: 'Formato de saída', whatChanges: 'O que muda?', process: 'Processar localmente', ready: 'Pronto para descarregar', download: 'Descarregar resultado', original: 'Original', newFile: 'Novo ficheiro', convertTo: 'Converter para', imageQuality: 'Qualidade da imagem', whatPreserved: 'O que é preservado?', compressionLevel: 'Nível de compressão', balanced: 'Equilibrado', smallerFile: 'Ficheiro menor', betterQuality: 'Melhor qualidade', confirmLimitation: 'Compreendo a limitação de formatação indicada.', rotation: 'Rotação', pageSize: 'Tamanho da página PDF', processing: 'A processar localmente…', finished: 'Concluído. O ficheiro nunca saiu do dispositivo.', failed: 'O processamento local falhou. Tente outro ficheiro compatível ou definição.', invalidFile: 'Este formato é inválido ou não suportado.', tooLarge: 'O ficheiro excede o limite seguro de processamento local.', noText: 'Não foi encontrado texto legível. PDF digitalizado precisa de OCR.', password: 'PDF protegido por palavra-passe não é suportado.', review: 'Abra e verifique o resultado antes de substituir o original.' },
  'zh-cn': { localFileTool: '本地文件工具', localImageTool: '本地图像工具', localPdfTool: '本地 PDF 工具', noUpload: '无需上传服务器', processedHere: '在您的设备上处理', chooseFile: '选择文件', chooseFiles: '选择文件', chooseImage: '选择图片', choosePdf: '选择 PDF', dragDrop: '或拖放到此处', remove: '移除', removeAll: '全部移除', selectedFile: '已选文件', selectedFiles: '已选文件', compressionGoal: '压缩目标', auto: '自动', targetSize: '目标大小', reduceBy: '缩小比例', keepUnder: '控制在以下大小', approximateReduction: '精确缩减上限', outputFormat: '输出格式', whatChanges: '会发生什么变化？', process: '在本地处理', ready: '可以下载', download: '下载结果', original: '原文件', newFile: '新文件', convertTo: '转换为', imageQuality: '图像质量', whatPreserved: '会保留什么？', compressionLevel: '压缩级别', balanced: '均衡', smallerFile: '更小文件', betterQuality: '更高质量', confirmLimitation: '我了解所述的格式限制。', rotation: '旋转', pageSize: 'PDF 页面大小', processing: '正在本地处理…', finished: '已完成。文件从未离开您的设备。', failed: '本地处理失败。请尝试其他兼容文件或设置。', invalidFile: '文件格式无效或不受支持。', tooLarge: '文件超过本地处理安全限制。', noText: '未找到可读文字。扫描 PDF 需要 OCR。', password: '暂不支持受密码保护的 PDF。', review: '替换原文件前，请打开并检查结果。' },
  'zh-tw': { localFileTool: '本機檔案工具', localImageTool: '本機圖片工具', localPdfTool: '本機 PDF 工具', noUpload: '不會上傳伺服器', processedHere: '在您的裝置上處理', chooseFile: '選擇檔案', chooseFiles: '選擇檔案', chooseImage: '選擇圖片', choosePdf: '選擇 PDF', dragDrop: '或拖放到此處', remove: '移除', removeAll: '全部移除', selectedFile: '已選檔案', selectedFiles: '已選檔案', compressionGoal: '壓縮目標', auto: '自動', targetSize: '目標大小', reduceBy: '縮小比例', keepUnder: '控制在以下大小', approximateReduction: '精確縮減上限', outputFormat: '輸出格式', whatChanges: '會有哪些變更？', process: '在本機處理', ready: '可以下載', download: '下載結果', original: '原始檔案', newFile: '新檔案', convertTo: '轉換為', imageQuality: '圖片品質', whatPreserved: '會保留什麼？', compressionLevel: '壓縮等級', balanced: '均衡', smallerFile: '較小檔案', betterQuality: '較佳品質', confirmLimitation: '我了解上述格式限制。', rotation: '旋轉', pageSize: 'PDF 頁面大小', processing: '正在本機處理…', finished: '已完成。檔案從未離開您的裝置。', failed: '本機處理失敗。請嘗試其他相容檔案或設定。', invalidFile: '檔案格式無效或不受支援。', tooLarge: '檔案超過本機處理安全限制。', noText: '找不到可讀文字。掃描 PDF 需要 OCR。', password: '不支援受密碼保護的 PDF。', review: '替換原始檔案前，請開啟並檢查結果。' },
  hi: { localFileTool: 'स्थानीय फ़ाइल टूल', localImageTool: 'स्थानीय इमेज टूल', localPdfTool: 'स्थानीय PDF टूल', noUpload: 'सर्वर अपलोड नहीं', processedHere: 'आपके डिवाइस पर प्रोसेस', chooseFile: 'फ़ाइल चुनें', chooseFiles: 'फ़ाइलें चुनें', chooseImage: 'इमेज चुनें', choosePdf: 'PDF चुनें', dragDrop: 'या यहाँ खींचकर छोड़ें', remove: 'हटाएँ', removeAll: 'सभी हटाएँ', selectedFile: 'चुनी गई फ़ाइल', selectedFiles: 'चुनी गई फ़ाइलें', compressionGoal: 'कंप्रेशन लक्ष्य', auto: 'ऑटो', targetSize: 'लक्षित आकार', reduceBy: 'इतना घटाएँ', keepUnder: 'इससे कम रखें', approximateReduction: 'सटीक कमी सीमा', outputFormat: 'आउटपुट फ़ॉर्मेट', whatChanges: 'क्या बदलेगा?', process: 'स्थानीय रूप से प्रोसेस करें', ready: 'डाउनलोड के लिए तैयार', download: 'परिणाम डाउनलोड करें', original: 'मूल', newFile: 'नई फ़ाइल', convertTo: 'इसमें बदलें', imageQuality: 'इमेज गुणवत्ता', whatPreserved: 'क्या सुरक्षित रहेगा?', compressionLevel: 'कंप्रेशन स्तर', balanced: 'संतुलित', smallerFile: 'छोटी फ़ाइल', betterQuality: 'बेहतर गुणवत्ता', confirmLimitation: 'मैं बताई गई फ़ॉर्मेटिंग सीमा समझता/समझती हूँ।', rotation: 'रोटेशन', pageSize: 'PDF पेज आकार', processing: 'डिवाइस पर प्रोसेस हो रहा है…', finished: 'पूरा हुआ। फ़ाइल आपके डिवाइस से बाहर नहीं गई।', failed: 'स्थानीय प्रोसेसिंग विफल रही। दूसरी संगत फ़ाइल या सेटिंग आज़माएँ।', invalidFile: 'यह फ़ाइल फ़ॉर्मेट मान्य या समर्थित नहीं है।', tooLarge: 'फ़ाइल स्थानीय प्रोसेसिंग की सुरक्षित सीमा से बड़ी है।', noText: 'पढ़ने योग्य टेक्स्ट नहीं मिला। स्कैन PDF के लिए OCR चाहिए।', password: 'पासवर्ड-सुरक्षित PDF समर्थित नहीं है।', review: 'मूल फ़ाइल बदलने से पहले परिणाम खोलकर जाँचें।' },
  ar: { localFileTool: 'أداة ملفات محلية', localImageTool: 'أداة صور محلية', localPdfTool: 'أداة PDF محلية', noUpload: 'من دون رفع إلى الخادم', processedHere: 'تتم المعالجة على جهازك', chooseFile: 'اختر ملفًا', chooseFiles: 'اختر ملفات', chooseImage: 'اختر صورة', choosePdf: 'اختر PDF', dragDrop: 'أو اسحب وأفلت هنا', remove: 'إزالة', removeAll: 'إزالة الكل', selectedFile: 'الملف المحدد', selectedFiles: 'الملفات المحددة', compressionGoal: 'هدف الضغط', auto: 'تلقائي', targetSize: 'الحجم المستهدف', reduceBy: 'تقليل بنسبة', keepUnder: 'إبقاء الحجم أقل من', approximateReduction: 'حد التخفيض الدقيق', outputFormat: 'تنسيق الإخراج', whatChanges: 'ما الذي سيتغير؟', process: 'المعالجة محليًا', ready: 'جاهز للتنزيل', download: 'تنزيل النتيجة', original: 'الأصل', newFile: 'ملف جديد', convertTo: 'التحويل إلى', imageQuality: 'جودة الصورة', whatPreserved: 'ما الذي سيُحفظ؟', compressionLevel: 'مستوى الضغط', balanced: 'متوازن', smallerFile: 'ملف أصغر', betterQuality: 'جودة أفضل', confirmLimitation: 'أفهم قيد التنسيق الموضح.', rotation: 'التدوير', pageSize: 'حجم صفحة PDF', processing: 'تتم المعالجة محليًا…', finished: 'اكتملت العملية. لم يغادر الملف جهازك.', failed: 'فشلت المعالجة المحلية. جرّب ملفًا متوافقًا أو إعدادًا آخر.', invalidFile: 'تنسيق الملف غير صالح أو غير مدعوم.', tooLarge: 'يتجاوز الملف حد الأمان للمعالجة المحلية.', noText: 'لم يُعثر على نص قابل للقراءة. يحتاج PDF الممسوح ضوئيًا إلى OCR.', password: 'ملفات PDF المحمية بكلمة مرور غير مدعومة.', review: 'افتح النتيجة وراجعها قبل استبدال الملف الأصلي.' },
  ru: { localFileTool: 'Локальный файловый инструмент', localImageTool: 'Локальный инструмент для изображений', localPdfTool: 'Локальный PDF-инструмент', noUpload: 'Без загрузки на сервер', processedHere: 'Обработка на вашем устройстве', chooseFile: 'Выбрать файл', chooseFiles: 'Выбрать файлы', chooseImage: 'Выбрать изображение', choosePdf: 'Выбрать PDF', dragDrop: 'или перетащите сюда', remove: 'Удалить', removeAll: 'Удалить все', selectedFile: 'Выбранный файл', selectedFiles: 'Выбранные файлы', compressionGoal: 'Цель сжатия', auto: 'Авто', targetSize: 'Целевой размер', reduceBy: 'Уменьшить на', keepUnder: 'Размер не более', approximateReduction: 'Точный предел уменьшения', outputFormat: 'Формат результата', whatChanges: 'Что изменится?', process: 'Обработать локально', ready: 'Готово к скачиванию', download: 'Скачать результат', original: 'Оригинал', newFile: 'Новый файл', convertTo: 'Преобразовать в', imageQuality: 'Качество изображения', whatPreserved: 'Что сохраняется?', compressionLevel: 'Уровень сжатия', balanced: 'Сбалансированный', smallerFile: 'Меньший файл', betterQuality: 'Лучшее качество', confirmLimitation: 'Я понимаю указанное ограничение форматирования.', rotation: 'Поворот', pageSize: 'Размер страницы PDF', processing: 'Локальная обработка…', finished: 'Готово. Файл не покидал ваше устройство.', failed: 'Локальная обработка не удалась. Попробуйте другой совместимый файл или настройку.', invalidFile: 'Формат файла недействителен или не поддерживается.', tooLarge: 'Файл превышает безопасный лимит локальной обработки.', noText: 'Читаемый текст не найден. Для сканированного PDF нужен OCR.', password: 'PDF с паролем не поддерживается.', review: 'Откройте и проверьте результат перед заменой оригинала.' },
  id: { localFileTool: 'Alat file lokal', localImageTool: 'Alat gambar lokal', localPdfTool: 'Alat PDF lokal', noUpload: 'Tanpa unggah ke server', processedHere: 'Diproses di perangkat Anda', chooseFile: 'Pilih file', chooseFiles: 'Pilih file', chooseImage: 'Pilih gambar', choosePdf: 'Pilih PDF', dragDrop: 'atau seret dan lepas di sini', remove: 'Hapus', removeAll: 'Hapus semua', selectedFile: 'File terpilih', selectedFiles: 'File terpilih', compressionGoal: 'Target kompresi', auto: 'Otomatis', targetSize: 'Ukuran target', reduceBy: 'Kurangi sebesar', keepUnder: 'Jaga di bawah', approximateReduction: 'Batas pengurangan pasti', outputFormat: 'Format keluaran', whatChanges: 'Apa yang berubah?', process: 'Proses secara lokal', ready: 'Siap diunduh', download: 'Unduh hasil', original: 'Asli', newFile: 'File baru', convertTo: 'Konversi ke', imageQuality: 'Kualitas gambar', whatPreserved: 'Apa yang dipertahankan?', compressionLevel: 'Tingkat kompresi', balanced: 'Seimbang', smallerFile: 'File lebih kecil', betterQuality: 'Kualitas lebih baik', confirmLimitation: 'Saya memahami batas pemformatan yang dijelaskan.', rotation: 'Rotasi', pageSize: 'Ukuran halaman PDF', processing: 'Memproses secara lokal…', finished: 'Selesai. File tidak pernah meninggalkan perangkat Anda.', failed: 'Pemrosesan lokal gagal. Coba file kompatibel atau pengaturan lain.', invalidFile: 'Format file tidak valid atau tidak didukung.', tooLarge: 'File melebihi batas aman pemrosesan lokal.', noText: 'Teks yang dapat dibaca tidak ditemukan. PDF pindaian memerlukan OCR.', password: 'PDF yang dilindungi sandi tidak didukung.', review: 'Buka dan periksa hasil sebelum mengganti file asli.' },
  it: { localFileTool: 'Strumento file locale', localImageTool: 'Strumento immagini locale', localPdfTool: 'Strumento PDF locale', noUpload: 'Nessun caricamento sul server', processedHere: 'Elaborato sul tuo dispositivo', chooseFile: 'Scegli file', chooseFiles: 'Scegli file', chooseImage: 'Scegli immagine', choosePdf: 'Scegli PDF', dragDrop: 'oppure trascina qui', remove: 'Rimuovi', removeAll: 'Rimuovi tutto', selectedFile: 'File selezionato', selectedFiles: 'File selezionati', compressionGoal: 'Obiettivo di compressione', auto: 'Automatico', targetSize: 'Dimensione obiettivo', reduceBy: 'Riduci del', keepUnder: 'Mantieni sotto', approximateReduction: 'Limite esatto di riduzione', outputFormat: 'Formato di uscita', whatChanges: 'Cosa cambia?', process: 'Elabora localmente', ready: 'Pronto da scaricare', download: 'Scarica risultato', original: 'Originale', newFile: 'Nuovo file', convertTo: 'Converti in', imageQuality: 'Qualità immagine', whatPreserved: 'Cosa viene conservato?', compressionLevel: 'Livello di compressione', balanced: 'Bilanciato', smallerFile: 'File più piccolo', betterQuality: 'Qualità migliore', confirmLimitation: 'Comprendo il limite di formattazione indicato.', rotation: 'Rotazione', pageSize: 'Dimensione pagina PDF', processing: 'Elaborazione locale…', finished: 'Completato. Il file non ha mai lasciato il dispositivo.', failed: 'Elaborazione locale non riuscita. Prova un altro file compatibile o impostazione.', invalidFile: 'Il formato non è valido o non è supportato.', tooLarge: 'Il file supera il limite sicuro di elaborazione locale.', noText: 'Nessun testo leggibile trovato. I PDF scansionati richiedono OCR.', password: 'I PDF protetti da password non sono supportati.', review: 'Apri e verifica il risultato prima di sostituire l’originale.' },
  nl: { localFileTool: 'Lokaal bestandsgereedschap', localImageTool: 'Lokaal afbeeldingsgereedschap', localPdfTool: 'Lokaal PDF-gereedschap', noUpload: 'Geen serverupload', processedHere: 'Verwerkt op je apparaat', chooseFile: 'Bestand kiezen', chooseFiles: 'Bestanden kiezen', chooseImage: 'Afbeelding kiezen', choosePdf: 'PDF kiezen', dragDrop: 'of sleep het hierheen', remove: 'Verwijderen', removeAll: 'Alles verwijderen', selectedFile: 'Geselecteerd bestand', selectedFiles: 'Geselecteerde bestanden', compressionGoal: 'Compressiedoel', auto: 'Automatisch', targetSize: 'Doelgrootte', reduceBy: 'Verkleinen met', keepUnder: 'Houd onder', approximateReduction: 'Exacte verkleiningslimiet', outputFormat: 'Uitvoerformaat', whatChanges: 'Wat verandert er?', process: 'Lokaal verwerken', ready: 'Klaar om te downloaden', download: 'Resultaat downloaden', original: 'Origineel', newFile: 'Nieuw bestand', convertTo: 'Converteren naar', imageQuality: 'Beeldkwaliteit', whatPreserved: 'Wat blijft behouden?', compressionLevel: 'Compressieniveau', balanced: 'Gebalanceerd', smallerFile: 'Kleiner bestand', betterQuality: 'Betere kwaliteit', confirmLimitation: 'Ik begrijp de genoemde opmaakbeperking.', rotation: 'Rotatie', pageSize: 'PDF-paginaformaat', processing: 'Wordt lokaal verwerkt…', finished: 'Klaar. Het bestand heeft je apparaat nooit verlaten.', failed: 'Lokale verwerking mislukt. Probeer een ander compatibel bestand of instelling.', invalidFile: 'Dit bestandsformaat is ongeldig of niet ondersteund.', tooLarge: 'Het bestand overschrijdt de veilige limiet voor lokale verwerking.', noText: 'Geen leesbare tekst gevonden. Gescande PDF’s hebben OCR nodig.', password: 'PDF’s met een wachtwoord worden niet ondersteund.', review: 'Open en controleer het resultaat voordat je het origineel vervangt.' },
  tr: { localFileTool: 'Yerel dosya aracı', localImageTool: 'Yerel görsel aracı', localPdfTool: 'Yerel PDF aracı', noUpload: 'Sunucuya yükleme yok', processedHere: 'Cihazınızda işlenir', chooseFile: 'Dosya seç', chooseFiles: 'Dosyaları seç', chooseImage: 'Görsel seç', choosePdf: 'PDF seç', dragDrop: 'veya buraya sürükleyip bırakın', remove: 'Kaldır', removeAll: 'Tümünü kaldır', selectedFile: 'Seçilen dosya', selectedFiles: 'Seçilen dosyalar', compressionGoal: 'Sıkıştırma hedefi', auto: 'Otomatik', targetSize: 'Hedef boyut', reduceBy: 'Azaltma oranı', keepUnder: 'Şunun altında tut', approximateReduction: 'Kesin küçültme sınırı', outputFormat: 'Çıktı biçimi', whatChanges: 'Neler değişir?', process: 'Yerel olarak işle', ready: 'İndirmeye hazır', download: 'Sonucu indir', original: 'Orijinal', newFile: 'Yeni dosya', convertTo: 'Şuna dönüştür', imageQuality: 'Görsel kalitesi', whatPreserved: 'Neler korunur?', compressionLevel: 'Sıkıştırma düzeyi', balanced: 'Dengeli', smallerFile: 'Daha küçük dosya', betterQuality: 'Daha iyi kalite', confirmLimitation: 'Belirtilen biçimlendirme sınırını anlıyorum.', rotation: 'Döndürme', pageSize: 'PDF sayfa boyutu', processing: 'Yerel olarak işleniyor…', finished: 'Tamamlandı. Dosya cihazınızdan hiç ayrılmadı.', failed: 'Yerel işlem başarısız oldu. Başka bir uyumlu dosya veya ayar deneyin.', invalidFile: 'Dosya biçimi geçersiz veya desteklenmiyor.', tooLarge: 'Dosya yerel işlem güvenlik sınırını aşıyor.', noText: 'Okunabilir metin bulunamadı. Taranmış PDF için OCR gerekir.', password: 'Parola korumalı PDF desteklenmiyor.', review: 'Orijinali değiştirmeden önce sonucu açıp kontrol edin.' },
  vi: { localFileTool: 'Công cụ tệp cục bộ', localImageTool: 'Công cụ ảnh cục bộ', localPdfTool: 'Công cụ PDF cục bộ', noUpload: 'Không tải lên máy chủ', processedHere: 'Xử lý trên thiết bị của bạn', chooseFile: 'Chọn tệp', chooseFiles: 'Chọn các tệp', chooseImage: 'Chọn ảnh', choosePdf: 'Chọn PDF', dragDrop: 'hoặc kéo thả vào đây', remove: 'Xóa', removeAll: 'Xóa tất cả', selectedFile: 'Tệp đã chọn', selectedFiles: 'Các tệp đã chọn', compressionGoal: 'Mục tiêu nén', auto: 'Tự động', targetSize: 'Kích thước mục tiêu', reduceBy: 'Giảm theo', keepUnder: 'Giữ dưới', approximateReduction: 'Giới hạn giảm chính xác', outputFormat: 'Định dạng đầu ra', whatChanges: 'Điều gì thay đổi?', process: 'Xử lý cục bộ', ready: 'Sẵn sàng tải xuống', download: 'Tải kết quả', original: 'Bản gốc', newFile: 'Tệp mới', convertTo: 'Chuyển sang', imageQuality: 'Chất lượng ảnh', whatPreserved: 'Nội dung nào được giữ?', compressionLevel: 'Mức nén', balanced: 'Cân bằng', smallerFile: 'Tệp nhỏ hơn', betterQuality: 'Chất lượng tốt hơn', confirmLimitation: 'Tôi hiểu giới hạn định dạng đã nêu.', rotation: 'Xoay', pageSize: 'Kích thước trang PDF', processing: 'Đang xử lý cục bộ…', finished: 'Đã xong. Tệp không rời khỏi thiết bị của bạn.', failed: 'Xử lý cục bộ thất bại. Hãy thử tệp tương thích hoặc cài đặt khác.', invalidFile: 'Định dạng tệp không hợp lệ hoặc không được hỗ trợ.', tooLarge: 'Tệp vượt quá giới hạn an toàn của xử lý cục bộ.', noText: 'Không tìm thấy văn bản có thể đọc. PDF quét cần OCR.', password: 'Không hỗ trợ PDF có mật khẩu.', review: 'Mở và kiểm tra kết quả trước khi thay thế bản gốc.' },
  th: { localFileTool: 'เครื่องมือไฟล์ในเครื่อง', localImageTool: 'เครื่องมือรูปภาพในเครื่อง', localPdfTool: 'เครื่องมือ PDF ในเครื่อง', noUpload: 'ไม่อัปโหลดไปยังเซิร์ฟเวอร์', processedHere: 'ประมวลผลบนอุปกรณ์ของคุณ', chooseFile: 'เลือกไฟล์', chooseFiles: 'เลือกไฟล์', chooseImage: 'เลือกรูปภาพ', choosePdf: 'เลือก PDF', dragDrop: 'หรือลากมาวางที่นี่', remove: 'นำออก', removeAll: 'นำออกทั้งหมด', selectedFile: 'ไฟล์ที่เลือก', selectedFiles: 'ไฟล์ที่เลือก', compressionGoal: 'เป้าหมายการบีบอัด', auto: 'อัตโนมัติ', targetSize: 'ขนาดเป้าหมาย', reduceBy: 'ลดลง', keepUnder: 'ให้ต่ำกว่า', approximateReduction: 'ขีดจำกัดการลดที่แน่นอน', outputFormat: 'รูปแบบผลลัพธ์', whatChanges: 'มีอะไรเปลี่ยนแปลง?', process: 'ประมวลผลในเครื่อง', ready: 'พร้อมดาวน์โหลด', download: 'ดาวน์โหลดผลลัพธ์', original: 'ต้นฉบับ', newFile: 'ไฟล์ใหม่', convertTo: 'แปลงเป็น', imageQuality: 'คุณภาพรูปภาพ', whatPreserved: 'มีอะไรคงอยู่?', compressionLevel: 'ระดับการบีบอัด', balanced: 'สมดุล', smallerFile: 'ไฟล์เล็กลง', betterQuality: 'คุณภาพดีกว่า', confirmLimitation: 'ฉันเข้าใจข้อจำกัดด้านรูปแบบที่ระบุ', rotation: 'การหมุน', pageSize: 'ขนาดหน้า PDF', processing: 'กำลังประมวลผลในเครื่อง…', finished: 'เสร็จแล้ว ไฟล์ไม่เคยออกจากอุปกรณ์ของคุณ', failed: 'การประมวลผลในเครื่องล้มเหลว ลองใช้ไฟล์หรือการตั้งค่าอื่นที่รองรับ', invalidFile: 'รูปแบบไฟล์ไม่ถูกต้องหรือไม่รองรับ', tooLarge: 'ไฟล์เกินขีดจำกัดความปลอดภัยของการประมวลผลในเครื่อง', noText: 'ไม่พบข้อความที่อ่านได้ PDF ที่สแกนต้องใช้ OCR', password: 'ไม่รองรับ PDF ที่ป้องกันด้วยรหัสผ่าน', review: 'เปิดและตรวจสอบผลลัพธ์ก่อนแทนที่ไฟล์ต้นฉบับ' },
  pl: { localFileTool: 'Lokalne narzędzie plikowe', localImageTool: 'Lokalne narzędzie obrazów', localPdfTool: 'Lokalne narzędzie PDF', noUpload: 'Bez wysyłania na serwer', processedHere: 'Przetwarzane na Twoim urządzeniu', chooseFile: 'Wybierz plik', chooseFiles: 'Wybierz pliki', chooseImage: 'Wybierz obraz', choosePdf: 'Wybierz PDF', dragDrop: 'lub przeciągnij i upuść tutaj', remove: 'Usuń', removeAll: 'Usuń wszystko', selectedFile: 'Wybrany plik', selectedFiles: 'Wybrane pliki', compressionGoal: 'Cel kompresji', auto: 'Automatycznie', targetSize: 'Rozmiar docelowy', reduceBy: 'Zmniejsz o', keepUnder: 'Utrzymaj poniżej', approximateReduction: 'Dokładny limit zmniejszenia', outputFormat: 'Format wyjściowy', whatChanges: 'Co się zmieni?', process: 'Przetwórz lokalnie', ready: 'Gotowe do pobrania', download: 'Pobierz wynik', original: 'Oryginał', newFile: 'Nowy plik', convertTo: 'Konwertuj do', imageQuality: 'Jakość obrazu', whatPreserved: 'Co zostanie zachowane?', compressionLevel: 'Poziom kompresji', balanced: 'Zrównoważony', smallerFile: 'Mniejszy plik', betterQuality: 'Lepsza jakość', confirmLimitation: 'Rozumiem podane ograniczenie formatowania.', rotation: 'Obrót', pageSize: 'Rozmiar strony PDF', processing: 'Przetwarzanie lokalne…', finished: 'Gotowe. Plik nigdy nie opuścił Twojego urządzenia.', failed: 'Lokalne przetwarzanie nie powiodło się. Spróbuj innego zgodnego pliku lub ustawienia.', invalidFile: 'Format pliku jest nieprawidłowy lub nieobsługiwany.', tooLarge: 'Plik przekracza bezpieczny limit lokalnego przetwarzania.', noText: 'Nie znaleziono czytelnego tekstu. Skanowany PDF wymaga OCR.', password: 'PDF zabezpieczony hasłem nie jest obsługiwany.', review: 'Otwórz i sprawdź wynik przed zastąpieniem oryginału.' },
};

const hardReductionMessages: Record<LocalePath, string> = {
  en: 'This is a hard byte limit. An 80% reduction produces a file no larger than 20% of the original.',
  ja: 'これは厳密なバイト上限です。80%削減では、出力ファイルは元の20%以下になります。',
  ko: '이는 엄격한 바이트 제한입니다. 80% 축소를 선택하면 결과 파일은 원본의 20%를 넘지 않습니다.',
  es: 'Este es un límite estricto de bytes. Una reducción del 80 % produce un archivo de como máximo el 20 % del original.',
  fr: 'Il s’agit d’une limite stricte en octets. Une réduction de 80 % produit un fichier ne dépassant pas 20 % de l’original.',
  de: 'Dies ist ein festes Byte-Limit. Eine Reduzierung um 80 % erzeugt eine Datei, die höchstens 20 % des Originals groß ist.',
  pt: 'Este é um limite rígido de bytes. Uma redução de 80% produz um ficheiro com no máximo 20% do tamanho original.',
  'zh-cn': '这是严格的字节上限。减少 80% 时，输出文件不会超过原文件大小的 20%。',
  'zh-tw': '這是嚴格的位元組上限。縮減 80% 時，輸出檔案不會超過原檔案大小的 20%。',
  hi: 'यह बाइट आकार की सख्त सीमा है। 80% कमी पर आउटपुट फ़ाइल मूल फ़ाइल के 20% से बड़ी नहीं होगी।',
  ar: 'هذا حد صارم للحجم بالبايت. عند التخفيض بنسبة 80%، لن يتجاوز حجم الملف الناتج 20% من حجم الملف الأصلي.',
  ru: 'Это строгий лимит размера в байтах. При уменьшении на 80% итоговый файл будет не больше 20% исходного.',
  id: 'Ini adalah batas byte yang ketat. Pengurangan 80% menghasilkan file yang tidak lebih besar dari 20% ukuran asli.',
  it: 'Questo è un limite rigido in byte. Una riduzione dell’80% produce un file non superiore al 20% dell’originale.',
  nl: 'Dit is een harde limiet in bytes. Een verkleining van 80% levert een bestand op dat niet groter is dan 20% van het origineel.',
  tr: 'Bu, bayt cinsinden kesin bir üst sınırdır. %80 küçültme, özgün dosyanın en fazla %20’si boyutunda bir dosya üretir.',
  vi: 'Đây là giới hạn byte bắt buộc. Mức giảm 80% tạo ra tệp không lớn hơn 20% dung lượng ban đầu.',
  th: 'นี่คือขีดจำกัดจำนวนไบต์แบบตายตัว การลด 80% จะได้ไฟล์ที่มีขนาดไม่เกิน 20% ของไฟล์ต้นฉบับ',
  pl: 'To ścisły limit liczby bajtów. Zmniejszenie o 80% daje plik nie większy niż 20% rozmiaru oryginału.',
};

const pdfPageLimits: Record<LocalePath, string> = {
  en: 'up to 40 pages',
  ja: '最大40ページ',
  ko: '최대 40페이지',
  es: 'hasta 40 páginas',
  fr: 'jusqu’à 40 pages',
  de: 'bis zu 40 Seiten',
  pt: 'até 40 páginas',
  'zh-cn': '最多 40 页',
  'zh-tw': '最多 40 頁',
  hi: 'अधिकतम 40 पेज',
  ar: 'حتى 40 صفحة',
  ru: 'до 40 страниц',
  id: 'hingga 40 halaman',
  it: 'fino a 40 pagine',
  nl: 'maximaal 40 pagina’s',
  tr: 'en fazla 40 sayfa',
  vi: 'tối đa 40 trang',
  th: 'สูงสุด 40 หน้า',
  pl: 'do 40 stron',
};

export function getWorkbenchMessages(locale: LocalePath) {
  return workbenchMessages[locale];
}

export function getHardReductionMessage(locale: LocalePath) {
  return hardReductionMessages[locale];
}

export function getPdfPageLimit(locale: LocalePath) {
  return pdfPageLimits[locale];
}
