import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
import {createWorker} from 'tesseract.js';
import {convertOfficeToPdf} from '../../src/lib/office-wasm/client';
import BackgroundWorker from '../../src/workers/background-removal.worker?worker';
const results:unknown[]=[];
const send=(value:unknown)=>(window as any).chrome.webview.postMessage(value);
const output=(id:string,data:Uint8Array)=>{let text='';for(let i=0;i<data.length;i+=8192)text+=String.fromCharCode(...data.subarray(i,i+8192));send({type:'output',id,data:btoa(text)});};
async function probe(id:string,run:()=>Promise<unknown>){const start=performance.now();try{const detail=await run();results.push({id,status:'PASS',durationMs:Math.round(performance.now()-start),detail});}catch(e){results.push({id,status:'FAIL',durationMs:Math.round(performance.now()-start),error:e instanceof Error?e.message:'Failed'});}document.querySelector('#result')!.textContent=JSON.stringify(results,null,2);}
await probe('pdf',async()=>{const doc=await PDFDocument.create();const font=await doc.embedFont(StandardFonts.Helvetica);for(let i=0;i<12;i++){const page=doc.addPage([612,792]);page.drawText('SoraFiles native PDF '+i,{x:48,y:700,font,size:24,color:rgb(.2,.2,.6)});}const bytes=await doc.save();const check=await PDFDocument.load(bytes);if(check.getPageCount()!==12)throw Error('Page count');output('pdf',bytes);return {pages:12};});
await probe('image',async()=>{const canvas=new OffscreenCanvas(1600,1000),ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,1600,1000);ctx.fillStyle='#0044ff';ctx.fillRect(400,250,800,500);const blob=await canvas.convertToBlob({type:'image/png'});const bitmap=await createImageBitmap(blob);if(bitmap.width!==1600)throw Error('Dimensions');bitmap.close();output('image',new Uint8Array(await blob.arrayBuffer()));return {width:1600,height:1000};});
await probe('ocr',async()=>{const canvas=new OffscreenCanvas(1400,300),ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,1400,300);ctx.fillStyle='#000';ctx.font='64px Arial';ctx.fillText('SoraFiles invoice 7631',45,150);const worker=await createWorker('eng',1,{workerPath:'/ocr/runtime/worker.min.js',corePath:'/ocr/runtime',langPath:'/ocr/lang',gzip:true});try{const r=await worker.recognize(await canvas.convertToBlob());if(!r.data.text.includes('7631'))throw Error('Known text missing');output('ocr',new TextEncoder().encode(r.data.text));return {knownIdentifier:true};}finally{await worker.terminate();}});
await probe('office',async()=>{const file=new File([await(await fetch('/fixture/complex.docx')).arrayBuffer()],'probe.docx');const bytes=await convertOfficeToPdf(file,'writer');const doc=await PDFDocument.load(bytes);if(doc.getPageCount()<1)throw Error('No pages');output('office',bytes);return {pages:doc.getPageCount()};});
await probe('background',async()=>{const worker=new BackgroundWorker();try{return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Inference timeout')),180000);worker.onerror=e=>{clearTimeout(timer);reject(Error(e.message));};worker.onmessage=async({data})=>{if(data.type==='error'){clearTimeout(timer);reject(Error(data.code||data.message||'Background failed'));}if(data.type==='result'){clearTimeout(timer);const blob=data.blob; if(!(blob instanceof Blob))return reject(Error('Missing output'));output('background',new Uint8Array(await blob.arrayBuffer()));resolve({bytes:blob.size});}};fetch('/fixture/product.png').then(r=>r.blob()).then(file=>worker.postMessage({file,publicPath:location.origin+'/model/',device:'cpu',model:'isnet_quint8',pixelLimit:40000000,cleanup:true})).catch(reject);});}finally{worker.terminate();}});
send({type:'complete',nativeHost:'WebView2',crossOriginIsolated,sharedArrayBuffer:typeof SharedArrayBuffer!=='undefined',userAgent:navigator.userAgent,results});
