import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync} from 'node:crypto';import {writeFile,readFile,readdir,rm} from 'node:fs/promises';import {localFixture} from './local-fixture.mjs';import {join} from 'node:path';import {PDFDocument} from 'pdf-lib';import {unzipSync} from 'fflate';import {createPdfJobQueue} from '../core/pdf-jobs.mjs';import {signEntitlement,entitlementClaims} from '../license-service/signing.mjs';
const pair=generateKeyPairSync('ed25519'),privateKey=pair.privateKey.export({format:'pem',type:'pkcs8'}),publicKey=pair.publicKey.export({format:'pem',type:'spki'}),now=1800000000;
function state(){const claims=entitlementClaims({license:{ref:'license',plan:'personal-monthly',status:'active',period_end:now+86400},deviceId:'device',now});return {token:signEntitlement(claims,{privateKey,kid:'test'}),verification:{keys:{test:publicKey},deviceId:'device',now:now*1000}};}
async function wait(queue){const end=Date.now()+5000;while(queue.list().some(j=>['queued','running'].includes(j.state))){if(Date.now()>end)throw Error('Job timeout');await new Promise(r=>setTimeout(r,10));}}
test('signed license gates real PDF processing through selected IDs, output validation and no-overwrite save',async()=>{const dir=await localFixture('sorafiles-pdf-job-');try{const doc=await PDFDocument.create();for(let i=0;i<3;i++)doc.addPage();const bytes=await doc.save(),source=join(dir,'source.pdf');await writeFile(source,bytes);let license=state();const queue=createPdfJobQueue({resolveSelection:async ids=>ids.map(id=>{if(id!=='selected')throw Error('Unknown selection');return source;}),readLicenseState:async()=>license});
 await queue.add('rotate-pdf',{selectionIds:['selected'],options:{rotations:[{pageIndex:0,angle:90}]}});await wait(queue);assert.equal(queue.list()[0].state,'completed');assert.equal((await PDFDocument.load(await readFile(queue.list()[0].result.path))).getPage(0).getRotation().angle,90);assert.deepEqual(await readFile(source),Buffer.from(bytes));
 await queue.add('split-pdf',{selectionIds:['selected'],options:{mode:'each'}});await wait(queue);const archive=unzipSync(await readFile(queue.list()[1].result.path));assert.equal(Object.keys(archive).length,3);assert.ok(Object.keys(archive).every(name=>/^source-page-\d{3}\.pdf$/.test(name)));
 license={...license,token:license.token.slice(0,-4)+'abcd'};const before=await readdir(dir);await assert.rejects(queue.add('remove-pages',{selectionIds:['selected'],options:{remove:[0]}}));assert.deepEqual(await readdir(dir),before);
 }finally{await rm(dir,{recursive:true,force:true});}});
