import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync,sign,createHash} from 'node:crypto';import {mkdtemp,writeFile,rm} from 'node:fs/promises';import {join} from 'node:path';import {tmpdir} from 'node:os';
import {verifyReleaseEnvelope,trustedUpdate,verifyStagedUpdate,artifactSignatureMessage} from '../shared/update-trust.mjs';
const now=1800000000,pair=generateKeyPairSync('ed25519'),keys={test:pair.publicKey.export({format:'pem',type:'spki'})};
const payload=Buffer.from('synthetic signed installer, never executable');
function artifact(){const a={version:'1.1.0',minOS:'10.0',channel:'stable',platform:'windows',arch:'x64',package:'msi',status:'active',security:'clear',url:'https://downloads.sorafiles.com/1.1.0/windows-x64.msi',bytes:payload.length,sha256:createHash('sha256').update(payload).digest('hex'),releaseDate:'2026-09-12',notes:'Synthetic QA fixture',tested:true,signing:'signed',updaterEligible:true};a.updateSignature='test.'+sign(null,artifactSignatureMessage(a),pair.privateKey).toString('base64url');return a;}
function envelope(patch={}){const manifest={schema:1,sequence:1,issuedAt:now,expiresAt:now+86400,releases:[artifact()],...patch},raw=Buffer.from(JSON.stringify(manifest));return {kid:'test',payload:raw.toString('base64url'),signature:sign(null,Buffer.concat([Buffer.from('sorafiles-release-manifest-v1\n'),raw]),pair.privateKey).toString('base64url')};}
const options={keys,now,device:{currentVersion:'1.0.0',osVersion:'10.0',platform:'windows',arch:'x64',packageType:'msi'},downloadOrigins:['https://downloads.sorafiles.com']};
test('signed manifest and signed compatible artifact are both required',()=>{assert.equal(trustedUpdate(envelope(),options).release.version,'1.1.0');const e=envelope();e.payload=Buffer.from('{}').toString('base64url');assert.throws(()=>trustedUpdate(e,options),/signature/);const a=artifact();a.bytes++;assert.throws(()=>trustedUpdate(envelope({releases:[a]}),options),/signature/);assert.throws(()=>trustedUpdate(envelope(),{...options,downloadOrigins:[]}),/origin/);});
test('expired metadata, rollback/equivocation, unknown keys, wrong OS and downgrade attempts are rejected',()=>{assert.throws(()=>verifyReleaseEnvelope(envelope({expiresAt:now}),options),/expired/);assert.throws(()=>verifyReleaseEnvelope(envelope(),{...options,trustedState:{sequence:2,digest:'newer'}}),/rollback/);const e=envelope(),state=verifyReleaseEnvelope(e,options).trustedState;assert.ok(verifyReleaseEnvelope(e,{...options,trustedState:state}));assert.throws(()=>verifyReleaseEnvelope(envelope({expiresAt:now+1}),{...options,trustedState:state}),/rollback/);assert.throws(()=>verifyReleaseEnvelope({...e,kid:'unknown'},options),/key/);assert.equal(trustedUpdate(e,{...options,device:{...options.device,currentVersion:'2.0.0'}}).release,null);assert.equal(trustedUpdate(e,{...options,device:{...options.device,osVersion:'6.1'}}).release,null);assert.throws(()=>trustedUpdate(e,{...options,device:{...options.device,osVersion:null}}),/identity/);});
test('installer bytes are hashed independently and tampering or truncation is rejected',async()=>{const dir=await mkdtemp(join(tmpdir(),'sorafiles-update-'));try{const path=join(dir,'fixture.msi'),a=artifact();await writeFile(path,payload);assert.equal((await verifyStagedUpdate(path,a,{keys})).verified,true);const tampered=Buffer.from(payload);tampered[0]^=1;await writeFile(path,tampered);await assert.rejects(verifyStagedUpdate(path,a,{keys}),/integrity/);await writeFile(path,payload.subarray(0,3));await assert.rejects(verifyStagedUpdate(path,a,{keys}),/size/);}finally{await rm(dir,{recursive:true,force:true});}});
