import './styles.css';
import './brand.css';
import {capabilities,relevantActions,searchTools} from '../shared/capabilities.mjs';
import {host,onNativeSelection} from './host';
type Selected={id:string;name:string;format:string|null;validated:boolean;bytes:number};
const root=document.querySelector<HTMLElement>('#app')!;
const state={page:'home',query:'',tool:'',files:[] as Selected[],busy:false,error:'',notice:'',license:'not-activated',activationAvailable:false,plan:'',expiresAt:null as number|null,devices:[] as {id:string;current:boolean;active:boolean}[],output:'source',startup:false,theme:'system',version:'Development build',platform:'windows'};
const licenseReady=()=>['active','trial'].includes(state.license);
const planLabel=()=>state.plan.split('-').map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ');
const escape=(value:unknown)=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const paths:Record<string,string>={home:'M3 10 12 3l9 7v10H3V10Zm6 10v-7h6v7',grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',lock:'M6 10h12a2 2 0 0 1 2 2v8H4v-8a2 2 0 0 1 2-2Zm2 0V7a4 4 0 0 1 8 0v3M12 14v3',settings:'m12 3 2 3 4-1 1 4 3 3-3 2 1 4-4 1-4 3-2-3-4 1-1-4-3-3 3-2-1-4 4-1 4-3Zm0 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',update:'M20 8a8 8 0 1 0 0 8M20 3v5h-5',file:'M6 3h8l4 4v14H6V3Zm8 0v5h4M9 12h6M9 16h6',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14Zm5 12 6 6',folder:'M3 6h7l2 3h9v11H3V6',arrow:'M5 12h14m-5-5 5 5-5 5',upload:'M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',image:'M3 3h18v18H3zM3 16l6-6 5 5 3-3 4 4M15 7h.01',compress:'M3 8h5V3m0 5L3 3m18 5h-5V3m0 5 5-5M3 16h5v5m0-5-5 5m18-5h-5v5m0-5 5 5',merge:'M5 3v5l7 6 7-6V3m-7 11v7m-4-4 4 4 4-4',power:'M12 3v9M6 5a9 9 0 1 0 12 0'};
const icon=(name:string,cls='')=>`<svg class="icon ${cls}" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]||paths.file}"/></svg>`;
const toolIcon=(id:string)=>id.includes('compress')?'compress':id==='merge-pdf'?'merge':id.includes('image')||id==='remove-background'||id==='heic-to-jpg'?'image':'file';
const common=['compress-pdf','merge-pdf','image-converter','resize-image','remove-background','pdf-ocr'];
function toolButton(tool:any){return `<button class="tool-card" data-tool="${tool.id}"><span class="tool-icon ${tool.formats[0]==='PDF'?'purple':'blue'}">${icon(toolIcon(tool.id))}</span><span><strong>${escape(tool.name)}</strong><small>${escape(tool.formats.slice(0,3).join(', '))}${tool.formats.length>3?' + more':''}</small></span>${icon('arrow','card-arrow')}</button>`;}
const feedback=()=>`${state.error?`<div role="alert" class="feedback error">${escape(state.error)}</div>`:''}${state.notice?`<div role="status" class="feedback">${escape(state.notice)}</div>`:''}`;
function heading(eyebrow:string,title:string,description:string){return `<header class="page-heading"><p class="eyebrow">${eyebrow}</p><h1 tabindex="-1">${title}</h1><p>${description}</p></header>`;}
function selected(){if(!state.files.length)return '';return `<div class="selected"><div class="section-title"><h2>${state.files.length} ${state.files.length===1?'file':'files'} selected</h2><button class="text-button" data-action="clear">Clear selection</button></div><ul>${state.files.map(f=>`<li>${icon(f.format==='PDF'?'file':'image')}<span>${escape(f.name)}<small>${f.format||'Needs inspection'} · ${new Intl.NumberFormat('en',{maximumFractionDigits:1}).format(f.bytes/1024)} KB</small></span><button class="icon-button" data-remove="${escape(f.id)}" aria-label="Remove ${escape(f.name)}">${icon('close')}</button></li>`).join('')}</ul></div>`;}
function dropzone(compact=false){return `<div class="dropzone ${compact?'compact':''}" data-dropzone><span class="drop-icon">${icon('upload')}</span><h2>${state.files.length?'Add more files':'Drop your files here'}</h2><p>PDFs, images and documents. Choose what to do next.</p><button class="primary" data-action="select" ${state.busy?'disabled':''}>${icon('folder')}Choose files</button><small>Your originals stay untouched.</small></div>`;}
function home(){const suggestions=state.files.length?relevantActions(state.files,true):capabilities.filter(t=>common.includes(t.id));return `${heading('YOUR FILES. YOUR DEVICE.','File tools for your desktop.','Convert, compress and organize files, right where they are.')}${feedback()}${dropzone(state.files.length>0)}${selected()}<section class="tool-section"><div class="section-title"><h2>${state.files.length?'Works with your selection':'Everyday tools'}</h2><button class="text-button" data-page="tools">All ${capabilities.length} tools ${icon('arrow')}</button></div><div class="tool-grid">${suggestions.filter(t=>t.id!=='open').map(toolButton).join('')||'<p>No quick action matches this selection. Choose a tool to inspect the files.</p>'}</div></section><p class="privacy-note">${icon('lock')}File processing stays on your device.</p>`;}
function tools(){const list=searchTools(state.query);return `${heading('FIND YOUR NEXT STEP','All tools','One place for your PDFs, images and documents.')}<label class="search-box">${icon('search')}<input id="tool-search" type="search" placeholder="Search tools, e.g. merge PDF" value="${escape(state.query)}" aria-label="Search tools" autocomplete="off"><kbd>${state.platform==='macos'?'⌘ K':'Ctrl K'}</kbd></label><div id="tool-results"><p class="result-count">${list.length} tools</p><div class="tool-grid">${list.map(toolButton).join('')}</div>${!list.length?'<div class="empty"><h2>No tools found</h2><p>Try “PDF”, “image” or “compress”.</p><button class="secondary" data-action="reset-search">Clear search</button></div>':''}</div>`;}
function workspace(){const tool=capabilities.find(t=>t.id===state.tool)!;return `<button class="text-button back" data-page="tools">← All tools</button>${heading('ON YOUR DEVICE',escape(tool.name),`Choose ${escape(tool.formats.join(', '))} files to get started.`)}${feedback()}${dropzone(true)}${selected()}<section class="panel output-panel"><div>${icon('folder')}<h2>Save results</h2></div><p>${state.output==='source'?'Beside each original file':state.output==='downloads'?'Your Downloads folder':state.output==='ask'?'Choose a folder each time':'Your chosen folder'}</p><p class="muted">If a name is taken, we add a number. Your originals are kept.</p><button class="text-button" data-page="settings">Change output settings</button></section><div class="action-bar"><div>${icon('lock')}<span>Start your trial or activate a license to process files.</span></div><button class="primary" data-page="license">Set up Desktop ${icon('arrow')}</button></div>`;}
function activationForm(){return `<section class="panel"><h2>Already have a license?</h2><p>Find your license key in your purchase email. Activation permanently binds a license seat to this device.</p><form id="license-form"><label for="license-key">License key</label><div class="key-field"><input id="license-key" name="license-key" type="password" autocomplete="off" spellcheck="false" required><button type="button" class="text-button" data-action="reveal-key" aria-controls="license-key" aria-pressed="false">Show</button></div><button type="submit" class="secondary" ${state.busy?'disabled':''}>Activate license</button></form></section>`;}
function license(){if(['active','trial','needs-verification'].includes(state.license))return activeLicense();return `${heading('SORAFILES DESKTOP','Activate SoraFiles Desktop.','Start a 7-day trial, or activate the license you already have.')}${feedback()}<div class="license-grid"><section class="panel"><span class="badge">7 days to try</span><h2>Try Desktop</h2><p>Explore local processing and quick file actions. An internet connection is needed to start your trial.</p><button class="primary" data-action="trial" ${state.busy?'disabled':''}>Start free trial</button><small>No files are sent for activation.</small></section>${activationForm()}</div><p class="privacy-note">${icon('lock')}SoraFiles Web stays free.</p>`;}
function activeLicense(){
 const needsCheck=state.license==='needs-verification',trial=state.license==='trial'||state.activationAvailable;
 const title=needsCheck?(trial?'Your trial needs a check':'Your license needs a check'):trial?'Your trial is active':'Desktop is activated';
 const expiry=needsCheck?'Check required':state.expiresAt?new Intl.DateTimeFormat('en',{dateStyle:'medium'}).format(state.expiresAt*1000):state.plan.includes('lifetime')?'No expiry':'Check required';
 return `${heading('SORAFILES DESKTOP',title,'Activation and license checks need an internet connection. File processing stays on your device.')}${feedback()}<section class="panel"><h2>${trial?'7-day trial':escape(planLabel())||'License status'}</h2><p>${trial?'Trial ends':'Offline access'}: ${escape(expiry)}</p>${trial&&needsCheck?'<p>Your trial may have ended, or this device could not verify it. You can activate a purchased license below.</p>':''}${!trial?'<div class="license-actions"><button class="secondary" data-action="refresh-license">Check license online</button><button class="text-button" data-action="license-devices">View bound devices</button></div>':''}${state.devices.length?'<ul>'+state.devices.map((d,i)=>'<li>'+(d.current?'This device':'Device '+(i+1))+(d.active?'':' — unavailable')+'</li>').join('')+'</ul>':''}${!trial?'<div class="setting-row"><div><strong>Bound to this device</strong><p>Each activated license seat is permanently linked to its device. It cannot be deactivated or transferred.</p></div></div>':''}</section>${trial?activationForm():''}`;
}
function settings(){return `${heading('MAKE IT YOURS','Settings','Simple defaults for the way you work.')}${feedback()}<section class="panel settings-panel"><h2>Output location</h2><p>Choose where new files are saved.</p><label for="output-mode" class="sr-only">Default output location</label><select id="output-mode">${[['source','Same folder as source'],['downloads','Downloads'],['custom','Custom folder'],['ask','Ask each time']].map(([value,label])=>`<option value="${value}" ${state.output===value?'selected':''}>${label}</option>`).join('')}</select>${state.output==='custom'?'<button class="secondary" data-action="folder">Choose folder</button>':''}<div class="setting-row"><div><strong>Keep originals safe</strong><p>New results get a numbered name if one already exists.</p></div><span class="quiet-badge">Always on</span></div><div class="setting-row"><div><strong>Quick actions after sign-in</strong><p>Keep the lightweight helper available without opening a window.</p></div><input type="checkbox" id="startup" aria-label="Keep quick actions available after sign-in" ${state.startup?'checked':''}></div><div class="setting-row"><label for="theme">Appearance</label><select id="theme">${['system','light','dark'].map(value=>`<option value="${value}" ${state.theme===value?'selected':''}>${value[0].toUpperCase()+value.slice(1)}</option>`).join('')}</select></div></section>`;}
function updates(){return `${heading('BUILT BY SORA LABS','Updates & about','A private space for working with your files.')}${feedback()}<section class="panel about-panel"><img src="/icon-192.png" width="64" height="64" alt=""><h2>SoraFiles Desktop</h2><p>${escape(state.version)}</p><p>This development build is not a released installer.</p><button class="secondary" data-action="updates">Check for updates</button></section>`;}
function render(){document.documentElement.dataset.theme=state.theme;root.innerHTML=`<a class="skip-link" href="#main">Skip to content</a><aside class="sidebar"><div class="brand"><img src="/icon-192.png" alt="" width="36" height="36"><div>SoraFiles<span>DESKTOP</span></div></div><nav aria-label="Main navigation">${[['home','Home','home'],['tools','All tools','grid'],['license','License','lock'],['settings','Settings','settings'],['updates','Updates & about','update']].map(([id,name,glyph])=>`<button aria-label="${name}" data-page="${id}" ${state.page===id||state.page==='workspace'&&id==='tools'?'aria-current="page"':''}>${icon(glyph)}<span>${name}</span></button>`).join('')}</nav><div class="sidebar-bottom"><div class="trial-card">${icon('lock')}<strong>${licenseReady()?state.license==='trial'?'Your trial is active':'Desktop is activated':'Your Desktop license'}</strong><p>${licenseReady()?'Your files. On your device.':state.license==='needs-verification'?'Your license needs a check.':'Get started with a trial or license.'}</p><button class="secondary" data-page="license">${licenseReady()?'Manage license':'View license'}</button></div><button class="quit" data-action="quit" aria-label="Quit SoraFiles" title="Quit SoraFiles">${icon('power')}<span>Quit SoraFiles</span></button><small>Development build</small></div></aside><main id="main" tabindex="-1">${state.page==='home'?home():state.page==='tools'?tools():state.page==='workspace'?workspace():state.page==='license'?license():state.page==='settings'?settings():updates()}</main>`;syncBusy();}
function navigate(page:string){state.page=page;state.error='';state.notice='';render();root.querySelector<HTMLElement>('h1')?.focus();}
function syncBusy(){
 root.querySelectorAll<HTMLButtonElement|HTMLInputElement|HTMLSelectElement>('[data-action]:not([data-action="reveal-key"]),[data-remove],select,input[type="checkbox"],button[type="submit"]').forEach(control=>control.disabled=state.busy);
 root.setAttribute('aria-busy',String(state.busy));
 document.querySelector<HTMLElement>('#pending-action')!.hidden=!state.busy;
}
function restoreFocus(previous:HTMLElement|null){
 const attributes=['id','data-action','data-remove','data-page'];
 const attribute=attributes.find(name=>previous?.hasAttribute(name));
 const replacement=attribute?root.querySelector<HTMLElement>(`[${attribute}="${CSS.escape(previous!.getAttribute(attribute)!)}"]`):null;
 (replacement||root.querySelector<HTMLElement>('h1'))?.focus({preventScroll:true});
}
async function perform(run:()=>Promise<void>){
 if(state.busy)return;
 const page=state.page,origin=document.activeElement as HTMLElement;state.busy=true;state.error='';state.notice='';
 root.querySelectorAll('.feedback').forEach(node=>node.remove());syncBusy();
 try{await run();}catch(error){state.error=error instanceof Error?error.message:'This action could not finish. Try again.';}
 finally{
  state.busy=false;
  // Do not replace a different screen the user opened while waiting.
  if(state.page===page){const focused=document.activeElement===document.body?origin:document.activeElement as HTMLElement;render();restoreFocus(focused);}
  syncBusy();document.querySelector('#announcement')!.textContent=state.page===page?'':state.error||state.notice;
 }
}
function acceptFiles(selection:Selected[]|{files:Selected[];rejected:boolean}){
 const files=Array.isArray(selection)?selection:selection.files;
 if(!Array.isArray(selection)&&selection.rejected)state.error='Some files could not be added. Choose readable, non-empty files on this device, up to 512 MB each and 256 files at a time.';
 if(!files.length)return;
 state.files=[...new Map([...state.files,...files].map(f=>[f.id,f])).values()].slice(0,256);
 if(state.page!=='workspace'&&state.page!=='home'){state.page='home';render();}
}
root.addEventListener('click',event=>{const target=(event.target as HTMLElement).closest<HTMLButtonElement>('button');if(!target)return;if(target.dataset.page){navigate(target.dataset.page);return;}if(target.dataset.tool){state.tool=target.dataset.tool;navigate('workspace');return;}if(target.dataset.remove){const id=target.dataset.remove;void perform(async()=>{await host('releaseSelection',{ids:[id]});state.files=state.files.filter(f=>f.id!==id);});return;}
 switch(target.dataset.action){case 'select':void perform(async()=>acceptFiles(await host('selectFiles')));break;case 'clear':void perform(async()=>{await host('releaseSelection',{ids:state.files.map(f=>f.id)});state.files=[];});break;case 'reset-search':state.query='';render();document.querySelector<HTMLInputElement>('#tool-search')?.focus();break;case 'trial':void perform(async()=>{Object.assign(state,await host('startTrial'));state.notice='Trial activated.';});break;case 'refresh-license':void perform(async()=>{Object.assign(state,await host('refreshLicense'));state.notice='License verified.';});break;case 'license-devices':void perform(async()=>{state.devices=(await host('licenseDevices')).devices;});break;case 'folder':void perform(async()=>{const result=await host('chooseFolder');if(result.selected)state.notice='Output folder saved.';});break;case 'updates':void perform(async()=>{const result=await host('checkUpdates');state.notice=result.message;});break;case 'quit':void perform(async()=>{await host('quit');});break;case 'reveal-key':{const input=document.querySelector<HTMLInputElement>('#license-key')!;input.type=input.type==='password'?'text':'password';target.textContent=input.type==='password'?'Show':'Hide';target.setAttribute('aria-pressed',String(input.type==='text'));break;}}
});
root.addEventListener('input',event=>{const input=event.target as HTMLInputElement;if(input.id!=='tool-search')return;state.query=input.value;const position=input.selectionStart;render();const replacement=document.querySelector<HTMLInputElement>('#tool-search')!;replacement.focus();try{replacement.setSelectionRange(position,position);}catch{}});
root.addEventListener('change',event=>{const input=event.target as HTMLInputElement;if(input.id==='output-mode'||input.id==='theme'||input.id==='startup')void perform(async()=>{const settings=await host('saveSettings',{[input.id==='output-mode'?'output':input.id]:input.type==='checkbox'?input.checked:input.value});Object.assign(state,settings);});});
root.addEventListener('submit',event=>{if((event.target as HTMLFormElement).id!=='license-form')return;event.preventDefault();const input=document.querySelector<HTMLInputElement>('#license-key')!;const key=input.value.trim();if(!key)return;input.value='';void perform(async()=>{Object.assign(state,await host('activate',{licenseKey:key}));state.notice='License activated.';});});
root.addEventListener('dragover',event=>{event.preventDefault();(event.target as HTMLElement).closest('[data-dropzone]')?.classList.add('dragging');});root.addEventListener('dragleave',event=>(event.target as HTMLElement).closest('[data-dropzone]')?.classList.remove('dragging'));
root.addEventListener('drop',event=>{event.preventDefault();const files=Array.from(event.dataTransfer?.files||[]);if(files.length)void perform(async()=>acceptFiles(await host('dropFiles',{},files)));});
document.addEventListener('keydown',event=>{if((state.platform==='macos'?event.metaKey:event.ctrlKey)&&!event.altKey&&event.key.toLowerCase()==='o'){event.preventDefault();void perform(async()=>acceptFiles(await host('selectFiles')));}if(state.platform==='macos'&&event.metaKey&&event.key===','){event.preventDefault();navigate('settings');}if((state.platform==='macos'?event.metaKey:event.ctrlKey)&&!event.altKey&&event.key.toLowerCase()==='k'){event.preventDefault();navigate('tools');document.querySelector<HTMLInputElement>('#tool-search')?.focus();}if(event.key==='Escape'){if(state.page==='tools'&&state.query){state.query='';render();document.querySelector<HTMLInputElement>('#tool-search')?.focus();}else if(state.page==='workspace')navigate('tools');}if(event.key==='Enter'&&(event.target as HTMLElement).id==='tool-search'){const first=searchTools(state.query)[0];if(first){event.preventDefault();state.tool=first.id;navigate('workspace');}}});
onNativeSelection(selection=>{acceptFiles(selection);render();});
render();void host('getState').then(data=>{Object.assign(state,data);render();void host('licenseStatus').then(status=>{Object.assign(state,status);render();}).catch(()=>{});}).catch(error=>{state.error=error.message;render();});
